const steamImage = (appId) => `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;
const youtube = (id) => `https://www.youtube.com/watch?v=${id}`;
const youtubeSearch = (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q + " co-op gameplay")}`;

window.GAMES = [
  {
    id: "gears-of-war-reloaded",
    title: "Gears of War: Reloaded",
    year: 2025,
    genres: ["AAA", "Shooter", "Third-person", "Action"],
    endingType: "story",
    rating: 79,
    playersMax: 2,
    hours: 9,
    oneCopy: "none",
    price: 1299,
    verdict: "Самый прямой наследник ощущения Army of Two: укрытия, мясо, дуо.",
    storeUrl: "https://store.steampowered.com/app/2523720/Gears_of_War_Reloaded/",
    imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2523720/779c1934da3b39c307d91195ff764502f2ce1063/capsule_616x353.jpg",
    youtubeUrl: youtube("UHg5MMnsMJ4")
  },
  {
    id: "space-marine-2",
    title: "Warhammer 40,000: Space Marine 2",
    year: 2024,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Sci-fi"],
    endingType: "story",
    rating: 82,
    playersMax: 3,
    hours: 11,
    oneCopy: "none",
    price: 1299,
    verdict: "Очень жирный современный кооп-экшен. Не про укрытия, а про продавить всё силой.",
    storeUrl: "https://store.steampowered.com/app/2183900/Warhammer_40000_Space_Marine_2/",
    imageUrl: steamImage(2183900),
    youtubeUrl: youtube("_5qGL9IK-XY")
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    year: 2023,
    genres: ["AAA", "RPG", "Tactics", "Fantasy"],
    endingType: "story",
    rating: 96,
    playersMax: 4,
    hours: 85,
    oneCopy: "none",
    price: 899,
    verdict: "Лучший вариант, если окей пошаговая ролевая игра и большая законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
    imageUrl: steamImage(1086940),
    youtubeUrl: youtube("UxSgaBXMqP4")
  },
  {
    id: "remnant-2",
    title: "Remnant II",
    year: 2023,
    genres: ["AA", "Shooter", "Action", "RPG", "Soulslike"],
    endingType: "story",
    rating: 80,
    playersMax: 3,
    hours: 22,
    oneCopy: "none",
    price: 1299,
    verdict: "Dark Souls с пушками. Кампания конечная, но игра любит повторные прохождения и лут.",
    storeUrl: "https://store.steampowered.com/app/1282100/REMNANT_II/",
    imageUrl: steamImage(1282100),
    youtubeUrl: youtube("x3ZheAh5oPc")
  },
  {
    id: "trine-5",
    title: "Trine 5: A Clockwork Conspiracy",
    year: 2023,
    genres: ["AA", "Puzzle", "Platformer", "Fantasy"],
    endingType: "story",
    rating: 78,
    playersMax: 4,
    hours: 13,
    oneCopy: "remote-play",
    price: 600,
    verdict: "Кооп-пазлы и платформинг. Не AAA, но аккуратная законченная игра.",
    storeUrl: "https://store.steampowered.com/app/1436700/Trine_5_A_Clockwork_Conspiracy/",
    imageUrl: steamImage(1436700),
    youtubeUrl: youtube("MDCcvLZVEnM")
  },
  {
    id: "sniper-elite-5",
    title: "Sniper Elite 5",
    year: 2022,
    genres: ["AA", "Shooter", "Stealth", "Tactics", "Military"],
    endingType: "story",
    rating: 79,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 579,
    verdict: "Медленнее Army of Two: стелс, снайпинг, тактика. Вдвоём работает хорошо.",
    storeUrl: "https://store.steampowered.com/app/1029690/Sniper_Elite_5/",
    imageUrl: steamImage(1029690),
    youtubeUrl: youtube("uG8LCpWPZlg")
  },
  {
    id: "we-were-here-forever",
    title: "We Were Here Forever",
    year: 2022,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 56,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 375,
    verdict: "Пазл-кооп с голосовой связью. Не экшен, но именно игра для двоих.",
    storeUrl: "https://store.steampowered.com/app/1341290/We_Were_Here_Forever/",
    imageUrl: steamImage(1341290),
    youtubeUrl: youtube("YeNCUS_Cdas")
  },
  {
    id: "operation-tango",
    title: "Operation: Tango",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 76,
    playersMax: 2,
    hours: 4,
    oneCopy: "friend-pass",
    price: 415,
    verdict: "Асимметричный шпионский кооп: один агент, второй хакер. Короткая, зато честно сделана под двух игроков.",
    storeUrl: "https://store.steampowered.com/app/1335790/Operation_Tango/",
    imageUrl: steamImage(1335790),
    youtubeUrl: youtube("CIJZ2tfW__8")
  },
  {
    id: "the-ascent",
    title: "The Ascent",
    year: 2021,
    genres: ["AA", "Shooter", "Action", "RPG", "Sci-fi", "Isometric"],
    endingType: "story",
    rating: 74,
    playersMax: 4,
    hours: 14,
    oneCopy: "remote-play",
    price: 635,
    verdict: "Киберпанк twin-stick шутер. Красивый, но сюжет не главный козырь.",
    storeUrl: "https://store.steampowered.com/app/979690/The_Ascent/",
    imageUrl: steamImage(979690),
    youtubeUrl: youtube("vXUTYzj_bKE")
  },
  {
    id: "outriders",
    title: "Outriders",
    year: 2021,
    genres: ["AAA", "Shooter", "Action", "RPG", "Loot", "Sci-fi"],
    endingType: "story",
    rating: 73,
    playersMax: 3,
    hours: 20,
    oneCopy: "none",
    price: 499,
    verdict: "Кампания есть и заканчивается, но это лутер-шутер. Брать, если окей гриндовая ДНК.",
    storeUrl: "https://store.steampowered.com/app/680420/OUTRIDERS/",
    imageUrl: steamImage(680420),
    youtubeUrl: youtube("S8TaAcA0_Ug")
  },
  {
    id: "wasteland-3",
    title: "Wasteland 3",
    year: 2020,
    genres: ["AA", "RPG", "Tactics"],
    endingType: "story",
    rating: 85,
    playersMax: 2,
    hours: 50,
    oneCopy: "none",
    price: 479,
    verdict: "Пошаговая ролевая игра с нормальным сюжетом и решениями. Хороший кооп, если хочется не шутер.",
    storeUrl: "https://store.steampowered.com/app/719040/Wasteland_3/",
    imageUrl: steamImage(719040),
    youtubeUrl: youtube("4XY4BAtJuow")
  },
  {
    id: "gears-5",
    title: "Gears 5",
    year: 2019,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Sci-fi"],
    endingType: "story",
    rating: 82,
    playersMax: 3,
    hours: 11,
    oneCopy: "none",
    price: 760,
    verdict: "Один из лучших вариантов под запрос: AAA, сюжет, экшен, можно проходить вдвоём.",
    storeUrl: "https://store.steampowered.com/app/1097840/Gears_5/",
    imageUrl: steamImage(1097840),
    youtubeUrl: youtube("yxnXis9OV_E")
  },
  {
    id: "halo-mcc",
    title: "Halo: The Master Chief Collection",
    year: 2019,
    genres: ["AAA", "Shooter", "FPS", "Sci-fi"],
    endingType: "story",
    rating: 91,
    playersMax: 4,
    hours: 55,
    oneCopy: "none",
    price: 1399,
    verdict: "Много законченных кампаний в одном пакете. Минус - это FPS, не постановочный дуо-боевик.",
    storeUrl: "https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/",
    imageUrl: steamImage(976730),
    youtubeUrl: youtube("yTy41rmm6rk")
  },
  {
    id: "darksiders-genesis",
    title: "Darksiders Genesis",
    year: 2019,
    genres: ["AA", "Action", "Isometric", "Fantasy"],
    endingType: "story",
    rating: 77,
    playersMax: 2,
    hours: 14,
    oneCopy: "remote-play",
    price: 389,
    verdict: "Изометрический экшен про двух персонажей. Ближе к Diablo/Darksiders, чем к Army of Two.",
    storeUrl: "https://store.steampowered.com/app/710920/Darksiders_Genesis/",
    imageUrl: steamImage(710920),
    youtubeUrl: youtube("C7Hxw08wRfs")
  },
  {
    id: "wolfenstein-youngblood",
    title: "Wolfenstein: Youngblood",
    year: 2019,
    genres: ["AAA", "Shooter", "FPS", "Action", "Sci-fi"],
    endingType: "story",
    rating: 69,
    playersMax: 2,
    hours: 10,
    oneCopy: "friend-pass",
    price: 349,
    verdict: "Кооп и кампания есть, но игра спорная. Buddy Pass работает через Deluxe Edition.",
    storeUrl: "https://store.steampowered.com/app/1056960/Wolfenstein_Youngblood/",
    imageUrl: steamImage(1056960),
    youtubeUrl: youtube("lFM7zFCVwgo")
  },
  {
    id: "far-cry-5",
    title: "Far Cry 5",
    year: 2018,
    genres: ["AAA", "Shooter", "FPS", "Open World", "Action"],
    endingType: "story",
    rating: 78,
    playersMax: 2,
    hours: 22,
    oneCopy: "none",
    price: 915,
    verdict: "Открытый мир, не постановочная дуо-игра. Вдвоём весело, но сюжетно рыхло.",
    storeUrl: "https://store.steampowered.com/app/552520/Far_Cry_5/",
    imageUrl: steamImage(552520),
    youtubeUrl: youtube("n-lJd1gueOQ")
  },
  {
    id: "divinity-original-sin-2",
    title: "Divinity: Original Sin II",
    year: 2017,
    genres: ["AAA", "RPG", "Tactics", "Fantasy"],
    endingType: "story",
    rating: 93,
    playersMax: 4,
    hours: 75,
    oneCopy: "remote-play",
    price: 529,
    verdict: "Если BG3 зайдёт, это почти обязательная следующая остановка. Кампания огромная и законченная.",
    storeUrl: "https://store.steampowered.com/app/435150/Divinity_Original_Sin_2/",
    imageUrl: steamImage(435150),
    youtubeUrl: youtube("unWFWGrMbpc")
  },
  {
    id: "ghost-recon-wildlands",
    title: "Ghost Recon Wildlands",
    year: 2017,
    genres: ["AAA", "Shooter", "Third-person", "Open World", "Tactics", "Military"],
    endingType: "story",
    rating: 80,
    playersMax: 4,
    hours: 35,
    oneCopy: "none",
    price: 759,
    verdict: "Военный кооп в открытом мире. Сюжет слабее, зато двое чистят карту работает.",
    storeUrl: "https://store.steampowered.com/app/460930/Tom_Clancys_Ghost_Recon_Wildlands/",
    imageUrl: steamImage(460930),
    youtubeUrl: youtube("7UboU-rioaY")
  },
  {
    id: "portal-2",
    title: "Portal 2",
    year: 2011,
    genres: ["AAA", "Puzzle", "FPS", "Sci-fi"],
    endingType: "story",
    rating: 95,
    playersMax: 2,
    hours: 5,
    oneCopy: "remote-play",
    price: 225,
    verdict: "Если не проходил кооп-кампанию, это must-play. Не просто режим, а отдельная игра на двоих.",
    storeUrl: "https://store.steampowered.com/app/620/Portal_2/",
    imageUrl: steamImage(620),
    youtubeUrl: youtube("aySPmEBzlS4")
  },
  {
    id: "lara-croft-guardian-light",
    title: "Lara Croft and the Guardian of Light",
    year: 2010,
    genres: ["AAA", "Action", "Puzzle", "Adventure", "Isometric"],
    endingType: "story",
    rating: 82,
    playersMax: 2,
    hours: 7,
    oneCopy: "remote-play",
    price: 180,
    verdict: "Старенькая, но крепкая приключенческая кооп-игра с пазлами и боёвкой.",
    storeUrl: "https://store.steampowered.com/app/35130/Lara_Croft_and_the_Guardian_of_Light/",
    imageUrl: steamImage(35130),
    youtubeUrl: youtube("nER0GNRlK_c")
  },
  {
    id: "borderlands-3",
    title: "Borderlands 3",
    year: 2019,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot", "Open World"],
    endingType: "story",
    rating: 81,
    playersMax: 4,
    hours: 23,
    oneCopy: "none",
    price: 849,
    verdict: "Крупная кооп-кампания с отличной стрельбой и лутом. Сюжет спорный, но вдвоём темп держит хорошо.",
    storeUrl: "https://store.steampowered.com/app/397540/Borderlands_3/",
    imageUrl: steamImage(397540),
    youtubeUrl: youtube("KojWXk9Vgso")
  },
  {
    id: "tiny-tinas-wonderlands",
    title: "Tiny Tina's Wonderlands",
    year: 2022,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot", "Fantasy"],
    endingType: "story",
    rating: 80,
    playersMax: 4,
    hours: 17,
    oneCopy: "none",
    price: 1249,
    verdict: "Borderlands в фэнтези-обёртке. Хороший вариант, если хочется стрельбы, классов и более лёгкого тона.",
    storeUrl: "https://store.steampowered.com/app/1286680/Tiny_Tinas_Wonderlands/",
    imageUrl: steamImage(1286680),
    youtubeUrl: youtube("L0wnhP_mQKA")
  },
  {
    id: "dying-light",
    title: "Dying Light",
    year: 2015,
    genres: ["AAA", "Action", "FPS", "RPG", "Open World", "Horror"],
    endingType: "story",
    rating: 75,
    playersMax: 4,
    hours: 18,
    oneCopy: "none",
    price: 349,
    verdict: "Паркур, зомби и полный кооп кампании после вступления. Более грязный и живой вариант для двоих.",
    storeUrl: "https://store.steampowered.com/app/239140/Dying_Light/",
    imageUrl: steamImage(239140),
    youtubeUrl: youtube("pL4a6QkzkLs")
  },
  {
    id: "dying-light-2",
    title: "Dying Light 2 Stay Human",
    year: 2022,
    genres: ["AAA", "Action", "FPS", "RPG", "Open World", "Horror"],
    endingType: "story",
    rating: 77,
    playersMax: 4,
    hours: 24,
    oneCopy: "none",
    price: 1599,
    verdict: "Больше открытого мира и паркура, чем в первой части. Кооп есть почти на всю кампанию, прогресс сильнее завязан на хоста.",
    storeUrl: "https://store.steampowered.com/app/534380/Dying_Light_2_Stay_Human_Reloaded_Edition/",
    imageUrl: steamImage(534380),
    youtubeUrl: youtube("inetjGIjKGU")
  },
  {
    id: "shadow-warrior-2",
    title: "Shadow Warrior 2",
    year: 2016,
    genres: ["AA", "Shooter", "FPS", "Action", "Loot"],
    endingType: "levels",
    rating: 78,
    playersMax: 4,
    hours: 13,
    oneCopy: "none",
    price: 600,
    verdict: "Быстрый мясной FPS с оружием, мечами и лутом. Сюжет вторичен, зато экшен в коопе бодрый.",
    storeUrl: "https://store.steampowered.com/app/324800/Shadow_Warrior_2/",
    imageUrl: steamImage(324800),
    youtubeUrl: youtube("ftciCeHHn5c")
  },
  {
    id: "strange-brigade",
    title: "Strange Brigade",
    year: 2018,
    genres: ["AA", "Shooter", "Third-person", "Action", "Adventure"],
    endingType: "story",
    rating: 74,
    playersMax: 4,
    hours: 8,
    oneCopy: "none",
    price: 579,
    verdict: "Пульповый кооп-шутер про экспедиции, ловушки и толпы врагов. Больше аркада, чем сюжетный дуо-боевик.",
    storeUrl: "https://store.steampowered.com/app/312670/Strange_Brigade/",
    imageUrl: steamImage(312670),
    youtubeUrl: youtube("PpAHlg2oIDQ")
  },
  {
    id: "aliens-fireteam-elite",
    title: "Aliens: Fireteam Elite",
    year: 2021,
    genres: ["AA", "Shooter", "Third-person", "Action", "Horror", "Sci-fi"],
    endingType: "story",
    rating: 67,
    playersMax: 3,
    hours: 8,
    oneCopy: "none",
    price: 599,
    verdict: "Трёхместный кооп по Aliens: коридоры, классы, ксеноморфы. Хорошо как вечерний шутер, слабее как история.",
    storeUrl: "https://store.steampowered.com/app/1549970/Aliens_Fireteam_Elite/",
    imageUrl: steamImage(1549970),
    youtubeUrl: youtube("6c8TrceZWS4")
  },
  {
    id: "back-4-blood",
    title: "Back 4 Blood",
    year: 2021,
    genres: ["AAA", "Shooter", "FPS", "Action", "Horror"],
    endingType: "story",
    rating: 77,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 749,
    verdict: "Наследник Left 4 Dead с карточной системой и кооп-кампанией. Хорошо для стрельбы, но не для плотного сюжета.",
    storeUrl: "https://store.steampowered.com/app/924970/Back_4_Blood/",
    imageUrl: steamImage(924970),
    youtubeUrl: youtube("mnjwzd0WsEQ")
  },
  {
    id: "grounded",
    title: "Grounded",
    year: 2022,
    genres: ["AA", "Survival", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 82,
    playersMax: 4,
    hours: 35,
    oneCopy: "none",
    price: 479,
    verdict: "Выживание с историей и хорошим коопом. Не боевик, зато сильная совместная песочница с понятной целью.",
    storeUrl: "https://store.steampowered.com/app/962130/Grounded/",
    imageUrl: steamImage(962130),
    youtubeUrl: youtube("ebITJ7jQIf4")
  },
  {
    id: "nobody-saves-the-world",
    title: "Nobody Saves the World",
    year: 2022,
    genres: ["Indie", "Action", "RPG", "Isometric"],
    endingType: "story",
    rating: 79,
    playersMax: 2,
    hours: 16,
    oneCopy: "none",
    price: 530,
    verdict: "Изометрический action RPG с онлайн-коопом на двоих. Не AAA, но аккуратная законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/1432050/Nobody_Saves_the_World/",
    imageUrl: steamImage(1432050),
    youtubeUrl: youtube("OZQPvKMUlkc")
  },
  {
    id: "styx-shards-of-darkness",
    title: "Styx: Shards of Darkness",
    year: 2017,
    genres: ["AA", "Stealth", "Action", "Fantasy"],
    endingType: "story",
    rating: 74,
    playersMax: 2,
    hours: 14,
    oneCopy: "none",
    price: 249,
    verdict: "Редкий полноценный кооп-стелс. Хороший кандидат, если хочется не стрелять, а синхронно прокрадываться.",
    storeUrl: "https://store.steampowered.com/app/355790/Styx_Shards_of_Darkness/",
    imageUrl: steamImage(355790),
    youtubeUrl: youtube("apwc3_A9WL8")
  },
  {
    id: "saints-row-4",
    title: "Saints Row IV: Re-Elected",
    year: 2013,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Open World", "Sci-fi"],
    endingType: "story",
    rating: 86,
    playersMax: 2,
    hours: 16,
    oneCopy: "none",
    price: 533,
    verdict: "Безумный открытый мир с кооп-кампанией. Стоит держать в списке, но PC-кооп у серии иногда капризный.",
    storeUrl: "https://store.steampowered.com/app/206420/Saints_Row_IV_ReElected/",
    imageUrl: steamImage(206420),
    youtubeUrl: youtube("kzDK1IYo9nw")
  },
  {
    id: "borderlands-2",
    title: "Borderlands 2",
    year: 2012,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot", "Open World"],
    endingType: "story",
    rating: 91,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 389,
    verdict: "Классика 4-местного лутер-шутера. Огромная кампания, тонны оружия, кооп с самого старта.",
    storeUrl: "https://store.steampowered.com/app/49520/Borderlands_2/",
    imageUrl: steamImage(49520),
    youtubeUrl: youtube("KsNZ6eOJl0c")
  },
  {
    id: "diablo-4",
    title: "Diablo IV",
    year: 2023,
    genres: ["AAA", "Action", "RPG", "Loot", "Fantasy", "Isometric"],
    endingType: "story",
    rating: 86,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 1696,
    verdict: "Большая кампания с актами и нормальной концовкой. Онлайн-кооп на двоих работает без сюрпризов.",
    storeUrl: "https://store.steampowered.com/app/2344520/Diablo_IV/",
    imageUrl: steamImage(2344520),
    youtubeUrl: youtube("wH72EpRepWM")
  },
  {
    id: "vermintide-2",
    title: "Warhammer: Vermintide 2",
    year: 2018,
    genres: ["AA", "Action", "FPS", "Fantasy", "Horror"],
    endingType: "levels",
    rating: 82,
    playersMax: 4,
    hours: 22,
    oneCopy: "none",
    price: 18,
    verdict: "Кооп-резня в фэнтези. Миссии короткие, кампания развёртывается по актам и доходит до финала.",
    storeUrl: "https://store.steampowered.com/app/552500/Warhammer_Vermintide_2/",
    imageUrl: steamImage(552500),
    youtubeUrl: youtube("4VadHTHJ-K8")
  },
  {
    id: "left-4-dead-2",
    title: "Left 4 Dead 2",
    year: 2009,
    genres: ["AAA", "Shooter", "FPS", "Action", "Horror"],
    endingType: "levels",
    rating: 89,
    playersMax: 4,
    hours: 10,
    oneCopy: "none",
    price: 225,
    verdict: "Эталон коопа от Valve. Пять отдельных кампаний, каждая со своим финалом.",
    storeUrl: "https://store.steampowered.com/app/550/Left_4_Dead_2/",
    imageUrl: steamImage(550),
    youtubeUrl: youtube("RvMFOsm4WmU")
  },
  {
    id: "the-forest",
    title: "The Forest",
    year: 2018,
    genres: ["Indie", "Survival", "Horror", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 96,
    playersMax: 8,
    hours: 15,
    oneCopy: "none",
    price: 279,
    verdict: "Выживание-хоррор с настоящим сюжетом и концовкой. Строй базу, исследуй пещеры.",
    storeUrl: "https://store.steampowered.com/app/242760/The_Forest/",
    imageUrl: steamImage(242760),
    youtubeUrl: youtube("62imEBDF2rE")
  },
  {
    id: "sons-of-the-forest",
    title: "Sons of the Forest",
    year: 2024,
    genres: ["Indie", "Survival", "Horror", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 86,
    playersMax: 8,
    hours: 25,
    oneCopy: "none",
    price: 600,
    verdict: "Продолжение The Forest: карта больше, монстры жёстче. Концовка есть, кооп онлайн.",
    storeUrl: "https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/",
    imageUrl: steamImage(1326470),
    youtubeUrl: youtube("lSJSVtkhRck")
  },
  {
    id: "man-of-medan",
    title: "The Dark Pictures: Man of Medan",
    year: 2019,
    genres: ["AA", "Adventure", "Horror"],
    endingType: "story",
    rating: 71,
    playersMax: 5,
    hours: 6,
    oneCopy: "friend-pass",
    price: 545,
    verdict: "Кинематографичный хоррор. Один владеет, второй заходит бесплатно через Friend's Pass.",
    storeUrl: "https://store.steampowered.com/app/1024480/The_Dark_Pictures_Anthology_Man_of_Medan/",
    imageUrl: steamImage(1024480),
    youtubeUrl: youtube("UyBYdhfAxvY")
  },
  {
    id: "magicka-2",
    title: "Magicka 2",
    year: 2015,
    genres: ["AA", "Action", "Adventure", "Fantasy", "Isometric"],
    endingType: "story",
    rating: 74,
    playersMax: 4,
    hours: 6,
    oneCopy: "none",
    price: 369,
    verdict: "Хаотичный кооп с комбинированием элементов. Короткая, но смешная законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/238370/Magicka_2/",
    imageUrl: steamImage(238370),
    youtubeUrl: youtube("o3NQb5zvBKY")
  },
  {
    id: "peak",
    title: "PEAK",
    year: 2025,
    genres: ["Indie", "Adventure", "Action"],
    endingType: "arcade-goal",
    rating: 94,
    playersMax: 4,
    hours: 5,
    oneCopy: "none",
    price: 98,
    verdict: "Кооп-челлендж: добраться до вершины. Не сюжет, но финал есть — каждый забег как короткая история.",
    storeUrl: "https://store.steampowered.com/app/3527290/PEAK/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3527290/31bac6b2eccf09b368f5e95ce510bae2baf3cfcd/header.jpg",
    youtubeUrl: youtube("u_vlCvsf8dg")
  },
  {
    id: "raft",
    title: "Raft",
    year: 2022,
    genres: ["Indie", "Survival", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 92,
    playersMax: 8,
    hours: 30,
    oneCopy: "none",
    price: 430,
    verdict: "Survival на плоту с финальной сюжетной аркой. Кооп до 8 человек онлайн.",
    storeUrl: "https://store.steampowered.com/app/648800/Raft/",
    imageUrl: steamImage(648800),
    youtubeUrl: youtube("iyU4_RR0l0o")
  },
  {
    id: "broforce",
    title: "Broforce",
    year: 2015,
    genres: ["Indie", "Action", "Platformer", "Shooter"],
    endingType: "levels",
    rating: 95,
    playersMax: 4,
    hours: 6,
    oneCopy: "none",
    price: 325,
    verdict: "Короткий мясной кооп-боевик. Кампания заканчивается, заходит на пару вечеров.",
    storeUrl: "https://store.steampowered.com/app/274190/Broforce/",
    imageUrl: steamImage(274190),
    youtubeUrl: youtube("DHmKxqMId_w")
  },
  {
    id: "castle-crashers",
    title: "Castle Crashers",
    year: 2012,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "levels",
    rating: 95,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 229,
    verdict: "Классический beat'em up на четверых. Старый, но один из лучших коопов — прошёл и закрыл.",
    storeUrl: "https://store.steampowered.com/app/204360/Castle_Crashers/",
    imageUrl: steamImage(204360),
    youtubeUrl: youtube("Ek2Eoivlwhs")
  },
  {
    id: "cuphead",
    title: "Cuphead",
    year: 2017,
    genres: ["Indie", "Action", "Platformer", "Shooter"],
    endingType: "levels",
    rating: 93,
    playersMax: 2,
    hours: 12,
    oneCopy: "remote-play",
    price: 279,
    verdict: "Боссы и платформинг в стиле 30-х. Кооп локальный — удалённо через Remote Play.",
    storeUrl: "https://store.steampowered.com/app/268910/Cuphead/",
    imageUrl: steamImage(268910),
    youtubeUrl: youtube("Ygdm1ltqC6c")
  },
  {
    id: "tmnt-shredders-revenge",
    title: "TMNT: Shredder's Revenge",
    year: 2022,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 94,
    playersMax: 6,
    hours: 6,
    oneCopy: "none",
    price: 515,
    verdict: "Бодрый beat'em up по черепашкам. Короткий, проходится за вечер-два.",
    storeUrl: "https://store.steampowered.com/app/1361510/Teenage_Mutant_Ninja_Turtles_Shredders_Revenge/",
    imageUrl: steamImage(1361510),
    youtubeUrl: youtube("RlviJbgWEEE")
  },
  {
    id: "cat-quest-2",
    title: "Cat Quest II",
    year: 2019,
    genres: ["Indie", "Action", "RPG", "Adventure", "Fantasy"],
    endingType: "story",
    rating: 92,
    playersMax: 2,
    hours: 10,
    oneCopy: "remote-play",
    price: 229,
    verdict: "Простая action-RPG про двух котов. Приятная, заканчивается, идеально без напряга.",
    storeUrl: "https://store.steampowered.com/app/914710/Cat_Quest_II/",
    imageUrl: steamImage(914710),
    youtubeUrl: youtube("RPfKh3FMk5s")
  },
  {
    id: "lovers-spacetime",
    title: "Lovers in a Dangerous Spacetime",
    year: 2015,
    genres: ["Indie", "Action", "Adventure", "Sci-fi"],
    endingType: "arcade-goal",
    rating: 90,
    playersMax: 4,
    hours: 5,
    oneCopy: "remote-play",
    price: 229,
    verdict: "Один космический корабль на двоих. Чистый кооп ради коопа — всё на коммуникацию.",
    storeUrl: "https://store.steampowered.com/app/252110/Lovers_in_a_Dangerous_Spacetime/",
    imageUrl: steamImage(252110),
    youtubeUrl: youtube("r9JButWd1zI")
  },
  {
    id: "children-of-morta",
    title: "Children of Morta",
    year: 2019,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "story",
    rating: 87,
    playersMax: 2,
    hours: 15,
    oneCopy: "none",
    price: 329,
    verdict: "Story-driven roguelite про семью защитников. В коопе работает приятно.",
    storeUrl: "https://store.steampowered.com/app/330020/Children_of_Morta/",
    imageUrl: steamImage(330020),
    youtubeUrl: youtube("Xs8wgjSBVI4")
  },
  {
    id: "full-metal-furies",
    title: "Full Metal Furies",
    year: 2018,
    genres: ["Indie", "Action", "RPG", "Adventure"],
    endingType: "story",
    rating: 87,
    playersMax: 4,
    hours: 10,
    oneCopy: "none",
    price: 415,
    verdict: "Недооценённый кооп-экшен от создателей Rogue Legacy. Заточен под командную игру.",
    storeUrl: "https://store.steampowered.com/app/416600/Full_Metal_Furies/",
    imageUrl: steamImage(416600),
    youtubeUrl: youtube("KjUrQmHv_w0")
  },
  {
    id: "escape-academy",
    title: "Escape Academy",
    year: 2022,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 83,
    playersMax: 2,
    hours: 6,
    oneCopy: "none",
    price: 279,
    verdict: "Эскейп-румы в виде игры. Хороший вариант, если хочется думать, а не стрелять.",
    storeUrl: "https://store.steampowered.com/app/1812090/Escape_Academy/",
    imageUrl: steamImage(1812090),
    youtubeUrl: youtube("Gowvcv6c_Bs")
  },
  {
    id: "journey-savage-planet",
    title: "Journey to the Savage Planet",
    year: 2021,
    genres: ["AA", "Adventure", "Action", "Sci-fi"],
    endingType: "story",
    rating: 84,
    playersMax: 2,
    hours: 10,
    oneCopy: "none",
    price: 635,
    verdict: "Кооп-экспедиция на странной планете. Прохождение до финала, без гриндфеста.",
    storeUrl: "https://store.steampowered.com/app/973810/Journey_To_The_Savage_Planet/",
    imageUrl: steamImage(973810),
    youtubeUrl: youtube("G6hMPSNVcJU")
  },
  {
    id: "revenge-savage-planet",
    title: "Revenge of the Savage Planet",
    year: 2025,
    genres: ["AA", "Adventure", "Action", "Sci-fi"],
    endingType: "story",
    rating: 83,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 555,
    verdict: "Прямое продолжение Journey. Кооп онлайн и split-screen — прямо в тему расширенного списка.",
    storeUrl: "https://store.steampowered.com/app/2787320/Revenge_of_the_Savage_Planet/",
    imageUrl: steamImage(2787320),
    youtubeUrl: youtube("0O-T24Mq77A")
  },
  {
    id: "trine-2",
    title: "Trine 2: Complete Story",
    year: 2013,
    genres: ["AA", "Puzzle", "Platformer", "Fantasy"],
    endingType: "story",
    rating: 95,
    playersMax: 3,
    hours: 9,
    oneCopy: "remote-play",
    price: 279,
    verdict: "Раз есть Trine 5, логично взять и Trine 2 — самую любимую часть серии.",
    storeUrl: "https://store.steampowered.com/app/35720/Trine_2_Complete_Story/",
    imageUrl: steamImage(35720),
    youtubeUrl: youtube("yxIaDq9aKPY")
  },
  {
    id: "guacamelee-2",
    title: "Guacamelee! 2",
    year: 2018,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 88,
    playersMax: 4,
    hours: 10,
    oneCopy: "remote-play",
    price: 430,
    verdict: "Метроидвания с боями и платформингом. Локальный кооп до 4 человек.",
    storeUrl: "https://store.steampowered.com/app/534550/Guacamelee_2/",
    imageUrl: steamImage(534550),
    youtubeUrl: youtube("f-b9PJKunww")
  },
  {
    id: "risk-of-rain-2",
    title: "Risk of Rain 2",
    year: 2020,
    genres: ["Indie", "Action", "Shooter", "Sci-fi"],
    endingType: "roguelite",
    rating: 93,
    playersMax: 4,
    hours: 25,
    oneCopy: "none",
    price: 108,
    verdict: "Рогалик-шутер: забег заканчивается финальным боссом, но это не сюжетная кампания.",
    storeUrl: "https://store.steampowered.com/app/632360/Risk_of_Rain_2/",
    imageUrl: steamImage(632360),
    youtubeUrl: youtube("qBRe2NDdN1E")
  },
  {
    id: "overcooked-all-you-can-eat",
    title: "Overcooked! All You Can Eat",
    year: 2021,
    genres: ["AA", "Puzzle", "Action"],
    endingType: "levels",
    rating: 85,
    playersMax: 4,
    hours: 20,
    oneCopy: "remote-play",
    price: 800,
    verdict: "Party-кооп про кухню. Кампании заканчиваются, но это не приключение, а тест нервов.",
    storeUrl: "https://store.steampowered.com/app/1243830/Overcooked_All_You_Can_Eat/",
    imageUrl: steamImage(1243830),
    youtubeUrl: youtube("GS81-vvSo2U")
  },
  {
    id: "terraria",
    title: "Terraria",
    year: 2011,
    genres: ["Indie", "Survival", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 97,
    playersMax: 8,
    hours: 50,
    oneCopy: "none",
    price: 225,
    verdict: "Песочница с финальной прогрессией: от Eye of Cthulhu до Moon Lord. Онлайн до 8.",
    storeUrl: "https://store.steampowered.com/app/105600/Terraria/",
    imageUrl: steamImage(105600),
    youtubeUrl: youtubeSearch("Terraria")
  },
  {
    id: "stardew-valley",
    title: "Stardew Valley",
    year: 2016,
    genres: ["Indie", "RPG", "Adventure"],
    endingType: "survival-goal",
    rating: 95,
    playersMax: 8,
    hours: 50,
    oneCopy: "none",
    price: 229,
    verdict: "Жизненный сим с коопом до 8. Community Center как явная финальная цель.",
    storeUrl: "https://store.steampowered.com/app/413150/Stardew_Valley/",
    imageUrl: steamImage(413150),
    youtubeUrl: youtubeSearch("Stardew Valley")
  },
  {
    id: "magicka",
    title: "Magicka",
    year: 2011,
    genres: ["Indie", "Action", "Adventure", "Fantasy"],
    endingType: "story",
    rating: 86,
    playersMax: 4,
    hours: 8,
    oneCopy: "none",
    price: 249,
    verdict: "Хаотичный кооп-маг до 4. Прародитель Magicka 2.",
    storeUrl: "https://store.steampowered.com/app/42910/Magicka/",
    imageUrl: steamImage(42910),
    youtubeUrl: youtubeSearch("Magicka")
  },
  {
    id: "we-were-here",
    title: "We Were Here",
    year: 2017,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 93,
    playersMax: 2,
    hours: 2,
    oneCopy: "none",
    price: 0,
    verdict: "Бесплатное начало серии. Двое в замке, пазлы через рацию.",
    storeUrl: "https://store.steampowered.com/app/582500/We_Were_Here/",
    imageUrl: steamImage(582500),
    youtubeUrl: youtubeSearch("We Were Here")
  },
  {
    id: "we-were-here-together",
    title: "We Were Here Together",
    year: 2019,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 92,
    playersMax: 2,
    hours: 6,
    oneCopy: "none",
    price: 108,
    verdict: "Лучшая часть серии: 4-6 часов кооп-пазлов с голосом.",
    storeUrl: "https://store.steampowered.com/app/865360/We_Were_Here_Together/",
    imageUrl: steamImage(865360),
    youtubeUrl: youtubeSearch("We Were Here Together")
  },
  {
    id: "streets-of-rage-4",
    title: "Streets of Rage 4",
    year: 2020,
    genres: ["Indie", "Action"],
    endingType: "levels",
    rating: 92,
    playersMax: 4,
    hours: 6,
    oneCopy: "none",
    price: 515,
    verdict: "Возрождение легенды. Beat'em up онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/985890/Streets_of_Rage_4/",
    imageUrl: steamImage(985890),
    youtubeUrl: youtubeSearch("Streets of Rage 4")
  },
  {
    id: "enter-the-gungeon",
    title: "Enter the Gungeon",
    year: 2016,
    genres: ["Indie", "Action", "Shooter", "Isometric"],
    endingType: "roguelite",
    rating: 92,
    playersMax: 2,
    hours: 25,
    oneCopy: "remote-play",
    price: 325,
    verdict: "Bullet-hell roguelike. Двоих через Remote Play, есть финал — The Past.",
    storeUrl: "https://store.steampowered.com/app/311690/Enter_the_Gungeon/",
    imageUrl: steamImage(311690),
    youtubeUrl: youtubeSearch("Enter the Gungeon")
  },
  {
    id: "spelunky-2",
    title: "Spelunky 2",
    year: 2020,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "roguelite",
    rating: 88,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 279,
    verdict: "Онлайн-кооп roguelike. Финальные маршруты до 7-1 / Cosmic Ocean.",
    storeUrl: "https://store.steampowered.com/app/418530/Spelunky_2/",
    imageUrl: steamImage(418530),
    youtubeUrl: youtubeSearch("Spelunky 2")
  },
  {
    id: "spelunky",
    title: "Spelunky",
    year: 2013,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "roguelite",
    rating: 88,
    playersMax: 4,
    hours: 10,
    oneCopy: "remote-play",
    price: 229,
    verdict: "Оригинал. Локальный кооп + Remote Play, финальная зона Olmec.",
    storeUrl: "https://store.steampowered.com/app/239350/Spelunky/",
    imageUrl: steamImage(239350),
    youtubeUrl: youtubeSearch("Spelunky")
  },
  {
    id: "battleblock-theater",
    title: "BattleBlock Theater",
    year: 2014,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 93,
    playersMax: 2,
    hours: 8,
    oneCopy: "none",
    price: 229,
    verdict: "От авторов Castle Crashers. Онлайн-кооп, законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/238460/BattleBlock_Theater/",
    imageUrl: steamImage(238460),
    youtubeUrl: youtubeSearch("BattleBlock Theater")
  },
  {
    id: "lego-skywalker-saga",
    title: "LEGO Star Wars: The Skywalker Saga",
    year: 2022,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "story",
    rating: 88,
    playersMax: 2,
    hours: 50,
    oneCopy: "remote-play",
    price: 649,
    verdict: "Огромная LEGO-кампания: все 9 эпизодов. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/920210/LEGO_Star_Wars_The_Skywalker_Saga/",
    imageUrl: steamImage(920210),
    youtubeUrl: youtubeSearch("LEGO Star Wars Skywalker Saga")
  },
  {
    id: "lego-city-undercover",
    title: "LEGO City Undercover",
    year: 2017,
    genres: ["AAA", "Action", "Adventure", "Open World"],
    endingType: "story",
    rating: 85,
    playersMax: 2,
    hours: 25,
    oneCopy: "remote-play",
    price: 799,
    verdict: "Цельная LEGO-игра с открытым городом.",
    storeUrl: "https://store.steampowered.com/app/578330/LEGO_City_Undercover/",
    imageUrl: steamImage(578330),
    youtubeUrl: youtubeSearch("LEGO City Undercover")
  },
  {
    id: "lego-marvel-superheroes",
    title: "LEGO Marvel Super Heroes",
    year: 2013,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "story",
    rating: 89,
    playersMax: 2,
    hours: 20,
    oneCopy: "remote-play",
    price: 279,
    verdict: "Любимая LEGO-кампания по Marvel.",
    storeUrl: "https://store.steampowered.com/app/249130/LEGO_Marvel_Super_Heroes/",
    imageUrl: steamImage(249130),
    youtubeUrl: youtubeSearch("LEGO Marvel Super Heroes")
  },
  {
    id: "a-hat-in-time",
    title: "A Hat in Time",
    year: 2017,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 92,
    playersMax: 2,
    hours: 12,
    oneCopy: "remote-play",
    price: 600,
    verdict: "3D-платформер с коопом. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/253230/A_Hat_in_Time/",
    imageUrl: steamImage(253230),
    youtubeUrl: youtubeSearch("A Hat in Time")
  },
  {
    id: "rayman-legends",
    title: "Rayman Legends",
    year: 2013,
    genres: ["AAA", "Action", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 95,
    playersMax: 4,
    hours: 15,
    oneCopy: "remote-play",
    price: 299,
    verdict: "Один из лучших кооп-платформеров. До 4 локально.",
    storeUrl: "https://store.steampowered.com/app/242550/Rayman_Legends/",
    imageUrl: steamImage(242550),
    youtubeUrl: youtubeSearch("Rayman Legends")
  },
  {
    id: "rayman-origins",
    title: "Rayman Origins",
    year: 2012,
    genres: ["AAA", "Action", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 92,
    playersMax: 4,
    hours: 12,
    oneCopy: "remote-play",
    price: 150,
    verdict: "Предшественник Legends. Локальный кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/207490/Rayman_Origins/",
    imageUrl: steamImage(207490),
    youtubeUrl: youtubeSearch("Rayman Origins")
  },
  {
    id: "sackboy-big-adventure",
    title: "Sackboy: A Big Adventure",
    year: 2022,
    genres: ["AAA", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 81,
    playersMax: 4,
    hours: 15,
    oneCopy: "none",
    price: 1699,
    verdict: "LittleBigPlanet-наследник. Локальный + онлайн кооп. Дорогой без скидки.",
    storeUrl: "https://store.steampowered.com/app/1599660/Sackboy_A_Big_Adventure/",
    imageUrl: steamImage(1599660),
    youtubeUrl: youtubeSearch("Sackboy A Big Adventure")
  },
  {
    id: "orcs-must-die-2",
    title: "Orcs Must Die! 2",
    year: 2012,
    genres: ["AA", "Action", "Tactics", "Fantasy"],
    endingType: "levels",
    rating: 92,
    playersMax: 2,
    hours: 15,
    oneCopy: "none",
    price: 229,
    verdict: "Классика action tower defense. Онлайн-кампания на двоих.",
    storeUrl: "https://store.steampowered.com/app/201790/Orcs_Must_Die_2/",
    imageUrl: steamImage(201790),
    youtubeUrl: youtubeSearch("Orcs Must Die 2")
  },
  {
    id: "dungeon-defenders",
    title: "Dungeon Defenders",
    year: 2011,
    genres: ["AA", "Action", "Tactics", "RPG", "Fantasy"],
    endingType: "levels",
    rating: 80,
    playersMax: 4,
    hours: 25,
    oneCopy: "none",
    price: 325,
    verdict: "Action tower defense с RPG-прогрессией. До 4 онлайн.",
    storeUrl: "https://store.steampowered.com/app/65800/Dungeon_Defenders/",
    imageUrl: steamImage(65800),
    youtubeUrl: youtubeSearch("Dungeon Defenders")
  },
  {
    id: "sanctum-2",
    title: "Sanctum 2",
    year: 2013,
    genres: ["AA", "Shooter", "FPS", "Tactics", "Sci-fi"],
    endingType: "levels",
    rating: 79,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 409,
    verdict: "FPS-tower defense. Онлайн-кампания до 4.",
    storeUrl: "https://store.steampowered.com/app/210770/Sanctum_2/",
    imageUrl: steamImage(210770),
    youtubeUrl: youtubeSearch("Sanctum 2")
  },
  {
    id: "world-war-z",
    title: "World War Z: Aftermath",
    year: 2021,
    genres: ["AA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 80,
    playersMax: 4,
    hours: 15,
    oneCopy: "none",
    price: 187,
    verdict: "Эпизодная кооп-кампания против зомби-волн. До 4 онлайн.",
    storeUrl: "https://store.steampowered.com/app/699130/World_War_Z_Aftermath/",
    imageUrl: steamImage(699130),
    youtubeUrl: youtubeSearch("World War Z Aftermath")
  },
  {
    id: "zombie-army-trilogy",
    title: "Zombie Army Trilogy",
    year: 2015,
    genres: ["AA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 80,
    playersMax: 4,
    hours: 15,
    oneCopy: "none",
    price: 529,
    verdict: "Sniper Elite в зомби-сеттинге. Кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/301640/Zombie_Army_Trilogy/",
    imageUrl: steamImage(301640),
    youtubeUrl: youtubeSearch("Zombie Army Trilogy")
  },
  {
    id: "serious-sam-3",
    title: "Serious Sam 3: BFE",
    year: 2011,
    genres: ["AA", "Shooter", "FPS", "Action", "Sci-fi"],
    endingType: "story",
    rating: 85,
    playersMax: 4,
    hours: 15,
    oneCopy: "none",
    price: 600,
    verdict: "Олдскульный FPS с кооп-кампанией до 4.",
    storeUrl: "https://store.steampowered.com/app/41070/Serious_Sam_3_BFE/",
    imageUrl: steamImage(41070),
    youtubeUrl: youtubeSearch("Serious Sam 3 BFE")
  },
  {
    id: "serious-sam-4",
    title: "Serious Sam 4",
    year: 2020,
    genres: ["AA", "Shooter", "FPS", "Action", "Sci-fi"],
    endingType: "story",
    rating: 76,
    playersMax: 4,
    hours: 20,
    oneCopy: "none",
    price: 740,
    verdict: "Современный Serious Sam с кооп-кампанией.",
    storeUrl: "https://store.steampowered.com/app/257420/Serious_Sam_4/",
    imageUrl: steamImage(257420),
    youtubeUrl: youtubeSearch("Serious Sam 4")
  },
  {
    id: "alien-swarm-reactive-drop",
    title: "Alien Swarm: Reactive Drop",
    year: 2017,
    genres: ["Indie", "Shooter", "Action", "Sci-fi", "Horror", "Isometric"],
    endingType: "levels",
    rating: 92,
    playersMax: 4,
    hours: 10,
    oneCopy: "none",
    price: 0,
    verdict: "Бесплатная top-down кооп-миссионка. Очевидное добавление.",
    storeUrl: "https://store.steampowered.com/app/563560/Alien_Swarm_Reactive_Drop/",
    imageUrl: steamImage(563560),
    youtubeUrl: youtubeSearch("Alien Swarm Reactive Drop")
  },
  {
    id: "powerwash-simulator",
    title: "PowerWash Simulator",
    year: 2022,
    genres: ["Indie", "Adventure", "Puzzle"],
    endingType: "levels",
    rating: 95,
    playersMax: 6,
    hours: 25,
    oneCopy: "none",
    price: 500,
    verdict: "Симулятор мойки. Career-режим с финитными работами.",
    storeUrl: "https://store.steampowered.com/app/1290000/PowerWash_Simulator/",
    imageUrl: steamImage(1290000),
    youtubeUrl: youtubeSearch("PowerWash Simulator")
  },
  {
    id: "teardown",
    title: "Teardown",
    year: 2022,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "story",
    rating: 95,
    playersMax: 12,
    hours: 15,
    oneCopy: "none",
    price: 649,
    verdict: "Voxel-разрушение. Кооп-кампания добавлена в 2026.",
    storeUrl: "https://store.steampowered.com/app/1167630/Teardown/",
    imageUrl: steamImage(1167630),
    youtubeUrl: youtubeSearch("Teardown")
  },
  {
    id: "human-fall-flat",
    title: "Human Fall Flat",
    year: 2016,
    genres: ["Indie", "Puzzle", "Adventure", "Platformer"],
    endingType: "levels",
    rating: 89,
    playersMax: 8,
    hours: 8,
    oneCopy: "none",
    price: 279,
    verdict: "Physics-кооп до 8. Уровни проходятся.",
    storeUrl: "https://store.steampowered.com/app/477160/Human_Fall_Flat/",
    imageUrl: steamImage(477160),
    youtubeUrl: youtubeSearch("Human Fall Flat")
  },
  {
    id: "for-the-king",
    title: "For The King",
    year: 2018,
    genres: ["Indie", "RPG", "Tactics", "Adventure", "Fantasy"],
    endingType: "roguelite",
    rating: 87,
    playersMax: 3,
    hours: 30,
    oneCopy: "none",
    price: 279,
    verdict: "Настольная roguelite-RPG. Онлайн-кампания.",
    storeUrl: "https://store.steampowered.com/app/527230/For_The_King/",
    imageUrl: steamImage(527230),
    youtubeUrl: youtubeSearch("For The King")
  },
  {
    id: "streets-of-rogue",
    title: "Streets of Rogue",
    year: 2019,
    genres: ["Indie", "Action", "RPG", "Adventure", "Isometric"],
    endingType: "roguelite",
    rating: 90,
    playersMax: 4,
    hours: 20,
    oneCopy: "none",
    price: 415,
    verdict: "Roguelite immersive sim. Пройти город онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/512900/Streets_of_Rogue/",
    imageUrl: steamImage(512900),
    youtubeUrl: youtubeSearch("Streets of Rogue")
  },
  {
    id: "nuclear-throne",
    title: "Nuclear Throne",
    year: 2015,
    genres: ["Indie", "Action", "Shooter"],
    endingType: "roguelite",
    rating: 95,
    playersMax: 2,
    hours: 10,
    oneCopy: "remote-play",
    price: 199,
    verdict: "Twin-stick roguelike. Локальный кооп + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/242680/Nuclear_Throne/",
    imageUrl: steamImage(242680),
    youtubeUrl: youtubeSearch("Nuclear Throne")
  },
  {
    id: "binding-of-isaac-rebirth",
    title: "The Binding of Isaac: Rebirth",
    year: 2014,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "roguelite",
    rating: 95,
    playersMax: 4,
    hours: 50,
    oneCopy: "remote-play",
    price: 229,
    verdict: "Roguelite в подвалах с боссами-эндингами. Локальный кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/",
    imageUrl: steamImage(250900),
    youtubeUrl: youtubeSearch("Binding of Isaac Rebirth")
  },
  {
    id: "keywe",
    title: "KeyWe",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "levels",
    rating: 86,
    playersMax: 2,
    hours: 6,
    oneCopy: "none",
    price: 329,
    verdict: "Милая кооп-почта про птичек-киви. Онлайн на двоих.",
    storeUrl: "https://store.steampowered.com/app/1242980/KeyWe/",
    imageUrl: steamImage(1242980),
    youtubeUrl: youtubeSearch("KeyWe")
  },
  {
    id: "moving-out",
    title: "Moving Out",
    year: 2020,
    genres: ["Indie", "Puzzle", "Action"],
    endingType: "levels",
    rating: 89,
    playersMax: 4,
    hours: 10,
    oneCopy: "remote-play",
    price: 419,
    verdict: "Кооп-грузчики в духе Overcooked. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/996770/Moving_Out/",
    imageUrl: steamImage(996770),
    youtubeUrl: youtubeSearch("Moving Out")
  },
  {
    id: "roboquest",
    title: "Roboquest",
    year: 2023,
    genres: ["Indie", "Action", "Shooter", "FPS", "Sci-fi"],
    endingType: "roguelite",
    rating: 95,
    playersMax: 2,
    hours: 20,
    oneCopy: "none",
    price: 390,
    verdict: "FPS-roguelike с финалом забега. Онлайн на двоих.",
    storeUrl: "https://store.steampowered.com/app/692890/Roboquest/",
    imageUrl: steamImage(692890),
    youtubeUrl: youtubeSearch("Roboquest")
  },
  {
    id: "gunfire-reborn",
    title: "Gunfire Reborn",
    year: 2021,
    genres: ["Indie", "Action", "Shooter", "FPS"],
    endingType: "roguelite",
    rating: 95,
    playersMax: 4,
    hours: 25,
    oneCopy: "none",
    price: 399,
    verdict: "FPS-roguelite до 4 с финальным боссом забега.",
    storeUrl: "https://store.steampowered.com/app/1217060/Gunfire_Reborn/",
    imageUrl: steamImage(1217060),
    youtubeUrl: youtubeSearch("Gunfire Reborn")
  },
  {
    id: "ravenswatch",
    title: "Ravenswatch",
    year: 2024,
    genres: ["AA", "Action", "RPG", "Fantasy", "Isometric"],
    endingType: "roguelite",
    rating: 85,
    playersMax: 4,
    hours: 20,
    oneCopy: "none",
    price: 460,
    verdict: "Roguelite от Curse of the Dead Gods. Онлайн-кооп.",
    storeUrl: "https://store.steampowered.com/app/2071280/Ravenswatch/",
    imageUrl: steamImage(2071280),
    youtubeUrl: youtubeSearch("Ravenswatch")
  },
  {
    id: "wizard-of-legend",
    title: "Wizard of Legend",
    year: 2018,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "roguelite",
    rating: 88,
    playersMax: 2,
    hours: 12,
    oneCopy: "remote-play",
    price: 239,
    verdict: "Заклинательский roguelite. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/445980/Wizard_of_Legend/",
    imageUrl: steamImage(445980),
    youtubeUrl: youtubeSearch("Wizard of Legend")
  },
  {
    id: "death-road-to-canada",
    title: "Death Road to Canada",
    year: 2016,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "roguelite",
    rating: 89,
    playersMax: 4,
    hours: 8,
    oneCopy: "remote-play",
    price: 229,
    verdict: "Roguelite roadtrip. Доехать до Канады, локально до 4.",
    storeUrl: "https://store.steampowered.com/app/252610/Death_Road_to_Canada/",
    imageUrl: steamImage(252610),
    youtubeUrl: youtubeSearch("Death Road to Canada")
  },
  {
    id: "kane-lynch-2",
    title: "Kane & Lynch 2: Dog Days",
    year: 2010,
    genres: ["AAA", "Shooter", "Third-person", "Action"],
    endingType: "story",
    rating: 65,
    playersMax: 2,
    hours: 6,
    oneCopy: "none",
    price: 169,
    verdict: "Грязный криминальный кооп-боевик. Прямой родственник Army of Two.",
    storeUrl: "https://store.steampowered.com/app/28000/Kane__Lynch_2_Dog_Days/",
    imageUrl: steamImage(28000),
    youtubeUrl: youtubeSearch("Kane Lynch 2 Dog Days")
  },
  {
    id: "towerfall-ascension",
    title: "TowerFall Ascension",
    year: 2014,
    genres: ["Indie", "Action", "Platformer"],
    endingType: "arcade-goal",
    rating: 94,
    playersMax: 4,
    hours: 8,
    oneCopy: "remote-play",
    price: 289,
    verdict: "PvP + кооп Quest Mode и Dark World. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/251470/TowerFall_Ascension/",
    imageUrl: steamImage(251470),
    youtubeUrl: youtubeSearch("TowerFall Ascension")
  },
  {
    id: "capcom-beat-em-up-bundle",
    title: "Capcom Beat 'Em Up Bundle",
    year: 2018,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "levels",
    rating: 84,
    playersMax: 4,
    hours: 8,
    oneCopy: "none",
    price: 649,
    verdict: "Сборник 7 классических beat'em up'ов Capcom. Онлайн.",
    storeUrl: "https://store.steampowered.com/app/885150/Capcom_Beat_Em_Up_Bundle/",
    imageUrl: steamImage(885150),
    youtubeUrl: youtubeSearch("Capcom Beat Em Up Bundle")
  },
  {
    id: "metal-slug-3",
    title: "METAL SLUG 3",
    year: 2014,
    genres: ["AAA", "Action", "Shooter", "Platformer"],
    endingType: "levels",
    rating: 87,
    playersMax: 2,
    hours: 4,
    oneCopy: "remote-play",
    price: 149,
    verdict: "Самая известная Metal Slug. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/250180/METAL_SLUG_3/",
    imageUrl: steamImage(250180),
    youtubeUrl: youtubeSearch("METAL SLUG 3")
  },
  {
    id: "monaco",
    title: "Monaco: What's Yours Is Mine",
    year: 2013,
    genres: ["Indie", "Action", "Adventure", "Stealth", "Isometric"],
    endingType: "levels",
    rating: 85,
    playersMax: 4,
    hours: 10,
    oneCopy: "none",
    price: 229,
    verdict: "Кооп-ограбления top-down. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/113020/Monaco_Whats_Yours_Is_Mine/",
    imageUrl: steamImage(113020),
    youtubeUrl: youtubeSearch("Monaco Whats Yours Is Mine")
  },
  {
    id: "the-cave",
    title: "The Cave",
    year: 2013,
    genres: ["AA", "Puzzle", "Adventure", "Platformer"],
    endingType: "story",
    rating: 75,
    playersMax: 3,
    hours: 6,
    oneCopy: "remote-play",
    price: 229,
    verdict: "Приключенческая головоломка от Рона Гилберта. Локально до 3.",
    storeUrl: "https://store.steampowered.com/app/221810/The_Cave/",
    imageUrl: steamImage(221810),
    youtubeUrl: youtubeSearch("The Cave")
  },
  {
    id: "20xx",
    title: "20XX",
    year: 2017,
    genres: ["Indie", "Action", "Platformer"],
    endingType: "roguelite",
    rating: 87,
    playersMax: 2,
    hours: 10,
    oneCopy: "none",
    price: 229,
    verdict: "Mega Man-like roguelite. Онлайн на двоих.",
    storeUrl: "https://store.steampowered.com/app/322110/20XX/",
    imageUrl: steamImage(322110),
    youtubeUrl: youtubeSearch("20XX")
  },
  {
    id: "vagante",
    title: "Vagante",
    year: 2018,
    genres: ["Indie", "Action", "RPG", "Platformer", "Fantasy"],
    endingType: "roguelite",
    rating: 86,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 229,
    verdict: "Roguelike-платформер. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/323220/Vagante/",
    imageUrl: steamImage(323220),
    youtubeUrl: youtubeSearch("Vagante")
  },
  {
    id: "barony",
    title: "Barony",
    year: 2015,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "roguelite",
    rating: 82,
    playersMax: 4,
    hours: 20,
    oneCopy: "none",
    price: 415,
    verdict: "First-person dungeon roguelike. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/371970/Barony/",
    imageUrl: steamImage(371970),
    youtubeUrl: youtubeSearch("Barony")
  },
  {
    id: "across-the-obelisk",
    title: "Across the Obelisk",
    year: 2021,
    genres: ["Indie", "RPG", "Tactics", "Adventure", "Fantasy"],
    endingType: "roguelite",
    rating: 90,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 489,
    verdict: "Карточный roguelite в актах. Онлайн-кампания.",
    storeUrl: "https://store.steampowered.com/app/1385380/Across_the_Obelisk/",
    imageUrl: steamImage(1385380),
    youtubeUrl: youtubeSearch("Across the Obelisk")
  },
  {
    id: "escape-simulator",
    title: "Escape Simulator",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 95,
    playersMax: 6,
    hours: 10,
    oneCopy: "none",
    price: 399,
    verdict: "Кооп escape room с комнатами и DLC-кампаниями. Онлайн до 6.",
    storeUrl: "https://store.steampowered.com/app/1435790/Escape_Simulator/",
    imageUrl: steamImage(1435790),
    youtubeUrl: youtubeSearch("Escape Simulator")
  },
  {
    id: "keep-talking-nobody-explodes",
    title: "Keep Talking and Nobody Explodes",
    year: 2015,
    genres: ["Indie", "Puzzle"],
    endingType: "arcade-goal",
    rating: 95,
    playersMax: 2,
    hours: 6,
    oneCopy: "friend-pass",
    price: 325,
    verdict: "Один обезвреживает бомбу, второй читает мануал. Одной копии достаточно.",
    storeUrl: "https://store.steampowered.com/app/341800/Keep_Talking_and_Nobody_Explodes/",
    imageUrl: steamImage(341800),
    youtubeUrl: youtubeSearch("Keep Talking and Nobody Explodes")
  },
  {
    id: "remnant-1",
    title: "Remnant: From the Ashes",
    year: 2019,
    genres: ["AA", "Shooter", "Third-person", "Action", "RPG", "Soulslike"],
    endingType: "story",
    rating: 80,
    playersMax: 3,
    hours: 25,
    oneCopy: "none",
    price: 479,
    verdict: "Soulslike с пушками. Предшественник Remnant II.",
    storeUrl: "https://store.steampowered.com/app/617290/Remnant_From_the_Ashes/",
    imageUrl: steamImage(617290),
    youtubeUrl: youtubeSearch("Remnant From the Ashes")
  },
  {
    id: "dead-island-de",
    title: "Dead Island Definitive Edition",
    year: 2016,
    genres: ["AAA", "Action", "FPS", "RPG", "Open World", "Horror"],
    endingType: "story",
    rating: 77,
    playersMax: 4,
    hours: 20,
    oneCopy: "none",
    price: 533,
    verdict: "Зомби-боевик с кооп-кампанией до 4.",
    storeUrl: "https://store.steampowered.com/app/383150/Dead_Island_Definitive_Edition/",
    imageUrl: steamImage(383150),
    youtubeUrl: youtubeSearch("Dead Island Definitive Edition")
  },
  {
    id: "portal-knights",
    title: "Portal Knights",
    year: 2017,
    genres: ["AA", "Action", "RPG", "Adventure", "Fantasy"],
    endingType: "survival-goal",
    rating: 80,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 279,
    verdict: "Voxel-Minecraft с боссами и прогрессией. Кооп локально/онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/374040/Portal_Knights/",
    imageUrl: steamImage(374040),
    youtubeUrl: youtubeSearch("Portal Knights")
  },
  {
    id: "chained-together",
    title: "Chained Together",
    year: 2024,
    genres: ["Indie", "Adventure", "Action"],
    endingType: "arcade-goal",
    rating: 87,
    playersMax: 4,
    hours: 5,
    oneCopy: "none",
    price: 124,
    verdict: "Кооп-восхождение скованными цепью. Добраться до вершины.",
    storeUrl: "https://store.steampowered.com/app/2567870/Chained_Together/",
    imageUrl: steamImage(2567870),
    youtubeUrl: youtubeSearch("Chained Together")
  },
  {
    id: "pico-park",
    title: "PICO PARK",
    year: 2021,
    genres: ["Indie", "Puzzle", "Platformer"],
    endingType: "levels",
    rating: 91,
    playersMax: 8,
    hours: 3,
    oneCopy: "none",
    price: 99,
    verdict: "Простые кооп-уровни до 8 человек. Минималистично и хорошо.",
    storeUrl: "https://store.steampowered.com/app/1509960/PICO_PARK/",
    imageUrl: steamImage(1509960),
    youtubeUrl: youtubeSearch("PICO PARK")
  },
  {
    id: "road-redemption",
    title: "Road Redemption",
    year: 2017,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 80,
    playersMax: 4,
    hours: 8,
    oneCopy: "remote-play",
    price: 279,
    verdict: "Road Rash-наследник. Локальный split-screen + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/300380/Road_Redemption/",
    imageUrl: steamImage(300380),
    youtubeUrl: youtubeSearch("Road Redemption")
  },
  {
    id: "edf-4-1",
    title: "Earth Defense Force 4.1",
    year: 2016,
    genres: ["AA", "Shooter", "Action", "Sci-fi"],
    endingType: "levels",
    rating: 88,
    playersMax: 4,
    hours: 50,
    oneCopy: "none",
    price: 279,
    verdict: "Орды гигантских жуков. Онлайн-миссии до 4.",
    storeUrl: "https://store.steampowered.com/app/410320/EARTH_DEFENSE_FORCE_41_The_Shadow_of_New_Despair/",
    imageUrl: steamImage(410320),
    youtubeUrl: youtubeSearch("Earth Defense Force 4.1")
  },
  {
    id: "assault-android-cactus",
    title: "Assault Android Cactus+",
    year: 2015,
    genres: ["Indie", "Action", "Shooter"],
    endingType: "levels",
    rating: 88,
    playersMax: 4,
    hours: 6,
    oneCopy: "remote-play",
    price: 279,
    verdict: "Twin-stick кампания. Локально до 4.",
    storeUrl: "https://store.steampowered.com/app/250110/Assault_Android_Cactus/",
    imageUrl: steamImage(250110),
    youtubeUrl: youtubeSearch("Assault Android Cactus")
  },
  {
    id: "fightn-rage",
    title: "Fight'N Rage",
    year: 2017,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 95,
    playersMax: 3,
    hours: 5,
    oneCopy: "remote-play",
    price: 415,
    verdict: "Современный beat'em up в духе 90-х. Локально до 3.",
    storeUrl: "https://store.steampowered.com/app/674520/FightN_Rage/",
    imageUrl: steamImage(674520),
    youtubeUrl: youtubeSearch("FightN Rage")
  },
  {
    id: "door-kickers-action-squad",
    title: "Door Kickers: Action Squad",
    year: 2018,
    genres: ["Indie", "Action", "Shooter", "Tactics"],
    endingType: "levels",
    rating: 92,
    playersMax: 4,
    hours: 15,
    oneCopy: "none",
    price: 310,
    verdict: "Тактический пиксельный shooter. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/686200/Door_Kickers_Action_Squad/",
    imageUrl: steamImage(686200),
    youtubeUrl: youtubeSearch("Door Kickers Action Squad")
  },
  {
    id: "satisfactory",
    title: "Satisfactory",
    year: 2024,
    genres: ["AA", "Survival", "Open World"],
    endingType: "survival-goal",
    rating: 97,
    playersMax: 4,
    hours: 80,
    oneCopy: "none",
    price: 740,
    verdict: "Строим автоматизированный завод на чужой планете ради сборки космического элеватора.",
    storeUrl: "https://store.steampowered.com/app/526870/",
    imageUrl: steamImage(526870),
    youtubeUrl: youtube("Jbs2haRVmC0")
  },
  {
    id: "just-shapes-and-beats",
    title: "Just Shapes & Beats",
    year: 2018,
    genres: ["Indie", "Action"],
    endingType: "levels",
    rating: 98,
    playersMax: 4,
    hours: 4,
    oneCopy: "none",
    price: 399,
    verdict: "Ритмический bullet hell на четверых: уворачиваемся от геометрии под электронную музыку.",
    storeUrl: "https://store.steampowered.com/app/531510/",
    imageUrl: steamImage(531510),
    youtubeUrl: youtube("Fll1AMxCYlo")
  },
  {
    id: "madness-project-nexus",
    title: "MADNESS: Project Nexus",
    year: 2021,
    genres: ["Indie", "Action", "Shooter"],
    endingType: "levels",
    rating: 97,
    playersMax: 2,
    hours: 12,
    oneCopy: "remote-play",
    price: 329,
    verdict: "Сюрреалистичный битэмап про чёрно-белых психопатов с автоматами и битами из вселенной Madness.",
    storeUrl: "https://store.steampowered.com/app/488860/",
    imageUrl: steamImage(488860),
    youtubeUrl: youtubeSearch("Madness Project Nexus co-op gameplay")
  },
  {
    id: "chicory-colorful-tale",
    title: "Chicory: A Colorful Tale",
    year: 2021,
    genres: ["Indie", "Adventure", "Puzzle"],
    endingType: "story",
    rating: 98,
    playersMax: 2,
    hours: 12,
    oneCopy: "remote-play",
    price: 415,
    verdict: "Уютное приключение про собаку с кистью: раскрашиваем мир, решаем пазлы и копаемся в чужих травмах.",
    storeUrl: "https://store.steampowered.com/app/1123450/",
    imageUrl: steamImage(1123450),
    youtubeUrl: youtubeSearch("Chicory Colorful Tale co-op gameplay")
  },
  {
    id: "rabbit-and-steel",
    title: "Rabbit and Steel",
    year: 2024,
    genres: ["Indie", "Action", "RPG"],
    endingType: "roguelite",
    rating: 97,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 325,
    verdict: "MMO-рейд в формате roguelite: четверо кроликов уворачиваются от паттернов босса с мечами и магией.",
    storeUrl: "https://store.steampowered.com/app/2132850/",
    imageUrl: steamImage(2132850),
    youtubeUrl: youtubeSearch("Rabbit and Steel co-op gameplay")
  },
  {
    id: "door-kickers-2",
    title: "Door Kickers 2: Task Force North",
    year: 2025,
    genres: ["Indie", "Tactics", "Isometric"],
    endingType: "levels",
    rating: 96,
    playersMax: 4,
    hours: 25,
    oneCopy: "none",
    price: 309,
    verdict: "Тактический штурм комнат с командой спецназа: вид сверху, пауза по нажатию, миссии в шаг от провала.",
    storeUrl: "https://store.steampowered.com/app/1239080/",
    imageUrl: steamImage(1239080),
    youtubeUrl: youtubeSearch("Door Kickers 2 co-op gameplay")
  },
  {
    id: "heavenly-bodies",
    title: "Heavenly Bodies",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "levels",
    rating: 95,
    playersMax: 2,
    hours: 5,
    oneCopy: "remote-play",
    price: 415,
    verdict: "Физика невесомости и космонавты-неумехи: один палец на руке, один тумблер за раз, локальные ржаки.",
    storeUrl: "https://store.steampowered.com/app/1138850/",
    imageUrl: steamImage(1138850),
    youtubeUrl: youtubeSearch("Heavenly Bodies co-op gameplay")
  },
  {
    id: "bang-on-balls-chronicles",
    title: "Bang-On Balls: Chronicles",
    year: 2023,
    genres: ["Indie", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 96,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 515,
    verdict: "Шарики путешествуют по историческим эпохам, бьют врагов и врываются друг в друга — 3D-платформер на четверых.",
    storeUrl: "https://store.steampowered.com/app/1227650/",
    imageUrl: steamImage(1227650),
    youtubeUrl: youtubeSearch("Bang-On Balls Chronicles co-op gameplay")
  },
  {
    id: "echo-point-nova",
    title: "Echo Point Nova",
    year: 2024,
    genres: ["Indie", "Shooter", "FPS"],
    endingType: "story",
    rating: 97,
    playersMax: 4,
    hours: 15,
    oneCopy: "none",
    price: 515,
    verdict: "Открытый мир, паркур-шутер от автора Severed Steel: парим, рикошетим пули, врываемся вчетвером.",
    storeUrl: "https://store.steampowered.com/app/1836730/",
    imageUrl: steamImage(1836730),
    youtubeUrl: youtubeSearch("Echo Point Nova co-op gameplay")
  },
  {
    id: "stick-it-to-the-stickman",
    title: "Stick It to the Stickman",
    year: 2025,
    genres: ["Indie", "Action"],
    endingType: "roguelite",
    rating: 97,
    playersMax: 4,
    hours: 10,
    oneCopy: "remote-play",
    price: 163,
    verdict: "Физический мордобой палочных человечков с прокачкой в roguelite-структуре — от Free Lives.",
    storeUrl: "https://store.steampowered.com/app/2085540/",
    imageUrl: steamImage(2085540),
    youtubeUrl: youtubeSearch("Stick It to the Stickman co-op gameplay")
  },
  {
    id: "age-of-empires-2-de",
    title: "Age of Empires II: Definitive Edition",
    year: 2019,
    genres: ["AAA", "Tactics"],
    endingType: "levels",
    rating: 95,
    playersMax: 4,
    hours: 80,
    oneCopy: "none",
    price: 880,
    verdict: "Классическая RTS в HD: кооперативные исторические кампании от Чингисхана до Жанны д'Арк.",
    storeUrl: "https://store.steampowered.com/app/813780/",
    imageUrl: steamImage(813780),
    youtubeUrl: youtubeSearch("Age of Empires 2 Definitive Edition co-op campaign")
  },
  {
    id: "mindustry",
    title: "Mindustry",
    year: 2019,
    genres: ["Indie", "Tactics"],
    endingType: "levels",
    rating: 96,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 169,
    verdict: "Гибрид tower defense и factory-game: автоматизируем добычу, отстраиваемся и отбиваемся вместе.",
    storeUrl: "https://store.steampowered.com/app/1127400/",
    imageUrl: steamImage(1127400),
    youtubeUrl: youtubeSearch("Mindustry co-op gameplay")
  },
  {
    id: "crypt-of-the-necrodancer",
    title: "Crypt of the NecroDancer",
    year: 2015,
    genres: ["Indie", "Action"],
    endingType: "roguelite",
    rating: 96,
    playersMax: 2,
    hours: 15,
    oneCopy: "remote-play",
    price: 325,
    verdict: "Ритм-рогалик: ходим по подземелью в такт бэнгеру, бьём скелетов на удар по такту.",
    storeUrl: "https://store.steampowered.com/app/247080/",
    imageUrl: steamImage(247080),
    youtubeUrl: youtubeSearch("Crypt of the NecroDancer co-op gameplay")
  },
  {
    id: "trine-1",
    title: "Trine Enchanted Edition",
    year: 2009,
    genres: ["AA", "Action", "Platformer"],
    endingType: "story",
    rating: 96,
    playersMax: 3,
    hours: 7,
    oneCopy: "none",
    price: 229,
    verdict: "Сказочный платформер от Frozenbyte: рыцарь, маг и воровка решают пазлы и колотят скелетов втроём.",
    storeUrl: "https://store.steampowered.com/app/35700/",
    imageUrl: steamImage(35700),
    youtubeUrl: youtubeSearch("Trine 1 co-op gameplay")
  },
  {
    id: "outlast-trials",
    title: "The Outlast Trials",
    year: 2024,
    genres: ["Indie", "Horror"],
    endingType: "levels",
    rating: 93,
    playersMax: 4,
    hours: 20,
    oneCopy: "none",
    price: 222,
    verdict: "Кооперативный психо-хоррор от Red Barrels: сбегаем из садистских испытаний холодной войны.",
    storeUrl: "https://store.steampowered.com/app/1304930/",
    imageUrl: steamImage(1304930),
    youtubeUrl: youtubeSearch("Outlast Trials co-op gameplay")
  },
  {
    id: "cook-serve-delicious",
    title: "Cook, Serve, Delicious!",
    year: 2013,
    genres: ["Indie", "Puzzle"],
    endingType: "levels",
    rating: 94,
    playersMax: 2,
    hours: 15,
    oneCopy: "remote-play",
    price: 57,
    verdict: "Хардкорный симулятор кафе: бьём по клавишам, готовим бургеры и кофе, пока клиенты не лопнули.",
    storeUrl: "https://store.steampowered.com/app/247020/",
    imageUrl: steamImage(247020),
    youtubeUrl: youtubeSearch("Cook Serve Delicious co-op gameplay")
  },
  {
    id: "mosa-lina",
    title: "Mosa Lina",
    year: 2023,
    genres: ["Indie", "Puzzle"],
    endingType: "arcade-goal",
    rating: 96,
    playersMax: 4,
    hours: 6,
    oneCopy: "none",
    price: 187,
    verdict: "Антипазлер: каждые 60 секунд другая комбинация инструментов и одна цель — собрать фрукты.",
    storeUrl: "https://store.steampowered.com/app/2477090/",
    imageUrl: steamImage(2477090),
    youtubeUrl: youtubeSearch("Mosa Lina co-op gameplay")
  },
  {
    id: "dishwasher-vampire-smile",
    title: "The Dishwasher: Vampire Smile",
    year: 2017,
    genres: ["Indie", "Action"],
    endingType: "levels",
    rating: 95,
    playersMax: 2,
    hours: 7,
    oneCopy: "none",
    price: 169,
    verdict: "Стильный 2D-битэмап от Ska Studios: киберсамураи рубят боссов под индастриал.",
    storeUrl: "https://store.steampowered.com/app/268990/",
    imageUrl: steamImage(268990),
    youtubeUrl: youtubeSearch("Dishwasher Vampire Smile co-op gameplay")
  },
  {
    id: "astroneer",
    title: "ASTRONEER",
    year: 2019,
    genres: ["Indie", "Survival", "Adventure", "Sci-fi"],
    endingType: "survival-goal",
    rating: 92,
    playersMax: 4,
    hours: 16,
    oneCopy: "none",
    price: 600,
    verdict: "Космическая песочница про колонизацию планет — финал по сюжету про древнюю цивилизацию.",
    storeUrl: "https://store.steampowered.com/app/361420/",
    imageUrl: steamImage(361420),
    youtubeUrl: youtube("HkVPsGKYIiY")
  },
  {
    id: "valheim",
    title: "Valheim",
    year: 2021,
    genres: ["Indie", "Survival", "Open World", "Fantasy"],
    endingType: "survival-goal",
    rating: 94,
    playersMax: 10,
    hours: 50,
    oneCopy: "none",
    price: 539,
    verdict: "Викинговский survival с боссами — пять (а с Ashlands шесть) финальных боссов как условие победы.",
    storeUrl: "https://store.steampowered.com/app/892970/",
    imageUrl: steamImage(892970),
    youtubeUrl: youtube("IVBFVaMktDU")
  },
  {
    id: "lotr-return-to-moria",
    title: "The Lord of the Rings: Return to Moria",
    year: 2024,
    genres: ["AA", "Survival", "Adventure", "Fantasy"],
    endingType: "survival-goal",
    rating: 82,
    playersMax: 8,
    hours: 35,
    oneCopy: "none",
    price: 600,
    verdict: "Survival-crafting во вселенной LOTR — кампания про возвращение гномов в Морию с финалом.",
    storeUrl: "https://store.steampowered.com/app/2933130/",
    imageUrl: steamImage(2933130),
    youtubeUrl: youtube("oD04v9ufk6c")
  },
  {
    id: "heroes-of-hammerwatch-2",
    title: "Heroes of Hammerwatch II",
    year: 2025,
    genres: ["Indie", "Action", "RPG", "Isometric"],
    endingType: "roguelite",
    rating: 83,
    playersMax: 4,
    hours: 18,
    oneCopy: "none",
    price: 419,
    verdict: "Кооперативный roguelite-боевик: процедурные подземелья, прокачка героев, общий городок-хаб.",
    storeUrl: "https://store.steampowered.com/app/619820/",
    imageUrl: steamImage(619820),
    youtubeUrl: youtube("69DqrQe-cd8")
  },
  {
    id: "reanimal",
    title: "REANIMAL",
    year: 2026,
    genres: ["AAA", "Adventure", "Horror", "Puzzle"],
    endingType: "story",
    rating: 74,
    playersMax: 2,
    hours: 8,
    oneCopy: "none",
    price: 740,
    verdict: "Хоррор-приключение от создателей Little Nightmares — кооп на двоих с финалом.",
    storeUrl: "https://store.steampowered.com/app/2129530/",
    imageUrl: steamImage(2129530),
    youtubeUrl: youtube("YQVLlHbIuGU")
  },
  {
    id: "elden-ring-nightreign",
    title: "Elden Ring Nightreign",
    year: 2025,
    genres: ["AAA", "Action", "RPG", "Soulslike", "Fantasy"],
    endingType: "roguelite",
    rating: 82,
    playersMax: 3,
    hours: 30,
    oneCopy: "none",
    price: 1199,
    verdict: "Кооп-spinoff Elden Ring: roguelite-вылазки втроём против Найтлордов.",
    storeUrl: "https://store.steampowered.com/app/2622380/",
    imageUrl: steamImage(2622380),
    youtubeUrl: youtube("bRt3Ylt_Udk")
  },
  {
    id: "marvel-cosmic-invasion",
    title: "MARVEL Cosmic Invasion",
    year: 2025,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 88,
    playersMax: 4,
    hours: 6,
    oneCopy: "none",
    price: 673,
    verdict: "Beat'em up по Marvel от создателей TMNT Shredder's Revenge: до 4 героев, короткая кампания.",
    storeUrl: "https://store.steampowered.com/app/2753970/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2753970/bcb8dd8a710ecd285876fd185b162f5feb545ee3/header_alt_assets_0.jpg",
    youtubeUrl: youtube("95KGhcg1o1o")
  },
  {
    id: "slay-the-spire-2",
    title: "Slay the Spire 2",
    year: 2026,
    genres: ["Indie", "Tactics", "Adventure"],
    endingType: "roguelite",
    rating: 63,
    playersMax: 4,
    hours: 25,
    oneCopy: "none",
    price: 499,
    verdict: "Дека-билдер с боссом-финалом, теперь в кооперативе до 4 человек.",
    storeUrl: "https://store.steampowered.com/app/2868840/",
    imageUrl: steamImage(2868840),
    youtubeUrl: youtube("OiHkpr_FYc0"),
    "needs-review": true
  },
  {
    id: "absolum",
    title: "Absolum",
    year: 2025,
    genres: ["Indie", "Action", "Adventure", "Fantasy"],
    endingType: "roguelite",
    rating: 92,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 515,
    verdict: "Roguelite beat'em up от Dotemu: пиксельный экшен, кооп на двоих, финальный босс Сан-Кинг.",
    storeUrl: "https://store.steampowered.com/app/1904480/",
    imageUrl: steamImage(1904480),
    youtubeUrl: youtube("R3lBuJkHYh4")
  },
  {
    id: "cult-of-the-lamb",
    title: "Cult of the Lamb",
    year: 2022,
    genres: ["AA", "Action", "Adventure"],
    endingType: "roguelite",
    rating: 96,
    playersMax: 2,
    hours: 15,
    oneCopy: "remote-play",
    price: 499,
    verdict: "Симулятор секты + roguelite-вылазки. С обновлением Unholy Alliance — кооп на двоих.",
    storeUrl: "https://store.steampowered.com/app/1313140/",
    imageUrl: steamImage(1313140),
    youtubeUrl: youtube("mkxJ9zhWa6k")
  },
  {
    id: "rv-there-yet",
    title: "RV There Yet?",
    year: 2025,
    genres: ["Indie", "Adventure", "Puzzle"],
    endingType: "levels",
    rating: 91,
    playersMax: 4,
    hours: 6,
    oneCopy: "none",
    price: 187,
    verdict: "Хаотичный кооп-роуд-трип: вчетвером тащите трейлер сквозь препятствия. Короткая кампания.",
    storeUrl: "https://store.steampowered.com/app/3949040/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3949040/cae24b4ed7f4531be51f0d63f785b7d253f92dc3/header.jpg",
    youtubeUrl: youtube("BvRhz1RvAOE")
  },
  {
    id: "sniper-elite-resistance",
    title: "Sniper Elite: Resistance",
    year: 2025,
    genres: ["AA", "Shooter", "Third-person", "Military", "Stealth"],
    endingType: "levels",
    rating: 75,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 925,
    verdict: "Спин-офф Sniper Elite 5: миссии во французском Сопротивлении, кооп на двоих, X-Ray-выстрелы.",
    storeUrl: "https://store.steampowered.com/app/2169200/",
    imageUrl: steamImage(2169200),
    youtubeUrl: youtube("k_NLBkhOU6E")
  },
  {
    id: "powerwash-simulator-2",
    title: "PowerWash Simulator 2",
    year: 2025,
    genres: ["Indie", "Adventure", "Puzzle"],
    endingType: "levels",
    rating: 91,
    playersMax: 2,
    hours: 20,
    oneCopy: "none",
    price: 500,
    verdict: "Продолжение медитативной мойки — теперь со сплит-скрином и онлайн-кооперативом на двоих.",
    storeUrl: "https://store.steampowered.com/app/2968420/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2968420/91fea40a711c5a74cce1bb1a9e05c48a379f6aa0/header.jpg",
    youtubeUrl: youtube("gE7_okg5TQM")
  },
  {
    id: "abiotic-factor",
    title: "Abiotic Factor",
    year: 2025,
    genres: ["Indie", "Survival", "Sci-fi", "Adventure"],
    endingType: "survival-goal",
    rating: 96,
    playersMax: 6,
    hours: 30,
    oneCopy: "none",
    price: 700,
    verdict: "Half-Life-вдохновленный survival-кооп: учёные сбегают из подземной лаборатории. Финал в 1.0.",
    storeUrl: "https://store.steampowered.com/app/427410/",
    imageUrl: steamImage(427410),
    youtubeUrl: youtube("ESgISzPUCtw")
  },
  {
    id: "borderlands-4",
    title: "Borderlands 4",
    year: 2025,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot"],
    endingType: "story",
    rating: 59,
    playersMax: 4,
    hours: 35,
    oneCopy: "none",
    price: 2579,
    verdict: "Очередная BL: новая планета, четыре охотника, кампания на 4 игроков. Релиз получил смешанные отзывы.",
    storeUrl: "https://store.steampowered.com/app/1285190/",
    imageUrl: steamImage(1285190),
    youtubeUrl: youtube("vVfGbgW-nF4"),
    "needs-review": true
  },
  {
    id: "risk-of-rain-returns",
    title: "Risk of Rain Returns",
    year: 2023,
    genres: ["Indie", "Action", "Shooter", "Platformer"],
    endingType: "roguelite",
    rating: 90,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 211,
    verdict: "Ремейк первого Risk of Rain: 2D-roguelite-стрелялка с финальным боссом и кооп на 4.",
    storeUrl: "https://store.steampowered.com/app/1337520/",
    imageUrl: steamImage(1337520),
    youtubeUrl: youtube("r87yUeAXDMQ")
  },
  {
    id: "sniper-elite-4",
    title: "Sniper Elite 4",
    year: 2017,
    genres: ["AA", "Shooter", "Third-person", "Military", "Stealth"],
    endingType: "levels",
    rating: 91,
    playersMax: 2,
    hours: 16,
    oneCopy: "none",
    price: 699,
    verdict: "Снайперский стелс по Италии 40-х: огромные открытые миссии, кооп на двоих, X-Ray-выстрелы.",
    storeUrl: "https://store.steampowered.com/app/312660/",
    imageUrl: steamImage(312660),
    youtubeUrl: youtube("I432Z3qCtgs")
  },
  {
    id: "saints-row-3-remastered",
    title: "Saints Row: The Third Remastered",
    year: 2021,
    genres: ["AAA", "Action", "Third-person", "Open World"],
    endingType: "story",
    rating: 72,
    playersMax: 2,
    hours: 16,
    oneCopy: "none",
    price: 79,
    verdict: "Ремастер Saints Row 3: дурдом-сюжет про Святых в Steelport, кооп на двоих.",
    storeUrl: "https://store.steampowered.com/app/978300/",
    imageUrl: steamImage(978300),
    youtubeUrl: youtube("HTX--pyBxr4")
  },
  {
    id: "edf-6",
    title: "Earth Defense Force 6",
    year: 2024,
    genres: ["AA", "Shooter", "Third-person", "Sci-fi"],
    endingType: "levels",
    rating: 69,
    playersMax: 4,
    hours: 60,
    oneCopy: "none",
    price: 1999,
    verdict: "Очередная EDF: ещё больше жуков, ещё больше миссий. Онлайн-кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/2291060/",
    imageUrl: steamImage(2291060),
    youtubeUrl: youtube("55GmzkhLkrk"),
    "needs-review": true
  },
  {
    id: "far-cry-6",
    title: "Far Cry 6",
    year: 2023,
    genres: ["AAA", "Shooter", "FPS", "Action", "Open World"],
    endingType: "story",
    rating: 71,
    playersMax: 2,
    hours: 25,
    oneCopy: "none",
    price: 915,
    verdict: "Открытая Куба, революция против диктатора Кастильо. Кооп всю кампанию на двоих.",
    storeUrl: "https://store.steampowered.com/app/2369390/",
    imageUrl: steamImage(2369390),
    youtubeUrl: youtube("YCN7AF3b4GA")
  },
  {
    id: "trine-4",
    title: "Trine 4: The Nightmare Prince",
    year: 2019,
    genres: ["AA", "Adventure", "Platformer", "Puzzle", "Fantasy"],
    endingType: "story",
    rating: 89,
    playersMax: 4,
    hours: 10,
    oneCopy: "none",
    price: 379,
    verdict: "Сказочный платформер-головоломка про троих героев: рыцарь, маг и воровка. Теперь до 4 в коопе.",
    storeUrl: "https://store.steampowered.com/app/690640/",
    imageUrl: steamImage(690640),
    youtubeUrl: youtube("szdg4txFw6U")
  },
  {
    id: "monster-hunter-world",
    title: "Monster Hunter: World",
    year: 2018,
    genres: ["AAA", "Action", "RPG", "Adventure", "Fantasy"],
    endingType: "story",
    rating: 89,
    playersMax: 4,
    hours: 60,
    oneCopy: "none",
    price: 949,
    verdict: "Охота на гигантских монстров в Новом Мире. Кампания + SOS-флаеры на четверых.",
    storeUrl: "https://store.steampowered.com/app/582010/",
    imageUrl: steamImage(582010),
    youtubeUrl: youtube("jn7zTVX-FD8")
  },
  {
    id: "unravel-two",
    title: "Unravel Two",
    year: 2020,
    genres: ["AAA", "Adventure", "Platformer", "Puzzle"],
    endingType: "story",
    rating: 78,
    playersMax: 2,
    hours: 7,
    oneCopy: "remote-play",
    price: 699,
    verdict: "Душевный платформер про двух Ярни, связанных нитью. Локальный кооп через Remote Play.",
    storeUrl: "https://store.steampowered.com/app/1225570/",
    imageUrl: steamImage(1225570),
    youtubeUrl: youtube("KCUsy2UamxQ")
  },
  {
    id: "state-of-decay-2",
    title: "State of Decay 2: Juggernaut Edition",
    year: 2020,
    genres: ["AAA", "Action", "RPG", "Survival", "Horror"],
    endingType: "survival-goal",
    rating: 83,
    playersMax: 4,
    hours: 25,
    oneCopy: "none",
    price: 379,
    verdict: "Зомби-апокалипсис с базой и общиной: 4 финала Legacy. Онлайн-кооп до 4 игроков.",
    storeUrl: "https://store.steampowered.com/app/495420/",
    imageUrl: steamImage(495420),
    youtubeUrl: youtube("iMJ803rxem8")
  },
  {
    id: "space-hulk-deathwing",
    title: "Space Hulk: Deathwing Enhanced Edition",
    year: 2018,
    genres: ["AA", "Shooter", "FPS", "Sci-fi", "Military"],
    endingType: "levels",
    rating: 72,
    playersMax: 4,
    hours: 12,
    oneCopy: "none",
    price: 59,
    verdict: "Кооп-FPS по Warhammer 40k: терминаторы зачищают Space Hulk от тиранидов. Кампания на 4.",
    storeUrl: "https://store.steampowered.com/app/816090/",
    imageUrl: steamImage(816090),
    youtubeUrl: youtube("6an1gvsR6r8")
  },
  {
    id: "divinity-original-sin-1",
    title: "Divinity: Original Sin - Enhanced Edition",
    year: 2015,
    genres: ["AA", "RPG", "Tactics", "Fantasy", "Isometric"],
    endingType: "story",
    rating: 89,
    playersMax: 2,
    hours: 60,
    oneCopy: "none",
    price: 47,
    verdict: "Изометрическая тактическая RPG-кампания на двоих от Larian. Предшественник D:OS2.",
    storeUrl: "https://store.steampowered.com/app/373420/",
    imageUrl: steamImage(373420),
    youtubeUrl: youtube("HnffHGYbpxc")
  },
  {
    id: "vermintide-1",
    title: "Warhammer: End Times - Vermintide",
    year: 2015,
    genres: ["AA", "Shooter", "FPS", "Action", "Fantasy"],
    endingType: "levels",
    rating: 80,
    playersMax: 4,
    hours: 18,
    oneCopy: "none",
    price: 60,
    verdict: "Первая Vermintide: убиваем скейвенов в Юбершрайке. Предшественник VT2.",
    storeUrl: "https://store.steampowered.com/app/235540/",
    imageUrl: steamImage(235540),
    youtubeUrl: youtube("d1xJv3pSNZU")
  },
  {
    id: "lego-voyagers",
    title: "LEGO Voyagers",
    year: 2025,
    genres: ["AA", "Adventure", "Puzzle", "Platformer"],
    endingType: "story",
    rating: 88,
    playersMax: 2,
    hours: 6,
    oneCopy: "remote-play",
    price: 489,
    verdict: "Кооп-приключение про двух LEGO-кубиков, спасающих космический корабль. В духе Split Fiction.",
    storeUrl: "https://store.steampowered.com/app/1538550/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1538550/db718ae2be60558df2ef9fcd65302ad87a6045d4/header.jpg",
    youtubeUrl: youtube("0kzKpCAV7Ks")
  },
  {
    id: "together-moon-escape",
    title: "Together: Moon Escape",
    year: 2026,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 90,
    playersMax: 2,
    hours: 5,
    oneCopy: "remote-play",
    price: 225,
    verdict: "Кооп-приключение на двоих в невесомости: асимметричные пазлы, побег из империи слизи Moontella.",
    storeUrl: "https://store.steampowered.com/app/3744430/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3744430/2b1989c2b09a474a13a9dc3db410248ad9fc04e4/header.jpg",
    youtubeUrl: youtube("e4Vhv2WgvzA")
  },
  {
    id: "parallel-experiment",
    title: "Parallel Experiment",
    year: 2025,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 84,
    playersMax: 2,
    hours: 4,
    oneCopy: "none",
    price: 225,
    verdict: "Кооп-эскейп: два детектива, каждый со своей половиной пазла, должны общаться чтобы выжить.",
    storeUrl: "https://store.steampowered.com/app/2012320/",
    imageUrl: steamImage(2012320),
    youtubeUrl: youtube("r0lefeOTYYA")
  },
  {
    id: "hellcard",
    title: "HELLCARD",
    year: 2024,
    genres: ["Indie", "Tactics", "Adventure"],
    endingType: "roguelite",
    rating: 86,
    playersMax: 3,
    hours: 20,
    oneCopy: "none",
    price: 399,
    verdict: "Кооп-roguelite дека-билдер от создателей Book of Demons: бумажная стилистика, до 3 в кооперативе.",
    storeUrl: "https://store.steampowered.com/app/1201540/",
    imageUrl: steamImage(1201540),
    youtubeUrl: youtube("V-XrmbnaOGM")
  },
  {
    id: "secrets-of-grindea",
    title: "Secrets of Grindea",
    year: 2024,
    genres: ["Indie", "Action", "RPG", "Adventure"],
    endingType: "story",
    rating: 89,
    playersMax: 4,
    hours: 30,
    oneCopy: "none",
    price: 229,
    verdict: "Олдскульная пиксельная action-RPG в духе Secret of Mana. Кампания и кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/269770/",
    imageUrl: steamImage(269770),
    youtubeUrl: youtube("CkEQFNMs290")
  },
  {
    id: "dying-light-the-beast",
    title: "Dying Light: The Beast",
    year: 2025,
    genres: ["AA", "Action", "Adventure", "Horror", "Open World", "Survival"],
    endingType: "story",
    rating: 87,
    playersMax: 4,
    hours: 18,
    oneCopy: "none",
    price: 1599,
    verdict: "Самостоятельный спин-офф Dying Light 2: новый регион, новая кампания, паркур+кооп на 4.",
    storeUrl: "https://store.steampowered.com/app/3008130/",
    imageUrl: steamImage(3008130),
    youtubeUrl: youtube("-9ugPXmWcfg")
  },
  {
    id: "ready-or-not",
    title: "Ready or Not",
    year: 2023,
    genres: ["Indie", "Shooter", "FPS", "Tactics", "Military"],
    endingType: "levels",
    rating: 78,
    playersMax: 5,
    hours: 16,
    oneCopy: "none",
    price: 625,
    verdict: "Хардкорная SWAT-тактика: миссии с заложниками, медленно и страшно. Кооп до 5.",
    storeUrl: "https://store.steampowered.com/app/1144200/",
    imageUrl: steamImage(1144200),
    youtubeUrl: youtube("_8LSKoxTjOg")
  },
  {
    id: "lego-batman-legacy",
    title: "LEGO Batman: Legacy of the Dark Knight",
    year: 2026,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "story",
    rating: 97,
    playersMax: 2,
    hours: 14,
    oneCopy: "remote-play",
    price: 1899,
    verdict: "Новая LEGO Batman от TT Games: сплит-скрин + Remote Play, кампания на двоих.",
    storeUrl: "https://store.steampowered.com/app/2215200/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215200/a07a9a6c0c9c1225f5b260b4f29fe40e6f099f6b/header.jpg",
    youtubeUrl: youtube("Mi-ru6HY5sA")
  },
  {
    id: "thick-as-thieves",
    title: "Thick As Thieves",
    year: 2026,
    genres: ["AA", "Action", "Stealth", "Adventure"],
    endingType: "levels",
    rating: 73,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 195,
    verdict: "Stealth-экшен про двух воров в магической столице 1910-х. Кооп на двоих от OtherSide Entertainment.",
    storeUrl: "https://store.steampowered.com/app/3341000/",
    imageUrl: steamImage(3341000),
    youtubeUrl: youtube("I8NwUMBNnrs")
  },
  {
    id: "in-sink",
    title: "In Sink: A Co-op Escape Adventure",
    year: 2024,
    genres: ["Indie", "Adventure", "Puzzle"],
    endingType: "arcade-goal",
    rating: 87,
    playersMax: 2,
    hours: 6,
    oneCopy: "none",
    price: 325,
    verdict: "Кооп-эскейп: вдвоём решаете загадки, чтобы сбежать с пустынного острова.",
    storeUrl: "https://store.steampowered.com/app/1858650/",
    imageUrl: steamImage(1858650),
    youtubeUrl: youtube("f04Sn_B6rzE")
  },
  {
    id: "bokura",
    title: "BOKURA",
    year: 2023,
    genres: ["Indie", "Adventure", "Puzzle", "Platformer"],
    endingType: "story",
    rating: 92,
    playersMax: 2,
    hours: 4,
    oneCopy: "none",
    price: 122,
    verdict: "Асимметричный кооп: два игрока видят разные миры, должны общаться чтобы решить пазлы.",
    storeUrl: "https://store.steampowered.com/app/1801110/",
    imageUrl: steamImage(1801110),
    youtubeUrl: youtube("u26eyzvcQSk")
  },
  {
    id: "the-past-within",
    title: "The Past Within",
    year: 2022,
    genres: ["Indie", "Adventure", "Puzzle", "Horror"],
    endingType: "story",
    rating: 95,
    playersMax: 2,
    hours: 3,
    oneCopy: "friend-pass",
    price: 149,
    verdict: "Асимметричный кооп от Rusty Lake: один в Прошлом, другой в Будущем. Один экземпляр на двоих.",
    storeUrl: "https://store.steampowered.com/app/1515210/",
    imageUrl: steamImage(1515210),
    youtubeUrl: youtube("gQ8K4WZH8uI")
  },
  {
    id: "pampas-selene",
    title: "Pampas & Selene: The Maze of Demons",
    year: 2024,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 91,
    playersMax: 2,
    hours: 10,
    oneCopy: "none",
    price: 225,
    verdict: "Co-opvania 8-bit платформер от создателя UnEpic: вдвоём против Тёмного Жреца.",
    storeUrl: "https://store.steampowered.com/app/1966220/",
    imageUrl: steamImage(1966220),
    youtubeUrl: youtube("rEI-hK7jugQ")
  },
  {
    id: "blood-typers",
    title: "Blood Typers",
    year: 2025,
    genres: ["Indie", "Horror", "Survival", "Adventure"],
    endingType: "story",
    rating: 95,
    playersMax: 4,
    hours: 8,
    oneCopy: "none",
    price: 274,
    verdict: "Survival-horror в стиле Resident Evil, но врагов убиваешь печатанием слов. Кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/2790330/",
    imageUrl: steamImage(2790330),
    youtubeUrl: youtube("pfsL5AcgmLI")
  },
  {
    id: "a-way-out",
    title: "A Way Out",
    year: 2018,
    genres: ["AA", "Action", "Adventure", "Third-person"],
    endingType: "story",
    rating: 78,
    playersMax: 2,
    hours: 6,
    oneCopy: "friend-pass",
    price: 799,
    verdict: "Спрятано: уже пройдено. Полностью построено вокруг дуо.",
    storeUrl: "https://store.steampowered.com/app/1222700/A_Way_Out/",
    imageUrl: steamImage(1222700),
    youtubeUrl: youtube("87HIFtmB948"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "it-takes-two",
    title: "It Takes Two",
    year: 2021,
    genres: ["AA", "Action", "Adventure", "Puzzle", "Platformer"],
    endingType: "story",
    rating: 89,
    playersMax: 2,
    hours: 12,
    oneCopy: "friend-pass",
    price: 999,
    verdict: "Спрятано: уже пройдено. Friend's Pass закрывает покупку второй копии.",
    storeUrl: "https://store.steampowered.com/app/1426210/It_Takes_Two/",
    imageUrl: steamImage(1426210),
    youtubeUrl: youtube("SPa5JXzPaAk"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "split-fiction",
    title: "Split Fiction",
    year: 2025,
    genres: ["AA", "Action", "Adventure", "Platformer", "Sci-fi", "Fantasy"],
    endingType: "story",
    rating: 91,
    playersMax: 2,
    hours: 15,
    oneCopy: "friend-pass",
    price: 1299,
    verdict: "Спрятано: уже пройдено. Эталонная проверка поля Friend Pass.",
    storeUrl: "https://store.steampowered.com/app/2001120/Split_Fiction/",
    imageUrl: steamImage(2001120),
    youtubeUrl: youtube("fcwngWPXQtg"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "resident-evil-5",
    title: "Resident Evil 5",
    year: 2009,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 86,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 649,
    verdict: "Спрятано: уже пройдено. Классический кооп-боевик Capcom.",
    storeUrl: "https://store.steampowered.com/app/21690/Resident_Evil_5/",
    imageUrl: steamImage(21690),
    youtubeUrl: youtube("qUsTgI0cs4c"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "resident-evil-6",
    title: "Resident Evil 6",
    year: 2013,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 69,
    playersMax: 2,
    hours: 21,
    oneCopy: "none",
    price: 649,
    verdict: "Спрятано: уже пройдено. Много кампаний, много хаоса, спорная репутация.",
    storeUrl: "https://store.steampowered.com/app/221040/Resident_Evil_6/",
    imageUrl: steamImage(221040),
    youtubeUrl: youtube("mI6TntXFfZY"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "dead-space-3",
    title: "Dead Space 3",
    year: 2013,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Horror", "Sci-fi"],
    endingType: "story",
    rating: 78,
    playersMax: 2,
    hours: 12,
    oneCopy: "none",
    price: 699,
    verdict: "Спрятано: уже пройдено. Кооп сильнее меняет тон игры, чем в первых двух частях.",
    storeUrl: "https://store.steampowered.com/app/1238060/Dead_Space_3/",
    imageUrl: steamImage(1238060),
    youtubeUrl: youtube("cZ3mad7SOBg"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "army-of-two",
    title: "Army of Two",
    year: 2008,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Military"],
    endingType: "story",
    rating: 74,
    playersMax: 2,
    hours: 7,
    oneCopy: "none",
    price: 0,
    verdict: "Спрятано: уже пройдено и оставлено как референс. Не является активным PC-кандидатом.",
    storeUrl: "https://en.wikipedia.org/wiki/Army_of_Two_(video_game)",
    imageUrl: "https://i.ytimg.com/vi/WbggbjbHphA/hqdefault.jpg",
    youtubeUrl: youtube("WbggbjbHphA"),
    hidden: true,
    hiddenReason: "Уже играли / референс"
  }
];
