const steamImage = (appId) => `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;
const youtube = (id) => `https://www.youtube.com/watch?v=${id}`;
const youtubeSearch = (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q + " co-op gameplay")}`;

window.GAMES = [
  {
    id: "gears-of-war-reloaded",
    title: "Gears of War: Reloaded",
    year: 2025,
    genres: ["AAA", "Shooter", "Third-person", "Action"],
    endingType: "story",
    rating: 79,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 79",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 8.5,
    hoursLabel: "7-10",
    oneCopy: "none",
    price: 1299,
    verdict: "Самый прямой наследник ощущения Army of Two: укрытия, мясо, дуо.",
    storeUrl: "https://store.steampowered.com/app/2523720/Gears_of_War_Reloaded/",
    imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2523720/779c1934da3b39c307d91195ff764502f2ce1063/capsule_616x353.jpg",
    youtubeUrl: youtube("UHg5MMnsMJ4")
  },
  {
    id: "space-marine-2",
    title: "Warhammer 40,000: Space Marine 2",
    year: 2024,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Sci-fi"],
    endingType: "story",
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 11,
    hoursLabel: "10-12",
    oneCopy: "none",
    price: 1299,
    verdict: "Очень жирный современный кооп-экшен. Не про укрытия, а про продавить всё силой.",
    storeUrl: "https://store.steampowered.com/app/2183900/Warhammer_40000_Space_Marine_2/",
    imageUrl: steamImage(2183900),
    youtubeUrl: youtube("_5qGL9IK-XY")
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    year: 2023,
    genres: ["AAA", "RPG", "Tactics", "Fantasy"],
    endingType: "story",
    rating: 96,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 96",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 85,
    hoursLabel: "80+",
    oneCopy: "none",
    price: 899,
    verdict: "Лучший вариант, если окей пошаговая ролевая игра и большая законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
    imageUrl: steamImage(1086940),
    youtubeUrl: youtube("UxSgaBXMqP4")
  },
  {
    id: "remnant-2",
    title: "Remnant II",
    year: 2023,
    genres: ["AA", "Shooter", "Action", "RPG", "Soulslike"],
    endingType: "story",
    rating: 80,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 80",
    playersMax: 3,
    playersLabel: "до 3",
    hours: 22,
    hoursLabel: "18-25",
    oneCopy: "none",
    price: 1299,
    verdict: "Dark Souls с пушками. Кампания конечная, но игра любит повторные прохождения и лут.",
    storeUrl: "https://store.steampowered.com/app/1282100/REMNANT_II/",
    imageUrl: steamImage(1282100),
    youtubeUrl: youtube("x3ZheAh5oPc")
  },
  {
    id: "trine-5",
    title: "Trine 5: A Clockwork Conspiracy",
    year: 2023,
    genres: ["AA", "Puzzle", "Platformer", "Fantasy"],
    endingType: "story",
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 78",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 13,
    hoursLabel: "12-14",
    oneCopy: "remote-play",
    price: 600,
    verdict: "Кооп-пазлы и платформинг. Не AAA, но аккуратная законченная игра.",
    storeUrl: "https://store.steampowered.com/app/1436700/Trine_5_A_Clockwork_Conspiracy/",
    imageUrl: steamImage(1436700),
    youtubeUrl: youtube("MDCcvLZVEnM")
  },
  {
    id: "sniper-elite-5",
    title: "Sniper Elite 5",
    year: 2022,
    genres: ["AA", "Shooter", "Stealth", "Tactics", "Military"],
    endingType: "story",
    rating: 79,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 79",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "none",
    price: 579,
    verdict: "Медленнее Army of Two: стелс, снайпинг, тактика. Вдвоём работает хорошо.",
    storeUrl: "https://store.steampowered.com/app/1029690/Sniper_Elite_5/",
    imageUrl: steamImage(1029690),
    youtubeUrl: youtube("uG8LCpWPZlg")
  },
  {
    id: "we-were-here-forever",
    title: "We Were Here Forever",
    year: 2022,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 56,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 56% рекомендуют",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 375,
    verdict: "Пазл-кооп с голосовой связью. Не экшен, но именно игра для двоих.",
    storeUrl: "https://store.steampowered.com/app/1341290/We_Were_Here_Forever/",
    imageUrl: steamImage(1341290),
    youtubeUrl: youtube("YeNCUS_Cdas")
  },
  {
    id: "operation-tango",
    title: "Operation: Tango",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 76,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 76",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 4,
    hoursLabel: "3-5",
    oneCopy: "friend-pass",
    price: 415,
    verdict: "Асимметричный шпионский кооп: один агент, второй хакер. Короткая, зато честно сделана под двух игроков.",
    storeUrl: "https://store.steampowered.com/app/1335790/Operation_Tango/",
    imageUrl: steamImage(1335790),
    youtubeUrl: youtube("CIJZ2tfW__8")
  },
  {
    id: "the-ascent",
    title: "The Ascent",
    year: 2021,
    genres: ["AA", "Shooter", "Action", "RPG", "Sci-fi", "Isometric"],
    endingType: "story",
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 74",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 14,
    hoursLabel: "12-16",
    oneCopy: "remote-play",
    price: 635,
    verdict: "Киберпанк twin-stick шутер. Красивый, но сюжет не главный козырь.",
    storeUrl: "https://store.steampowered.com/app/979690/The_Ascent/",
    imageUrl: steamImage(979690),
    youtubeUrl: youtube("vXUTYzj_bKE")
  },
  {
    id: "outriders",
    title: "Outriders",
    year: 2021,
    genres: ["AAA", "Shooter", "Action", "RPG", "Loot", "Sci-fi"],
    endingType: "story",
    rating: 73,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 73",
    playersMax: 3,
    playersLabel: "до 3",
    hours: 20,
    hoursLabel: "16-25",
    oneCopy: "none",
    price: 499,
    verdict: "Кампания есть и заканчивается, но это лутер-шутер. Брать, если окей гриндовая ДНК.",
    storeUrl: "https://store.steampowered.com/app/680420/OUTRIDERS/",
    imageUrl: steamImage(680420),
    youtubeUrl: youtube("S8TaAcA0_Ug")
  },
  {
    id: "wasteland-3",
    title: "Wasteland 3",
    year: 2020,
    genres: ["AA", "RPG", "Tactics"],
    endingType: "story",
    rating: 85,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 85",
    playersMax: 2,
    playersLabel: "2",
    hours: 50,
    hoursLabel: "45-60",
    oneCopy: "none",
    price: 479,
    verdict: "Пошаговая ролевая игра с нормальным сюжетом и решениями. Хороший кооп, если хочется не шутер.",
    storeUrl: "https://store.steampowered.com/app/719040/Wasteland_3/",
    imageUrl: steamImage(719040),
    youtubeUrl: youtube("4XY4BAtJuow")
  },
  {
    id: "gears-5",
    title: "Gears 5",
    year: 2019,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Sci-fi"],
    endingType: "story",
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 11,
    hoursLabel: "10-12",
    oneCopy: "none",
    price: 760,
    verdict: "Один из лучших вариантов под запрос: AAA, сюжет, экшен, можно проходить вдвоём.",
    storeUrl: "https://store.steampowered.com/app/1097840/Gears_5/",
    imageUrl: steamImage(1097840),
    youtubeUrl: youtube("yxnXis9OV_E")
  },
  {
    id: "halo-mcc",
    title: "Halo: The Master Chief Collection",
    year: 2019,
    genres: ["AAA", "Shooter", "FPS", "Sci-fi"],
    endingType: "story",
    rating: 91,
    ratingSource: "Steam",
    ratingLabel: "Steam 91% positive",
    playersMax: 4,
    playersLabel: "2-4, кампании",
    hours: 55,
    hoursLabel: "50+",
    oneCopy: "none",
    price: 1399,
    verdict: "Много законченных кампаний в одном пакете. Минус - это FPS, не постановочный дуо-боевик.",
    storeUrl: "https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/",
    imageUrl: steamImage(976730),
    youtubeUrl: youtube("yTy41rmm6rk")
  },
  {
    id: "darksiders-genesis",
    title: "Darksiders Genesis",
    year: 2019,
    genres: ["AA", "Action", "Isometric", "Fantasy"],
    endingType: "story",
    rating: 77,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 77",
    playersMax: 2,
    playersLabel: "2",
    hours: 13.5,
    hoursLabel: "12-15",
    oneCopy: "remote-play",
    price: 389,
    verdict: "Изометрический экшен про двух персонажей. Ближе к Diablo/Darksiders, чем к Army of Two.",
    storeUrl: "https://store.steampowered.com/app/710920/Darksiders_Genesis/",
    imageUrl: steamImage(710920),
    youtubeUrl: youtube("C7Hxw08wRfs")
  },
  {
    id: "wolfenstein-youngblood",
    title: "Wolfenstein: Youngblood",
    year: 2019,
    genres: ["AAA", "Shooter", "FPS", "Action", "Sci-fi"],
    endingType: "story",
    rating: 69,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 69",
    playersMax: 2,
    playersLabel: "2",
    hours: 10,
    hoursLabel: "9-12",
    oneCopy: "friend-pass",
    price: 349,
    verdict: "Кооп и кампания есть, но игра спорная. Buddy Pass работает через Deluxe Edition.",
    storeUrl: "https://store.steampowered.com/app/1056960/Wolfenstein_Youngblood/",
    imageUrl: steamImage(1056960),
    youtubeUrl: youtube("lFM7zFCVwgo")
  },
  {
    id: "far-cry-5",
    title: "Far Cry 5",
    year: 2018,
    genres: ["AAA", "Shooter", "FPS", "Open World", "Action"],
    endingType: "story",
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 22,
    hoursLabel: "18-25",
    oneCopy: "none",
    price: 915,
    verdict: "Открытый мир, не постановочная дуо-игра. Вдвоём весело, но сюжетно рыхло.",
    storeUrl: "https://store.steampowered.com/app/552520/Far_Cry_5/",
    imageUrl: steamImage(552520),
    youtubeUrl: youtube("n-lJd1gueOQ")
  },
  {
    id: "divinity-original-sin-2",
    title: "Divinity: Original Sin II",
    year: 2017,
    genres: ["AAA", "RPG", "Tactics", "Fantasy"],
    endingType: "story",
    rating: 93,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 93",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 75,
    hoursLabel: "70+",
    oneCopy: "remote-play",
    price: 529,
    verdict: "Если BG3 зайдёт, это почти обязательная следующая остановка. Кампания огромная и законченная.",
    storeUrl: "https://store.steampowered.com/app/435150/Divinity_Original_Sin_2/",
    imageUrl: steamImage(435150),
    youtubeUrl: youtube("unWFWGrMbpc")
  },
  {
    id: "ghost-recon-wildlands",
    title: "Ghost Recon Wildlands",
    year: 2017,
    genres: ["AAA", "Shooter", "Third-person", "Open World", "Tactics", "Military"],
    endingType: "story",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam 80% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 35,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 759,
    verdict: "Военный кооп в открытом мире. Сюжет слабее, зато двое чистят карту работает.",
    storeUrl: "https://store.steampowered.com/app/460930/Tom_Clancys_Ghost_Recon_Wildlands/",
    imageUrl: steamImage(460930),
    youtubeUrl: youtube("7UboU-rioaY")
  },
  {
    id: "portal-2",
    title: "Portal 2",
    year: 2011,
    genres: ["AAA", "Puzzle", "FPS", "Sci-fi"],
    endingType: "story",
    rating: 95,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 95",
    playersMax: 2,
    playersLabel: "2, отдельная кампания",
    hours: 5,
    hoursLabel: "4-6",
    oneCopy: "remote-play",
    price: 225,
    verdict: "Если не проходил кооп-кампанию, это must-play. Не просто режим, а отдельная игра на двоих.",
    storeUrl: "https://store.steampowered.com/app/620/Portal_2/",
    imageUrl: steamImage(620),
    youtubeUrl: youtube("aySPmEBzlS4")
  },
  {
    id: "lara-croft-guardian-light",
    title: "Lara Croft and the Guardian of Light",
    year: 2010,
    genres: ["AAA", "Action", "Puzzle", "Adventure", "Isometric"],
    endingType: "story",
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 2,
    playersLabel: "2",
    hours: 7,
    hoursLabel: "6-8",
    oneCopy: "remote-play",
    price: 180,
    verdict: "Старенькая, но крепкая приключенческая кооп-игра с пазлами и боёвкой.",
    storeUrl: "https://store.steampowered.com/app/35130/Lara_Croft_and_the_Guardian_of_Light/",
    imageUrl: steamImage(35130),
    youtubeUrl: youtube("nER0GNRlK_c")
  },
  {
    id: "borderlands-3",
    title: "Borderlands 3",
    year: 2019,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot", "Open World"],
    endingType: "story",
    rating: 81,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 81",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 23,
    hoursLabel: "22-25",
    oneCopy: "none",
    price: 849,
    verdict: "Крупная кооп-кампания с отличной стрельбой и лутом. Сюжет спорный, но вдвоём темп держит хорошо.",
    storeUrl: "https://store.steampowered.com/app/397540/Borderlands_3/",
    imageUrl: steamImage(397540),
    youtubeUrl: youtube("KojWXk9Vgso")
  },
  {
    id: "tiny-tinas-wonderlands",
    title: "Tiny Tina's Wonderlands",
    year: 2022,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot", "Fantasy"],
    endingType: "story",
    rating: 80,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 80",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 17,
    hoursLabel: "16-20",
    oneCopy: "none",
    price: 1249,
    verdict: "Borderlands в фэнтези-обёртке. Хороший вариант, если хочется стрельбы, классов и более лёгкого тона.",
    storeUrl: "https://store.steampowered.com/app/1286680/Tiny_Tinas_Wonderlands/",
    imageUrl: steamImage(1286680),
    youtubeUrl: youtube("L0wnhP_mQKA")
  },
  {
    id: "dying-light",
    title: "Dying Light",
    year: 2015,
    genres: ["AAA", "Action", "FPS", "RPG", "Open World", "Horror"],
    endingType: "story",
    rating: 75,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 75",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 18,
    hoursLabel: "17-20",
    oneCopy: "none",
    price: 349,
    verdict: "Паркур, зомби и полный кооп кампании после вступления. Более грязный и живой вариант для двоих.",
    storeUrl: "https://store.steampowered.com/app/239140/Dying_Light/",
    imageUrl: steamImage(239140),
    youtubeUrl: youtube("pL4a6QkzkLs")
  },
  {
    id: "dying-light-2",
    title: "Dying Light 2 Stay Human",
    year: 2022,
    genres: ["AAA", "Action", "FPS", "RPG", "Open World", "Horror"],
    endingType: "story",
    rating: 77,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 77",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 24,
    hoursLabel: "22-28",
    oneCopy: "none",
    price: 1599,
    verdict: "Больше открытого мира и паркура, чем в первой части. Кооп есть почти на всю кампанию, прогресс сильнее завязан на хоста.",
    storeUrl: "https://store.steampowered.com/app/534380/Dying_Light_2_Stay_Human_Reloaded_Edition/",
    imageUrl: steamImage(534380),
    youtubeUrl: youtube("inetjGIjKGU")
  },
  {
    id: "shadow-warrior-2",
    title: "Shadow Warrior 2",
    year: 2016,
    genres: ["AA", "Shooter", "FPS", "Action", "Loot"],
    endingType: "levels",
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 13,
    hoursLabel: "12-15",
    oneCopy: "none",
    price: 600,
    verdict: "Быстрый мясной FPS с оружием, мечами и лутом. Сюжет вторичен, зато экшен в коопе бодрый.",
    storeUrl: "https://store.steampowered.com/app/324800/Shadow_Warrior_2/",
    imageUrl: steamImage(324800),
    youtubeUrl: youtube("ftciCeHHn5c")
  },
  {
    id: "strange-brigade",
    title: "Strange Brigade",
    year: 2018,
    genres: ["AA", "Shooter", "Third-person", "Action", "Adventure"],
    endingType: "story",
    rating: 74,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 74",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 8,
    hoursLabel: "7-9",
    oneCopy: "none",
    price: 579,
    verdict: "Пульповый кооп-шутер про экспедиции, ловушки и толпы врагов. Больше аркада, чем сюжетный дуо-боевик.",
    storeUrl: "https://store.steampowered.com/app/312670/Strange_Brigade/",
    imageUrl: steamImage(312670),
    youtubeUrl: youtube("PpAHlg2oIDQ")
  },
  {
    id: "aliens-fireteam-elite",
    title: "Aliens: Fireteam Elite",
    year: 2021,
    genres: ["AA", "Shooter", "Third-person", "Action", "Horror", "Sci-fi"],
    endingType: "story",
    rating: 67,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 67",
    playersMax: 3,
    playersLabel: "до 3, миссии",
    hours: 8,
    hoursLabel: "7-10",
    oneCopy: "none",
    price: 599,
    verdict: "Трёхместный кооп по Aliens: коридоры, классы, ксеноморфы. Хорошо как вечерний шутер, слабее как история.",
    storeUrl: "https://store.steampowered.com/app/1549970/Aliens_Fireteam_Elite/",
    imageUrl: steamImage(1549970),
    youtubeUrl: youtube("6c8TrceZWS4")
  },
  {
    id: "back-4-blood",
    title: "Back 4 Blood",
    year: 2021,
    genres: ["AAA", "Shooter", "FPS", "Action", "Horror"],
    endingType: "story",
    rating: 77,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 77",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 749,
    verdict: "Наследник Left 4 Dead с карточной системой и кооп-кампанией. Хорошо для стрельбы, но не для плотного сюжета.",
    storeUrl: "https://store.steampowered.com/app/924970/Back_4_Blood/",
    imageUrl: steamImage(924970),
    youtubeUrl: youtube("mnjwzd0WsEQ")
  },
  {
    id: "grounded",
    title: "Grounded",
    year: 2022,
    genres: ["AA", "Survival", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 35,
    hoursLabel: "30-45",
    oneCopy: "none",
    price: 479,
    verdict: "Выживание с историей и хорошим коопом. Не боевик, зато сильная совместная песочница с понятной целью.",
    storeUrl: "https://store.steampowered.com/app/962130/Grounded/",
    imageUrl: steamImage(962130),
    youtubeUrl: youtube("ebITJ7jQIf4")
  },
  {
    id: "nobody-saves-the-world",
    title: "Nobody Saves the World",
    year: 2022,
    genres: ["Indie", "Action", "RPG", "Isometric"],
    endingType: "story",
    rating: 79,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 79",
    playersMax: 2,
    playersLabel: "2",
    hours: 16,
    hoursLabel: "15-18",
    oneCopy: "none",
    price: 530,
    verdict: "Изометрический action RPG с онлайн-коопом на двоих. Не AAA, но аккуратная законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/1432050/Nobody_Saves_the_World/",
    imageUrl: steamImage(1432050),
    youtubeUrl: youtube("OZQPvKMUlkc")
  },
  {
    id: "styx-shards-of-darkness",
    title: "Styx: Shards of Darkness",
    year: 2017,
    genres: ["AA", "Stealth", "Action", "Fantasy"],
    endingType: "story",
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 74",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 14,
    hoursLabel: "12-16",
    oneCopy: "none",
    price: 249,
    verdict: "Редкий полноценный кооп-стелс. Хороший кандидат, если хочется не стрелять, а синхронно прокрадываться.",
    storeUrl: "https://store.steampowered.com/app/355790/Styx_Shards_of_Darkness/",
    imageUrl: steamImage(355790),
    youtubeUrl: youtube("apwc3_A9WL8")
  },
  {
    id: "saints-row-4",
    title: "Saints Row IV: Re-Elected",
    year: 2013,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Open World", "Sci-fi"],
    endingType: "story",
    rating: 86,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 86",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 16,
    hoursLabel: "15-18",
    oneCopy: "none",
    price: 533,
    verdict: "Безумный открытый мир с кооп-кампанией. Стоит держать в списке, но PC-кооп у серии иногда капризный.",
    storeUrl: "https://store.steampowered.com/app/206420/Saints_Row_IV_ReElected/",
    imageUrl: steamImage(206420),
    youtubeUrl: youtube("kzDK1IYo9nw")
  },
  {
    id: "borderlands-2",
    title: "Borderlands 2",
    year: 2012,
    genres: ["AAA", "Shooter", "FPS", "RPG", "Loot", "Open World"],
    endingType: "story",
    rating: 91,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 91",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 30,
    hoursLabel: "28-35",
    oneCopy: "none",
    price: 389,
    verdict: "Классика 4-местного лутер-шутера. Огромная кампания, тонны оружия, кооп с самого старта.",
    storeUrl: "https://store.steampowered.com/app/49520/Borderlands_2/",
    imageUrl: steamImage(49520),
    youtubeUrl: youtube("KsNZ6eOJl0c")
  },
  {
    id: "diablo-4",
    title: "Diablo IV",
    year: 2023,
    genres: ["AAA", "Action", "RPG", "Loot", "Fantasy", "Isometric"],
    endingType: "story",
    rating: 86,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 86",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 30,
    hoursLabel: "28-35",
    oneCopy: "none",
    price: 1696,
    verdict: "Большая кампания с актами и нормальной концовкой. Онлайн-кооп на двоих работает без сюрпризов.",
    storeUrl: "https://store.steampowered.com/app/2344520/Diablo_IV/",
    imageUrl: steamImage(2344520),
    youtubeUrl: youtube("wH72EpRepWM")
  },
  {
    id: "vermintide-2",
    title: "Warhammer: Vermintide 2",
    year: 2018,
    genres: ["AA", "Action", "FPS", "Fantasy", "Horror"],
    endingType: "levels",
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 4,
    playersLabel: "до 4, миссии",
    hours: 22,
    hoursLabel: "20-25",
    oneCopy: "none",
    price: 18,
    verdict: "Кооп-резня в фэнтези. Миссии короткие, кампания развёртывается по актам и доходит до финала.",
    storeUrl: "https://store.steampowered.com/app/552500/Warhammer_Vermintide_2/",
    imageUrl: steamImage(552500),
    youtubeUrl: youtube("4VadHTHJ-K8")
  },
  {
    id: "left-4-dead-2",
    title: "Left 4 Dead 2",
    year: 2009,
    genres: ["AAA", "Shooter", "FPS", "Action", "Horror"],
    endingType: "levels",
    rating: 89,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 89",
    playersMax: 4,
    playersLabel: "до 4, кампании",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "none",
    price: 225,
    verdict: "Эталон коопа от Valve. Пять отдельных кампаний, каждая со своим финалом.",
    storeUrl: "https://store.steampowered.com/app/550/Left_4_Dead_2/",
    imageUrl: steamImage(550),
    youtubeUrl: youtube("RvMFOsm4WmU")
  },
  {
    id: "the-forest",
    title: "The Forest",
    year: 2018,
    genres: ["Indie", "Survival", "Horror", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 96,
    ratingSource: "Steam",
    ratingLabel: "Steam 96% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 15,
    hoursLabel: "12-18",
    oneCopy: "none",
    price: 279,
    verdict: "Выживание-хоррор с настоящим сюжетом и концовкой. Строй базу, исследуй пещеры.",
    storeUrl: "https://store.steampowered.com/app/242760/The_Forest/",
    imageUrl: steamImage(242760),
    youtubeUrl: youtube("62imEBDF2rE")
  },
  {
    id: "sons-of-the-forest",
    title: "Sons of the Forest",
    year: 2024,
    genres: ["Indie", "Survival", "Horror", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 86,
    ratingSource: "Steam",
    ratingLabel: "Steam 86% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 25,
    hoursLabel: "22-30",
    oneCopy: "none",
    price: 600,
    verdict: "Продолжение The Forest: карта больше, монстры жёстче. Концовка есть, кооп онлайн.",
    storeUrl: "https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/",
    imageUrl: steamImage(1326470),
    youtubeUrl: youtube("lSJSVtkhRck")
  },
  {
    id: "man-of-medan",
    title: "The Dark Pictures: Man of Medan",
    year: 2019,
    genres: ["AA", "Adventure", "Horror"],
    endingType: "story",
    rating: 71,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 71",
    playersMax: 5,
    playersLabel: "2-5, кампания",
    hours: 6,
    hoursLabel: "5-7",
    oneCopy: "friend-pass",
    price: 545,
    verdict: "Кинематографичный хоррор. Один владеет, второй заходит бесплатно через Friend's Pass.",
    storeUrl: "https://store.steampowered.com/app/1024480/The_Dark_Pictures_Anthology_Man_of_Medan/",
    imageUrl: steamImage(1024480),
    youtubeUrl: youtube("UyBYdhfAxvY")
  },
  {
    id: "magicka-2",
    title: "Magicka 2",
    year: 2015,
    genres: ["AA", "Action", "Adventure", "Fantasy", "Isometric"],
    endingType: "story",
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 74",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 369,
    verdict: "Хаотичный кооп с комбинированием элементов. Короткая, но смешная законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/238370/Magicka_2/",
    imageUrl: steamImage(238370),
    youtubeUrl: youtube("o3NQb5zvBKY")
  },
  {
    id: "peak",
    title: "PEAK",
    year: 2025,
    genres: ["Indie", "Adventure", "Action"],
    endingType: "arcade-goal",
    rating: 94,
    ratingSource: "Steam",
    ratingLabel: "Steam 94% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 5,
    hoursLabel: "3-8",
    oneCopy: "none",
    price: 98,
    verdict: "Кооп-челлендж: добраться до вершины. Не сюжет, но финал есть — каждый забег как короткая история.",
    storeUrl: "https://store.steampowered.com/app/3527290/PEAK/",
    imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3527290/31bac6b2eccf09b368f5e95ce510bae2baf3cfcd/header.jpg",
    youtubeUrl: youtube("u_vlCvsf8dg")
  },
  {
    id: "raft",
    title: "Raft",
    year: 2022,
    genres: ["Indie", "Survival", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam 92% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 30,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 430,
    verdict: "Survival на плоту с финальной сюжетной аркой. Кооп до 8 человек онлайн.",
    storeUrl: "https://store.steampowered.com/app/648800/Raft/",
    imageUrl: steamImage(648800),
    youtubeUrl: youtube("iyU4_RR0l0o")
  },
  {
    id: "broforce",
    title: "Broforce",
    year: 2015,
    genres: ["Indie", "Action", "Platformer", "Shooter"],
    endingType: "levels",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam 95% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 325,
    verdict: "Короткий мясной кооп-боевик. Кампания заканчивается, заходит на пару вечеров.",
    storeUrl: "https://store.steampowered.com/app/274190/Broforce/",
    imageUrl: steamImage(274190),
    youtubeUrl: youtube("DHmKxqMId_w")
  },
  {
    id: "castle-crashers",
    title: "Castle Crashers",
    year: 2012,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "levels",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam 95% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 229,
    verdict: "Классический beat'em up на четверых. Старый, но один из лучших коопов — прошёл и закрыл.",
    storeUrl: "https://store.steampowered.com/app/204360/Castle_Crashers/",
    imageUrl: steamImage(204360),
    youtubeUrl: youtube("Ek2Eoivlwhs")
  },
  {
    id: "cuphead",
    title: "Cuphead",
    year: 2017,
    genres: ["Indie", "Action", "Platformer", "Shooter"],
    endingType: "levels",
    rating: 93,
    ratingSource: "Steam",
    ratingLabel: "Steam 93% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Боссы и платформинг в стиле 30-х. Кооп локальный — удалённо через Remote Play.",
    storeUrl: "https://store.steampowered.com/app/268910/Cuphead/",
    imageUrl: steamImage(268910),
    youtubeUrl: youtube("Ygdm1ltqC6c")
  },
  {
    id: "tmnt-shredders-revenge",
    title: "TMNT: Shredder's Revenge",
    year: 2022,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 94,
    ratingSource: "Steam",
    ratingLabel: "Steam 94% positive",
    playersMax: 6,
    playersLabel: "до 6, кампания",
    hours: 6,
    hoursLabel: "5-7",
    oneCopy: "none",
    price: 515,
    verdict: "Бодрый beat'em up по черепашкам. Короткий, проходится за вечер-два.",
    storeUrl: "https://store.steampowered.com/app/1361510/Teenage_Mutant_Ninja_Turtles_Shredders_Revenge/",
    imageUrl: steamImage(1361510),
    youtubeUrl: youtube("RlviJbgWEEE")
  },
  {
    id: "cat-quest-2",
    title: "Cat Quest II",
    year: 2019,
    genres: ["Indie", "Action", "RPG", "Adventure", "Fantasy"],
    endingType: "story",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam 92% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Простая action-RPG про двух котов. Приятная, заканчивается, идеально без напряга.",
    storeUrl: "https://store.steampowered.com/app/914710/Cat_Quest_II/",
    imageUrl: steamImage(914710),
    youtubeUrl: youtube("RPfKh3FMk5s")
  },
  {
    id: "lovers-spacetime",
    title: "Lovers in a Dangerous Spacetime",
    year: 2015,
    genres: ["Indie", "Action", "Adventure", "Sci-fi"],
    endingType: "arcade-goal",
    rating: 90,
    ratingSource: "Steam",
    ratingLabel: "Steam 90% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 5,
    hoursLabel: "4-6",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Один космический корабль на двоих. Чистый кооп ради коопа — всё на коммуникацию.",
    storeUrl: "https://store.steampowered.com/app/252110/Lovers_in_a_Dangerous_Spacetime/",
    imageUrl: steamImage(252110),
    youtubeUrl: youtube("r9JButWd1zI")
  },
  {
    id: "children-of-morta",
    title: "Children of Morta",
    year: 2019,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "story",
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam 87% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 15,
    hoursLabel: "12-18",
    oneCopy: "none",
    price: 329,
    verdict: "Story-driven roguelite про семью защитников. В коопе работает приятно.",
    storeUrl: "https://store.steampowered.com/app/330020/Children_of_Morta/",
    imageUrl: steamImage(330020),
    youtubeUrl: youtube("Xs8wgjSBVI4")
  },
  {
    id: "full-metal-furies",
    title: "Full Metal Furies",
    year: 2018,
    genres: ["Indie", "Action", "RPG", "Adventure"],
    endingType: "story",
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam 87% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "none",
    price: 415,
    verdict: "Недооценённый кооп-экшен от создателей Rogue Legacy. Заточен под командную игру.",
    storeUrl: "https://store.steampowered.com/app/416600/Full_Metal_Furies/",
    imageUrl: steamImage(416600),
    youtubeUrl: youtube("KjUrQmHv_w0")
  },
  {
    id: "escape-academy",
    title: "Escape Academy",
    year: 2022,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 83,
    ratingSource: "Steam",
    ratingLabel: "Steam 83% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 279,
    verdict: "Эскейп-румы в виде игры. Хороший вариант, если хочется думать, а не стрелять.",
    storeUrl: "https://store.steampowered.com/app/1812090/Escape_Academy/",
    imageUrl: steamImage(1812090),
    youtubeUrl: youtube("Gowvcv6c_Bs")
  },
  {
    id: "journey-savage-planet",
    title: "Journey to the Savage Planet",
    year: 2021,
    genres: ["AA", "Adventure", "Action", "Sci-fi"],
    endingType: "story",
    rating: 84,
    ratingSource: "Steam",
    ratingLabel: "Steam 84% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "none",
    price: 635,
    verdict: "Кооп-экспедиция на странной планете. Прохождение до финала, без гриндфеста.",
    storeUrl: "https://store.steampowered.com/app/973810/Journey_To_The_Savage_Planet/",
    imageUrl: steamImage(973810),
    youtubeUrl: youtube("G6hMPSNVcJU")
  },
  {
    id: "revenge-savage-planet",
    title: "Revenge of the Savage Planet",
    year: 2025,
    genres: ["AA", "Adventure", "Action", "Sci-fi"],
    endingType: "story",
    rating: 83,
    ratingSource: "Steam",
    ratingLabel: "Steam 83% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "none",
    price: 555,
    verdict: "Прямое продолжение Journey. Кооп онлайн и split-screen — прямо в тему расширенного списка.",
    storeUrl: "https://store.steampowered.com/app/2787320/Revenge_of_the_Savage_Planet/",
    imageUrl: steamImage(2787320),
    youtubeUrl: youtube("0O-T24Mq77A")
  },
  {
    id: "trine-2",
    title: "Trine 2: Complete Story",
    year: 2013,
    genres: ["AA", "Puzzle", "Platformer", "Fantasy"],
    endingType: "story",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam 95% positive",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 9,
    hoursLabel: "8-12",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Раз есть Trine 5, логично взять и Trine 2 — самую любимую часть серии.",
    storeUrl: "https://store.steampowered.com/app/35720/Trine_2_Complete_Story/",
    imageUrl: steamImage(35720),
    youtubeUrl: youtube("yxIaDq9aKPY")
  },
  {
    id: "guacamelee-2",
    title: "Guacamelee! 2",
    year: 2018,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam 88% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "remote-play",
    price: 430,
    verdict: "Метроидвания с боями и платформингом. Локальный кооп до 4 человек.",
    storeUrl: "https://store.steampowered.com/app/534550/Guacamelee_2/",
    imageUrl: steamImage(534550),
    youtubeUrl: youtube("f-b9PJKunww")
  },
  {
    id: "risk-of-rain-2",
    title: "Risk of Rain 2",
    year: 2020,
    genres: ["Indie", "Action", "Shooter", "Sci-fi"],
    endingType: "roguelite",
    rating: 93,
    ratingSource: "Steam",
    ratingLabel: "Steam 93% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 25,
    hoursLabel: "20+, реплеи",
    oneCopy: "none",
    price: 108,
    verdict: "Рогалик-шутер: забег заканчивается финальным боссом, но это не сюжетная кампания.",
    storeUrl: "https://store.steampowered.com/app/632360/Risk_of_Rain_2/",
    imageUrl: steamImage(632360),
    youtubeUrl: youtube("qBRe2NDdN1E")
  },
  {
    id: "overcooked-all-you-can-eat",
    title: "Overcooked! All You Can Eat",
    year: 2021,
    genres: ["AA", "Puzzle", "Action"],
    endingType: "levels",
    rating: 85,
    ratingSource: "Steam",
    ratingLabel: "Steam 85% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 20,
    hoursLabel: "15-25",
    oneCopy: "remote-play",
    price: 800,
    verdict: "Party-кооп про кухню. Кампании заканчиваются, но это не приключение, а тест нервов.",
    storeUrl: "https://store.steampowered.com/app/1243830/Overcooked_All_You_Can_Eat/",
    imageUrl: steamImage(1243830),
    youtubeUrl: youtube("GS81-vvSo2U")
  },
  {
    id: "terraria",
    title: "Terraria",
    year: 2011,
    genres: ["Indie", "Survival", "Adventure", "Open World"],
    endingType: "survival-goal",
    rating: 97,
    ratingSource: "Steam",
    ratingLabel: "Steam ~97% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 50,
    hoursLabel: "40-80",
    oneCopy: "none",
    price: 225,
    verdict: "Песочница с финальной прогрессией: от Eye of Cthulhu до Moon Lord. Онлайн до 8.",
    storeUrl: "https://store.steampowered.com/app/105600/Terraria/",
    imageUrl: steamImage(105600),
    youtubeUrl: youtubeSearch("Terraria")
  },
  {
    id: "stardew-valley",
    title: "Stardew Valley",
    year: 2016,
    genres: ["Indie", "RPG", "Adventure"],
    endingType: "survival-goal",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 50,
    hoursLabel: "40+",
    oneCopy: "none",
    price: 229,
    verdict: "Жизненный сим с коопом до 8. Community Center как явная финальная цель.",
    storeUrl: "https://store.steampowered.com/app/413150/Stardew_Valley/",
    imageUrl: steamImage(413150),
    youtubeUrl: youtubeSearch("Stardew Valley")
  },
  {
    id: "magicka",
    title: "Magicka",
    year: 2011,
    genres: ["Indie", "Action", "Adventure", "Fantasy"],
    endingType: "story",
    rating: 86,
    ratingSource: "Steam",
    ratingLabel: "Steam ~86% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 8,
    hoursLabel: "6-10",
    oneCopy: "none",
    price: 249,
    verdict: "Хаотичный кооп-маг до 4. Прародитель Magicka 2.",
    storeUrl: "https://store.steampowered.com/app/42910/Magicka/",
    imageUrl: steamImage(42910),
    youtubeUrl: youtubeSearch("Magicka")
  },
  {
    id: "we-were-here",
    title: "We Were Here",
    year: 2017,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 93,
    ratingSource: "Steam",
    ratingLabel: "Steam ~93% positive",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 2,
    hoursLabel: "1-3",
    oneCopy: "none",
    price: 0,
    verdict: "Бесплатное начало серии. Двое в замке, пазлы через рацию.",
    storeUrl: "https://store.steampowered.com/app/582500/We_Were_Here/",
    imageUrl: steamImage(582500),
    youtubeUrl: youtubeSearch("We Were Here")
  },
  {
    id: "we-were-here-together",
    title: "We Were Here Together",
    year: 2019,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 6,
    hoursLabel: "4-8",
    oneCopy: "none",
    price: 108,
    verdict: "Лучшая часть серии: 4-6 часов кооп-пазлов с голосом.",
    storeUrl: "https://store.steampowered.com/app/865360/We_Were_Here_Together/",
    imageUrl: steamImage(865360),
    youtubeUrl: youtubeSearch("We Were Here Together")
  },
  {
    id: "streets-of-rage-4",
    title: "Streets of Rage 4",
    year: 2020,
    genres: ["Indie", "Action"],
    endingType: "levels",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 515,
    verdict: "Возрождение легенды. Beat'em up онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/985890/Streets_of_Rage_4/",
    imageUrl: steamImage(985890),
    youtubeUrl: youtubeSearch("Streets of Rage 4")
  },
  {
    id: "enter-the-gungeon",
    title: "Enter the Gungeon",
    year: 2016,
    genres: ["Indie", "Action", "Shooter", "Isometric"],
    endingType: "roguelite",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 25,
    hoursLabel: "20+, реплеи",
    oneCopy: "remote-play",
    price: 325,
    verdict: "Bullet-hell roguelike. Двоих через Remote Play, есть финал — The Past.",
    storeUrl: "https://store.steampowered.com/app/311690/Enter_the_Gungeon/",
    imageUrl: steamImage(311690),
    youtubeUrl: youtubeSearch("Enter the Gungeon")
  },
  {
    id: "spelunky-2",
    title: "Spelunky 2",
    year: 2020,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "roguelite",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam ~88% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 30,
    hoursLabel: "25+, реплеи",
    oneCopy: "none",
    price: 279,
    verdict: "Онлайн-кооп roguelike. Финальные маршруты до 7-1 / Cosmic Ocean.",
    storeUrl: "https://store.steampowered.com/app/418530/Spelunky_2/",
    imageUrl: steamImage(418530),
    youtubeUrl: youtubeSearch("Spelunky 2")
  },
  {
    id: "spelunky",
    title: "Spelunky",
    year: 2013,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "roguelite",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam ~88% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Оригинал. Локальный кооп + Remote Play, финальная зона Olmec.",
    storeUrl: "https://store.steampowered.com/app/239350/Spelunky/",
    imageUrl: steamImage(239350),
    youtubeUrl: youtubeSearch("Spelunky")
  },
  {
    id: "battleblock-theater",
    title: "BattleBlock Theater",
    year: 2014,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 93,
    ratingSource: "Steam",
    ratingLabel: "Steam ~93% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 8,
    hoursLabel: "6-10",
    oneCopy: "none",
    price: 229,
    verdict: "От авторов Castle Crashers. Онлайн-кооп, законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/238460/BattleBlock_Theater/",
    imageUrl: steamImage(238460),
    youtubeUrl: youtubeSearch("BattleBlock Theater")
  },
  {
    id: "lego-skywalker-saga",
    title: "LEGO Star Wars: The Skywalker Saga",
    year: 2022,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "story",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam ~88% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 50,
    hoursLabel: "40-60",
    oneCopy: "remote-play",
    price: 649,
    verdict: "Огромная LEGO-кампания: все 9 эпизодов. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/920210/LEGO_Star_Wars_The_Skywalker_Saga/",
    imageUrl: steamImage(920210),
    youtubeUrl: youtubeSearch("LEGO Star Wars Skywalker Saga")
  },
  {
    id: "lego-city-undercover",
    title: "LEGO City Undercover",
    year: 2017,
    genres: ["AAA", "Action", "Adventure", "Open World"],
    endingType: "story",
    rating: 85,
    ratingSource: "Steam",
    ratingLabel: "Steam ~85% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 25,
    hoursLabel: "20-30",
    oneCopy: "remote-play",
    price: 799,
    verdict: "Цельная LEGO-игра с открытым городом.",
    storeUrl: "https://store.steampowered.com/app/578330/LEGO_City_Undercover/",
    imageUrl: steamImage(578330),
    youtubeUrl: youtubeSearch("LEGO City Undercover")
  },
  {
    id: "lego-marvel-superheroes",
    title: "LEGO Marvel Super Heroes",
    year: 2013,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "story",
    rating: 89,
    ratingSource: "Steam",
    ratingLabel: "Steam ~89% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 20,
    hoursLabel: "18-25",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Любимая LEGO-кампания по Marvel.",
    storeUrl: "https://store.steampowered.com/app/249130/LEGO_Marvel_Super_Heroes/",
    imageUrl: steamImage(249130),
    youtubeUrl: youtubeSearch("LEGO Marvel Super Heroes")
  },
  {
    id: "a-hat-in-time",
    title: "A Hat in Time",
    year: 2017,
    genres: ["Indie", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "remote-play",
    price: 600,
    verdict: "3D-платформер с коопом. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/253230/A_Hat_in_Time/",
    imageUrl: steamImage(253230),
    youtubeUrl: youtubeSearch("A Hat in Time")
  },
  {
    id: "rayman-legends",
    title: "Rayman Legends",
    year: 2013,
    genres: ["AAA", "Action", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 15,
    hoursLabel: "12-20",
    oneCopy: "remote-play",
    price: 299,
    verdict: "Один из лучших кооп-платформеров. До 4 локально.",
    storeUrl: "https://store.steampowered.com/app/242550/Rayman_Legends/",
    imageUrl: steamImage(242550),
    youtubeUrl: youtubeSearch("Rayman Legends")
  },
  {
    id: "rayman-origins",
    title: "Rayman Origins",
    year: 2012,
    genres: ["AAA", "Action", "Platformer", "Adventure"],
    endingType: "levels",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "remote-play",
    price: 150,
    verdict: "Предшественник Legends. Локальный кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/207490/Rayman_Origins/",
    imageUrl: steamImage(207490),
    youtubeUrl: youtubeSearch("Rayman Origins")
  },
  {
    id: "sackboy-big-adventure",
    title: "Sackboy: A Big Adventure",
    year: 2022,
    genres: ["AAA", "Action", "Platformer", "Adventure"],
    endingType: "story",
    rating: 81,
    ratingSource: "Steam",
    ratingLabel: "Steam ~81% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 15,
    hoursLabel: "12-20",
    oneCopy: "none",
    price: 1699,
    verdict: "LittleBigPlanet-наследник. Локальный + онлайн кооп. Дорогой без скидки.",
    storeUrl: "https://store.steampowered.com/app/1599660/Sackboy_A_Big_Adventure/",
    imageUrl: steamImage(1599660),
    youtubeUrl: youtubeSearch("Sackboy A Big Adventure")
  },
  {
    id: "orcs-must-die-2",
    title: "Orcs Must Die! 2",
    year: 2012,
    genres: ["AA", "Action", "Tactics", "Fantasy"],
    endingType: "levels",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 15,
    hoursLabel: "12-20",
    oneCopy: "none",
    price: 229,
    verdict: "Классика action tower defense. Онлайн-кампания на двоих.",
    storeUrl: "https://store.steampowered.com/app/201790/Orcs_Must_Die_2/",
    imageUrl: steamImage(201790),
    youtubeUrl: youtubeSearch("Orcs Must Die 2")
  },
  {
    id: "dungeon-defenders",
    title: "Dungeon Defenders",
    year: 2011,
    genres: ["AA", "Action", "Tactics", "RPG", "Fantasy"],
    endingType: "levels",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam ~80% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 25,
    hoursLabel: "20+",
    oneCopy: "none",
    price: 325,
    verdict: "Action tower defense с RPG-прогрессией. До 4 онлайн.",
    storeUrl: "https://store.steampowered.com/app/65800/Dungeon_Defenders/",
    imageUrl: steamImage(65800),
    youtubeUrl: youtubeSearch("Dungeon Defenders")
  },
  {
    id: "sanctum-2",
    title: "Sanctum 2",
    year: 2013,
    genres: ["AA", "Shooter", "FPS", "Tactics", "Sci-fi"],
    endingType: "levels",
    rating: 79,
    ratingSource: "Steam",
    ratingLabel: "Steam ~79% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "none",
    price: 409,
    verdict: "FPS-tower defense. Онлайн-кампания до 4.",
    storeUrl: "https://store.steampowered.com/app/210770/Sanctum_2/",
    imageUrl: steamImage(210770),
    youtubeUrl: youtubeSearch("Sanctum 2")
  },
  {
    id: "world-war-z",
    title: "World War Z: Aftermath",
    year: 2021,
    genres: ["AA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam ~80% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 15,
    hoursLabel: "12-20",
    oneCopy: "none",
    price: 187,
    verdict: "Эпизодная кооп-кампания против зомби-волн. До 4 онлайн.",
    storeUrl: "https://store.steampowered.com/app/699130/World_War_Z_Aftermath/",
    imageUrl: steamImage(699130),
    youtubeUrl: youtubeSearch("World War Z Aftermath")
  },
  {
    id: "zombie-army-trilogy",
    title: "Zombie Army Trilogy",
    year: 2015,
    genres: ["AA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam ~80% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 15,
    hoursLabel: "12-18",
    oneCopy: "none",
    price: 529,
    verdict: "Sniper Elite в зомби-сеттинге. Кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/301640/Zombie_Army_Trilogy/",
    imageUrl: steamImage(301640),
    youtubeUrl: youtubeSearch("Zombie Army Trilogy")
  },
  {
    id: "serious-sam-3",
    title: "Serious Sam 3: BFE",
    year: 2011,
    genres: ["AA", "Shooter", "FPS", "Action", "Sci-fi"],
    endingType: "story",
    rating: 85,
    ratingSource: "Steam",
    ratingLabel: "Steam ~85% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 15,
    hoursLabel: "12-18",
    oneCopy: "none",
    price: 600,
    verdict: "Олдскульный FPS с кооп-кампанией до 4.",
    storeUrl: "https://store.steampowered.com/app/41070/Serious_Sam_3_BFE/",
    imageUrl: steamImage(41070),
    youtubeUrl: youtubeSearch("Serious Sam 3 BFE")
  },
  {
    id: "serious-sam-4",
    title: "Serious Sam 4",
    year: 2020,
    genres: ["AA", "Shooter", "FPS", "Action", "Sci-fi"],
    endingType: "story",
    rating: 76,
    ratingSource: "Steam",
    ratingLabel: "Steam ~76% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 20,
    hoursLabel: "16-22",
    oneCopy: "none",
    price: 740,
    verdict: "Современный Serious Sam с кооп-кампанией.",
    storeUrl: "https://store.steampowered.com/app/257420/Serious_Sam_4/",
    imageUrl: steamImage(257420),
    youtubeUrl: youtubeSearch("Serious Sam 4")
  },
  {
    id: "alien-swarm-reactive-drop",
    title: "Alien Swarm: Reactive Drop",
    year: 2017,
    genres: ["Indie", "Shooter", "Action", "Sci-fi", "Horror", "Isometric"],
    endingType: "levels",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 4,
    playersLabel: "до 4, миссии",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "none",
    price: 0,
    verdict: "Бесплатная top-down кооп-миссионка. Очевидное добавление.",
    storeUrl: "https://store.steampowered.com/app/563560/Alien_Swarm_Reactive_Drop/",
    imageUrl: steamImage(563560),
    youtubeUrl: youtubeSearch("Alien Swarm Reactive Drop")
  },
  {
    id: "powerwash-simulator",
    title: "PowerWash Simulator",
    year: 2022,
    genres: ["Indie", "Adventure", "Puzzle"],
    endingType: "levels",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 6,
    playersLabel: "до 6",
    hours: 25,
    hoursLabel: "20-40",
    oneCopy: "none",
    price: 500,
    verdict: "Симулятор мойки. Career-режим с финитными работами.",
    storeUrl: "https://store.steampowered.com/app/1290000/PowerWash_Simulator/",
    imageUrl: steamImage(1290000),
    youtubeUrl: youtubeSearch("PowerWash Simulator")
  },
  {
    id: "teardown",
    title: "Teardown",
    year: 2022,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "story",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 12,
    playersLabel: "до 12, кампания",
    hours: 15,
    hoursLabel: "12-20",
    oneCopy: "none",
    price: 649,
    verdict: "Voxel-разрушение. Кооп-кампания добавлена в 2026.",
    storeUrl: "https://store.steampowered.com/app/1167630/Teardown/",
    imageUrl: steamImage(1167630),
    youtubeUrl: youtubeSearch("Teardown")
  },
  {
    id: "human-fall-flat",
    title: "Human Fall Flat",
    year: 2016,
    genres: ["Indie", "Puzzle", "Adventure", "Platformer"],
    endingType: "levels",
    rating: 89,
    ratingSource: "Steam",
    ratingLabel: "Steam ~89% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 8,
    hoursLabel: "6-12",
    oneCopy: "none",
    price: 279,
    verdict: "Physics-кооп до 8. Уровни проходятся.",
    storeUrl: "https://store.steampowered.com/app/477160/Human_Fall_Flat/",
    imageUrl: steamImage(477160),
    youtubeUrl: youtubeSearch("Human Fall Flat")
  },
  {
    id: "for-the-king",
    title: "For The King",
    year: 2018,
    genres: ["Indie", "RPG", "Tactics", "Adventure", "Fantasy"],
    endingType: "roguelite",
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam ~87% positive",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 30,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 279,
    verdict: "Настольная roguelite-RPG. Онлайн-кампания.",
    storeUrl: "https://store.steampowered.com/app/527230/For_The_King/",
    imageUrl: steamImage(527230),
    youtubeUrl: youtubeSearch("For The King")
  },
  {
    id: "streets-of-rogue",
    title: "Streets of Rogue",
    year: 2019,
    genres: ["Indie", "Action", "RPG", "Adventure", "Isometric"],
    endingType: "roguelite",
    rating: 90,
    ratingSource: "Steam",
    ratingLabel: "Steam ~90% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 20,
    hoursLabel: "15-30",
    oneCopy: "none",
    price: 415,
    verdict: "Roguelite immersive sim. Пройти город онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/512900/Streets_of_Rogue/",
    imageUrl: steamImage(512900),
    youtubeUrl: youtubeSearch("Streets of Rogue")
  },
  {
    id: "nuclear-throne",
    title: "Nuclear Throne",
    year: 2015,
    genres: ["Indie", "Action", "Shooter"],
    endingType: "roguelite",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "remote-play",
    price: 199,
    verdict: "Twin-stick roguelike. Локальный кооп + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/242680/Nuclear_Throne/",
    imageUrl: steamImage(242680),
    youtubeUrl: youtubeSearch("Nuclear Throne")
  },
  {
    id: "binding-of-isaac-rebirth",
    title: "The Binding of Isaac: Rebirth",
    year: 2014,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "roguelite",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 50,
    hoursLabel: "40+",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Roguelite в подвалах с боссами-эндингами. Локальный кооп до 4.",
    storeUrl: "https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/",
    imageUrl: steamImage(250900),
    youtubeUrl: youtubeSearch("Binding of Isaac Rebirth")
  },
  {
    id: "keywe",
    title: "KeyWe",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "levels",
    rating: 86,
    ratingSource: "Steam",
    ratingLabel: "Steam ~86% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 329,
    verdict: "Милая кооп-почта про птичек-киви. Онлайн на двоих.",
    storeUrl: "https://store.steampowered.com/app/1242980/KeyWe/",
    imageUrl: steamImage(1242980),
    youtubeUrl: youtubeSearch("KeyWe")
  },
  {
    id: "moving-out",
    title: "Moving Out",
    year: 2020,
    genres: ["Indie", "Puzzle", "Action"],
    endingType: "levels",
    rating: 89,
    ratingSource: "Steam",
    ratingLabel: "Steam ~89% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "remote-play",
    price: 419,
    verdict: "Кооп-грузчики в духе Overcooked. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/996770/Moving_Out/",
    imageUrl: steamImage(996770),
    youtubeUrl: youtubeSearch("Moving Out")
  },
  {
    id: "roboquest",
    title: "Roboquest",
    year: 2023,
    genres: ["Indie", "Action", "Shooter", "FPS", "Sci-fi"],
    endingType: "roguelite",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 20,
    hoursLabel: "15+",
    oneCopy: "none",
    price: 390,
    verdict: "FPS-roguelike с финалом забега. Онлайн на двоих.",
    storeUrl: "https://store.steampowered.com/app/692890/Roboquest/",
    imageUrl: steamImage(692890),
    youtubeUrl: youtubeSearch("Roboquest")
  },
  {
    id: "gunfire-reborn",
    title: "Gunfire Reborn",
    year: 2021,
    genres: ["Indie", "Action", "Shooter", "FPS"],
    endingType: "roguelite",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 25,
    hoursLabel: "20+, реплеи",
    oneCopy: "none",
    price: 399,
    verdict: "FPS-roguelite до 4 с финальным боссом забега.",
    storeUrl: "https://store.steampowered.com/app/1217060/Gunfire_Reborn/",
    imageUrl: steamImage(1217060),
    youtubeUrl: youtubeSearch("Gunfire Reborn")
  },
  {
    id: "ravenswatch",
    title: "Ravenswatch",
    year: 2024,
    genres: ["AA", "Action", "RPG", "Fantasy", "Isometric"],
    endingType: "roguelite",
    rating: 85,
    ratingSource: "Steam",
    ratingLabel: "Steam ~85% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 20,
    hoursLabel: "15-30",
    oneCopy: "none",
    price: 460,
    verdict: "Roguelite от Curse of the Dead Gods. Онлайн-кооп.",
    storeUrl: "https://store.steampowered.com/app/2071280/Ravenswatch/",
    imageUrl: steamImage(2071280),
    youtubeUrl: youtubeSearch("Ravenswatch")
  },
  {
    id: "wizard-of-legend",
    title: "Wizard of Legend",
    year: 2018,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "roguelite",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam ~88% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "remote-play",
    price: 239,
    verdict: "Заклинательский roguelite. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/445980/Wizard_of_Legend/",
    imageUrl: steamImage(445980),
    youtubeUrl: youtubeSearch("Wizard of Legend")
  },
  {
    id: "death-road-to-canada",
    title: "Death Road to Canada",
    year: 2016,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "roguelite",
    rating: 89,
    ratingSource: "Steam",
    ratingLabel: "Steam ~89% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 8,
    hoursLabel: "6-12",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Roguelite roadtrip. Доехать до Канады, локально до 4.",
    storeUrl: "https://store.steampowered.com/app/252610/Death_Road_to_Canada/",
    imageUrl: steamImage(252610),
    youtubeUrl: youtubeSearch("Death Road to Canada")
  },
  {
    id: "kane-lynch-2",
    title: "Kane & Lynch 2: Dog Days",
    year: 2010,
    genres: ["AAA", "Shooter", "Third-person", "Action"],
    endingType: "story",
    rating: 65,
    ratingSource: "Steam",
    ratingLabel: "Steam ~65% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 6,
    hoursLabel: "5-7",
    oneCopy: "none",
    price: 169,
    verdict: "Грязный криминальный кооп-боевик. Прямой родственник Army of Two.",
    storeUrl: "https://store.steampowered.com/app/28000/Kane__Lynch_2_Dog_Days/",
    imageUrl: steamImage(28000),
    youtubeUrl: youtubeSearch("Kane Lynch 2 Dog Days")
  },
  {
    id: "towerfall-ascension",
    title: "TowerFall Ascension",
    year: 2014,
    genres: ["Indie", "Action", "Platformer"],
    endingType: "arcade-goal",
    rating: 94,
    ratingSource: "Steam",
    ratingLabel: "Steam ~94% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 8,
    hoursLabel: "6-12",
    oneCopy: "remote-play",
    price: 289,
    verdict: "PvP + кооп Quest Mode и Dark World. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/251470/TowerFall_Ascension/",
    imageUrl: steamImage(251470),
    youtubeUrl: youtubeSearch("TowerFall Ascension")
  },
  {
    id: "capcom-beat-em-up-bundle",
    title: "Capcom Beat 'Em Up Bundle",
    year: 2018,
    genres: ["AAA", "Action", "Adventure"],
    endingType: "levels",
    rating: 84,
    ratingSource: "Steam",
    ratingLabel: "Steam ~84% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 8,
    hoursLabel: "6-12",
    oneCopy: "none",
    price: 649,
    verdict: "Сборник 7 классических beat'em up'ов Capcom. Онлайн.",
    storeUrl: "https://store.steampowered.com/app/885150/Capcom_Beat_Em_Up_Bundle/",
    imageUrl: steamImage(885150),
    youtubeUrl: youtubeSearch("Capcom Beat Em Up Bundle")
  },
  {
    id: "metal-slug-3",
    title: "METAL SLUG 3",
    year: 2014,
    genres: ["AAA", "Action", "Shooter", "Platformer"],
    endingType: "levels",
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam ~87% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 4,
    hoursLabel: "2-5",
    oneCopy: "remote-play",
    price: 149,
    verdict: "Самая известная Metal Slug. Локально + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/250180/METAL_SLUG_3/",
    imageUrl: steamImage(250180),
    youtubeUrl: youtubeSearch("METAL SLUG 3")
  },
  {
    id: "monaco",
    title: "Monaco: What's Yours Is Mine",
    year: 2013,
    genres: ["Indie", "Action", "Adventure", "Stealth", "Isometric"],
    endingType: "levels",
    rating: 85,
    ratingSource: "Steam",
    ratingLabel: "Steam ~85% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "none",
    price: 229,
    verdict: "Кооп-ограбления top-down. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/113020/Monaco_Whats_Yours_Is_Mine/",
    imageUrl: steamImage(113020),
    youtubeUrl: youtubeSearch("Monaco Whats Yours Is Mine")
  },
  {
    id: "the-cave",
    title: "The Cave",
    year: 2013,
    genres: ["AA", "Puzzle", "Adventure", "Platformer"],
    endingType: "story",
    rating: 75,
    ratingSource: "Steam",
    ratingLabel: "Steam ~75% positive",
    playersMax: 3,
    playersLabel: "до 3, локально",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Приключенческая головоломка от Рона Гилберта. Локально до 3.",
    storeUrl: "https://store.steampowered.com/app/221810/The_Cave/",
    imageUrl: steamImage(221810),
    youtubeUrl: youtubeSearch("The Cave")
  },
  {
    id: "20xx",
    title: "20XX",
    year: 2017,
    genres: ["Indie", "Action", "Platformer"],
    endingType: "roguelite",
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam ~87% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "none",
    price: 229,
    verdict: "Mega Man-like roguelite. Онлайн на двоих.",
    storeUrl: "https://store.steampowered.com/app/322110/20XX/",
    imageUrl: steamImage(322110),
    youtubeUrl: youtubeSearch("20XX")
  },
  {
    id: "vagante",
    title: "Vagante",
    year: 2018,
    genres: ["Indie", "Action", "RPG", "Platformer", "Fantasy"],
    endingType: "roguelite",
    rating: 86,
    ratingSource: "Steam",
    ratingLabel: "Steam ~86% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 12,
    hoursLabel: "10-20",
    oneCopy: "none",
    price: 229,
    verdict: "Roguelike-платформер. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/323220/Vagante/",
    imageUrl: steamImage(323220),
    youtubeUrl: youtubeSearch("Vagante")
  },
  {
    id: "barony",
    title: "Barony",
    year: 2015,
    genres: ["Indie", "Action", "RPG", "Fantasy"],
    endingType: "roguelite",
    rating: 82,
    ratingSource: "Steam",
    ratingLabel: "Steam ~82% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 20,
    hoursLabel: "15-30",
    oneCopy: "none",
    price: 415,
    verdict: "First-person dungeon roguelike. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/371970/Barony/",
    imageUrl: steamImage(371970),
    youtubeUrl: youtubeSearch("Barony")
  },
  {
    id: "across-the-obelisk",
    title: "Across the Obelisk",
    year: 2021,
    genres: ["Indie", "RPG", "Tactics", "Adventure", "Fantasy"],
    endingType: "roguelite",
    rating: 90,
    ratingSource: "Steam",
    ratingLabel: "Steam ~90% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 30,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 489,
    verdict: "Карточный roguelite в актах. Онлайн-кампания.",
    storeUrl: "https://store.steampowered.com/app/1385380/Across_the_Obelisk/",
    imageUrl: steamImage(1385380),
    youtubeUrl: youtubeSearch("Across the Obelisk")
  },
  {
    id: "escape-simulator",
    title: "Escape Simulator",
    year: 2021,
    genres: ["Indie", "Puzzle", "Adventure"],
    endingType: "arcade-goal",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 6,
    playersLabel: "до 6",
    hours: 10,
    hoursLabel: "8-15",
    oneCopy: "none",
    price: 399,
    verdict: "Кооп escape room с комнатами и DLC-кампаниями. Онлайн до 6.",
    storeUrl: "https://store.steampowered.com/app/1435790/Escape_Simulator/",
    imageUrl: steamImage(1435790),
    youtubeUrl: youtubeSearch("Escape Simulator")
  },
  {
    id: "keep-talking-nobody-explodes",
    title: "Keep Talking and Nobody Explodes",
    year: 2015,
    genres: ["Indie", "Puzzle"],
    endingType: "arcade-goal",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 2,
    playersLabel: "2, асимметрично",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "friend-pass",
    price: 325,
    verdict: "Один обезвреживает бомбу, второй читает мануал. Одной копии достаточно.",
    storeUrl: "https://store.steampowered.com/app/341800/Keep_Talking_and_Nobody_Explodes/",
    imageUrl: steamImage(341800),
    youtubeUrl: youtubeSearch("Keep Talking and Nobody Explodes")
  },
  {
    id: "remnant-1",
    title: "Remnant: From the Ashes",
    year: 2019,
    genres: ["AA", "Shooter", "Third-person", "Action", "RPG", "Soulslike"],
    endingType: "story",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam ~80% positive",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 25,
    hoursLabel: "20-30",
    oneCopy: "none",
    price: 479,
    verdict: "Soulslike с пушками. Предшественник Remnant II.",
    storeUrl: "https://store.steampowered.com/app/617290/Remnant_From_the_Ashes/",
    imageUrl: steamImage(617290),
    youtubeUrl: youtubeSearch("Remnant From the Ashes")
  },
  {
    id: "dead-island-de",
    title: "Dead Island Definitive Edition",
    year: 2016,
    genres: ["AAA", "Action", "FPS", "RPG", "Open World", "Horror"],
    endingType: "story",
    rating: 77,
    ratingSource: "Steam",
    ratingLabel: "Steam ~77% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 20,
    hoursLabel: "16-25",
    oneCopy: "none",
    price: 533,
    verdict: "Зомби-боевик с кооп-кампанией до 4.",
    storeUrl: "https://store.steampowered.com/app/383150/Dead_Island_Definitive_Edition/",
    imageUrl: steamImage(383150),
    youtubeUrl: youtubeSearch("Dead Island Definitive Edition")
  },
  {
    id: "portal-knights",
    title: "Portal Knights",
    year: 2017,
    genres: ["AA", "Action", "RPG", "Adventure", "Fantasy"],
    endingType: "survival-goal",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam ~80% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 30,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 279,
    verdict: "Voxel-Minecraft с боссами и прогрессией. Кооп локально/онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/374040/Portal_Knights/",
    imageUrl: steamImage(374040),
    youtubeUrl: youtubeSearch("Portal Knights")
  },
  {
    id: "chained-together",
    title: "Chained Together",
    year: 2024,
    genres: ["Indie", "Adventure", "Action"],
    endingType: "arcade-goal",
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam ~87% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 5,
    hoursLabel: "3-8",
    oneCopy: "none",
    price: 124,
    verdict: "Кооп-восхождение скованными цепью. Добраться до вершины.",
    storeUrl: "https://store.steampowered.com/app/2567870/Chained_Together/",
    imageUrl: steamImage(2567870),
    youtubeUrl: youtubeSearch("Chained Together")
  },
  {
    id: "pico-park",
    title: "PICO PARK",
    year: 2021,
    genres: ["Indie", "Puzzle", "Platformer"],
    endingType: "levels",
    rating: 91,
    ratingSource: "Steam",
    ratingLabel: "Steam ~91% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 3,
    hoursLabel: "2-5",
    oneCopy: "none",
    price: 99,
    verdict: "Простые кооп-уровни до 8 человек. Минималистично и хорошо.",
    storeUrl: "https://store.steampowered.com/app/1509960/PICO_PARK/",
    imageUrl: steamImage(1509960),
    youtubeUrl: youtubeSearch("PICO PARK")
  },
  {
    id: "road-redemption",
    title: "Road Redemption",
    year: 2017,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam ~80% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 8,
    hoursLabel: "6-12",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Road Rash-наследник. Локальный split-screen + Remote Play.",
    storeUrl: "https://store.steampowered.com/app/300380/Road_Redemption/",
    imageUrl: steamImage(300380),
    youtubeUrl: youtubeSearch("Road Redemption")
  },
  {
    id: "edf-4-1",
    title: "Earth Defense Force 4.1",
    year: 2016,
    genres: ["AA", "Shooter", "Action", "Sci-fi"],
    endingType: "levels",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam ~88% positive",
    playersMax: 4,
    playersLabel: "до 4, миссии",
    hours: 50,
    hoursLabel: "40+",
    oneCopy: "none",
    price: 279,
    verdict: "Орды гигантских жуков. Онлайн-миссии до 4.",
    storeUrl: "https://store.steampowered.com/app/410320/EARTH_DEFENSE_FORCE_41_The_Shadow_of_New_Despair/",
    imageUrl: steamImage(410320),
    youtubeUrl: youtubeSearch("Earth Defense Force 4.1")
  },
  {
    id: "assault-android-cactus",
    title: "Assault Android Cactus+",
    year: 2015,
    genres: ["Indie", "Action", "Shooter"],
    endingType: "levels",
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam ~88% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 6,
    hoursLabel: "4-8",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Twin-stick кампания. Локально до 4.",
    storeUrl: "https://store.steampowered.com/app/250110/Assault_Android_Cactus/",
    imageUrl: steamImage(250110),
    youtubeUrl: youtubeSearch("Assault Android Cactus")
  },
  {
    id: "fightn-rage",
    title: "Fight'N Rage",
    year: 2017,
    genres: ["Indie", "Action", "Adventure"],
    endingType: "levels",
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam ~95% positive",
    playersMax: 3,
    playersLabel: "до 3, локально",
    hours: 5,
    hoursLabel: "4-8",
    oneCopy: "remote-play",
    price: 415,
    verdict: "Современный beat'em up в духе 90-х. Локально до 3.",
    storeUrl: "https://store.steampowered.com/app/674520/FightN_Rage/",
    imageUrl: steamImage(674520),
    youtubeUrl: youtubeSearch("FightN Rage")
  },
  {
    id: "door-kickers-action-squad",
    title: "Door Kickers: Action Squad",
    year: 2018,
    genres: ["Indie", "Action", "Shooter", "Tactics"],
    endingType: "levels",
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam ~92% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 15,
    hoursLabel: "12-20",
    oneCopy: "none",
    price: 310,
    verdict: "Тактический пиксельный shooter. Онлайн до 4.",
    storeUrl: "https://store.steampowered.com/app/686200/Door_Kickers_Action_Squad/",
    imageUrl: steamImage(686200),
    youtubeUrl: youtubeSearch("Door Kickers Action Squad")
  },
  {
    id: "a-way-out",
    title: "A Way Out",
    year: 2018,
    genres: ["AA", "Action", "Adventure", "Third-person"],
    endingType: "story",
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 6,
    hoursLabel: "6",
    oneCopy: "friend-pass",
    price: 799,
    verdict: "Спрятано: уже пройдено. Полностью построено вокруг дуо.",
    storeUrl: "https://store.steampowered.com/app/1222700/A_Way_Out/",
    imageUrl: steamImage(1222700),
    youtubeUrl: youtube("87HIFtmB948"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "it-takes-two",
    title: "It Takes Two",
    year: 2021,
    genres: ["AA", "Action", "Adventure", "Puzzle", "Platformer"],
    endingType: "story",
    rating: 89,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 89",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 12,
    hoursLabel: "11-14",
    oneCopy: "friend-pass",
    price: 999,
    verdict: "Спрятано: уже пройдено. Friend's Pass закрывает покупку второй копии.",
    storeUrl: "https://store.steampowered.com/app/1426210/It_Takes_Two/",
    imageUrl: steamImage(1426210),
    youtubeUrl: youtube("SPa5JXzPaAk"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "split-fiction",
    title: "Split Fiction",
    year: 2025,
    genres: ["AA", "Action", "Adventure", "Platformer", "Sci-fi", "Fantasy"],
    endingType: "story",
    rating: 91,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 91",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 15,
    hoursLabel: "14-16",
    oneCopy: "friend-pass",
    price: 1299,
    verdict: "Спрятано: уже пройдено. Эталонная проверка поля Friend Pass.",
    storeUrl: "https://store.steampowered.com/app/2001120/Split_Fiction/",
    imageUrl: steamImage(2001120),
    youtubeUrl: youtube("fcwngWPXQtg"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "resident-evil-5",
    title: "Resident Evil 5",
    year: 2009,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 86,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 86",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 649,
    verdict: "Спрятано: уже пройдено. Классический кооп-боевик Capcom.",
    storeUrl: "https://store.steampowered.com/app/21690/Resident_Evil_5/",
    imageUrl: steamImage(21690),
    youtubeUrl: youtube("qUsTgI0cs4c"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "resident-evil-6",
    title: "Resident Evil 6",
    year: 2013,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Horror"],
    endingType: "story",
    rating: 69,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 69",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 21,
    hoursLabel: "20-22",
    oneCopy: "none",
    price: 649,
    verdict: "Спрятано: уже пройдено. Много кампаний, много хаоса, спорная репутация.",
    storeUrl: "https://store.steampowered.com/app/221040/Resident_Evil_6/",
    imageUrl: steamImage(221040),
    youtubeUrl: youtube("mI6TntXFfZY"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "dead-space-3",
    title: "Dead Space 3",
    year: 2013,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Horror", "Sci-fi"],
    endingType: "story",
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "11-13",
    oneCopy: "none",
    price: 699,
    verdict: "Спрятано: уже пройдено. Кооп сильнее меняет тон игры, чем в первых двух частях.",
    storeUrl: "https://store.steampowered.com/app/1238060/Dead_Space_3/",
    imageUrl: steamImage(1238060),
    youtubeUrl: youtube("cZ3mad7SOBg"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "army-of-two",
    title: "Army of Two",
    year: 2008,
    genres: ["AAA", "Shooter", "Third-person", "Action", "Military"],
    endingType: "story",
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic console 74",
    playersMax: 2,
    playersLabel: "2",
    hours: 7,
    hoursLabel: "6-8",
    oneCopy: "none",
    price: 0,
    verdict: "Спрятано: уже пройдено и оставлено как референс. Не является активным PC-кандидатом.",
    storeUrl: "https://en.wikipedia.org/wiki/Army_of_Two_(video_game)",
    imageUrl: "https://i.ytimg.com/vi/WbggbjbHphA/hqdefault.jpg",
    youtubeUrl: youtube("WbggbjbHphA"),
    hidden: true,
    hiddenReason: "Уже играли / референс"
  }
];
