const steamImage = (appId) => `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;
const youtube = (id) => `https://www.youtube.com/watch?v=${id}`;

window.GAMES = [
  {
    id: "gears-of-war-reloaded",
    title: "Gears of War: Reloaded",
    year: 2025,
    genres: ["Shooter", "Third-person", "Action"],
    rating: 79,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 79",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 8.5,
    hoursLabel: "7-10",
    oneCopy: "none",
    price: 1299,
    verdict: "Самый прямой наследник ощущения Army of Two: укрытия, мясо, дуо.",
    storeUrl: "https://store.steampowered.com/app/2523720/Gears_of_War_Reloaded/",
    imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2523720/779c1934da3b39c307d91195ff764502f2ce1063/capsule_616x353.jpg",
    youtubeUrl: youtube("UHg5MMnsMJ4")
  },
  {
    id: "space-marine-2",
    title: "Warhammer 40,000: Space Marine 2",
    year: 2024,
    genres: ["Shooter", "Third-person", "Action", "Sci-fi"],
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 11,
    hoursLabel: "10-12",
    oneCopy: "none",
    price: 1299,
    verdict: "Очень жирный современный кооп-экшен. Не про укрытия, а про продавить всё силой.",
    storeUrl: "https://store.steampowered.com/app/2183900/Warhammer_40000_Space_Marine_2/",
    imageUrl: steamImage(2183900),
    youtubeUrl: youtube("_5qGL9IK-XY")
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    year: 2023,
    genres: ["RPG", "Tactics", "Fantasy"],
    rating: 96,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 96",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 85,
    hoursLabel: "80+",
    oneCopy: "none",
    price: 899,
    verdict: "Лучший вариант, если окей пошаговая ролевая игра и большая законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
    imageUrl: steamImage(1086940),
    youtubeUrl: youtube("UxSgaBXMqP4")
  },
  {
    id: "remnant-2",
    title: "Remnant II",
    year: 2023,
    genres: ["Shooter", "Action", "RPG", "Soulslike"],
    rating: 80,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 80",
    playersMax: 3,
    playersLabel: "до 3",
    hours: 22,
    hoursLabel: "18-25",
    oneCopy: "none",
    price: 1299,
    verdict: "Dark Souls с пушками. Кампания конечная, но игра любит повторные прохождения и лут.",
    storeUrl: "https://store.steampowered.com/app/1282100/REMNANT_II/",
    imageUrl: steamImage(1282100),
    youtubeUrl: youtube("x3ZheAh5oPc")
  },
  {
    id: "trine-5",
    title: "Trine 5: A Clockwork Conspiracy",
    year: 2023,
    genres: ["Puzzle", "Platformer", "Fantasy"],
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 78",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 13,
    hoursLabel: "12-14",
    oneCopy: "remote-play",
    price: 600,
    verdict: "Кооп-пазлы и платформинг. Не AAA, но аккуратная законченная игра.",
    storeUrl: "https://store.steampowered.com/app/1436700/Trine_5_A_Clockwork_Conspiracy/",
    imageUrl: steamImage(1436700),
    youtubeUrl: youtube("MDCcvLZVEnM")
  },
  {
    id: "sniper-elite-5",
    title: "Sniper Elite 5",
    year: 2022,
    genres: ["Shooter", "Stealth", "Tactics", "Military"],
    rating: 79,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 79",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "none",
    price: 579,
    verdict: "Медленнее Army of Two: стелс, снайпинг, тактика. Вдвоём работает хорошо.",
    storeUrl: "https://store.steampowered.com/app/1029690/Sniper_Elite_5/",
    imageUrl: steamImage(1029690),
    youtubeUrl: youtube("uG8LCpWPZlg")
  },
  {
    id: "we-were-here-forever",
    title: "We Were Here Forever",
    year: 2022,
    genres: ["Puzzle", "Adventure"],
    rating: 56,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 56% рекомендуют",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 375,
    verdict: "Пазл-кооп с голосовой связью. Не экшен, но именно игра для двоих.",
    storeUrl: "https://store.steampowered.com/app/1341290/We_Were_Here_Forever/",
    imageUrl: steamImage(1341290),
    youtubeUrl: youtube("YeNCUS_Cdas")
  },
  {
    id: "operation-tango",
    title: "Operation: Tango",
    year: 2021,
    genres: ["Puzzle", "Adventure"],
    rating: 76,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 76",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 4,
    hoursLabel: "3-5",
    oneCopy: "friend-pass",
    price: 415,
    verdict: "Асимметричный шпионский кооп: один агент, второй хакер. Короткая, зато честно сделана под двух игроков.",
    storeUrl: "https://store.steampowered.com/app/1335790/Operation_Tango/",
    imageUrl: steamImage(1335790),
    youtubeUrl: youtube("CIJZ2tfW__8")
  },
  {
    id: "the-ascent",
    title: "The Ascent",
    year: 2021,
    genres: ["Shooter", "Action", "RPG", "Sci-fi", "Isometric"],
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 74",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 14,
    hoursLabel: "12-16",
    oneCopy: "remote-play",
    price: 635,
    verdict: "Киберпанк twin-stick шутер. Красивый, но сюжет не главный козырь.",
    storeUrl: "https://store.steampowered.com/app/979690/The_Ascent/",
    imageUrl: steamImage(979690),
    youtubeUrl: youtube("vXUTYzj_bKE")
  },
  {
    id: "outriders",
    title: "Outriders",
    year: 2021,
    genres: ["Shooter", "Action", "RPG", "Loot", "Sci-fi"],
    rating: 73,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 73",
    playersMax: 3,
    playersLabel: "до 3",
    hours: 20,
    hoursLabel: "16-25",
    oneCopy: "none",
    price: 499,
    verdict: "Кампания есть и заканчивается, но это лутер-шутер. Брать, если окей гриндовая ДНК.",
    storeUrl: "https://store.steampowered.com/app/680420/OUTRIDERS/",
    imageUrl: steamImage(680420),
    youtubeUrl: youtube("S8TaAcA0_Ug")
  },
  {
    id: "wasteland-3",
    title: "Wasteland 3",
    year: 2020,
    genres: ["RPG", "Tactics"],
    rating: 85,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 85",
    playersMax: 2,
    playersLabel: "2",
    hours: 50,
    hoursLabel: "45-60",
    oneCopy: "none",
    price: 479,
    verdict: "Пошаговая ролевая игра с нормальным сюжетом и решениями. Хороший кооп, если хочется не шутер.",
    storeUrl: "https://store.steampowered.com/app/719040/Wasteland_3/",
    imageUrl: steamImage(719040),
    youtubeUrl: youtube("4XY4BAtJuow")
  },
  {
    id: "gears-5",
    title: "Gears 5",
    year: 2019,
    genres: ["Shooter", "Third-person", "Action", "Sci-fi"],
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 11,
    hoursLabel: "10-12",
    oneCopy: "none",
    price: 760,
    verdict: "Один из лучших вариантов под запрос: AAA, сюжет, экшен, можно проходить вдвоём.",
    storeUrl: "https://store.steampowered.com/app/1097840/Gears_5/",
    imageUrl: steamImage(1097840),
    youtubeUrl: youtube("yxnXis9OV_E")
  },
  {
    id: "halo-mcc",
    title: "Halo: The Master Chief Collection",
    year: 2019,
    genres: ["Shooter", "FPS", "Sci-fi"],
    rating: 91,
    ratingSource: "Steam",
    ratingLabel: "Steam 91% positive",
    playersMax: 4,
    playersLabel: "2-4, кампании",
    hours: 55,
    hoursLabel: "50+",
    oneCopy: "none",
    price: 1399,
    verdict: "Много законченных кампаний в одном пакете. Минус - это FPS, не постановочный дуо-боевик.",
    storeUrl: "https://store.steampowered.com/app/976730/Halo_The_Master_Chief_Collection/",
    imageUrl: steamImage(976730),
    youtubeUrl: youtube("yTy41rmm6rk")
  },
  {
    id: "darksiders-genesis",
    title: "Darksiders Genesis",
    year: 2019,
    genres: ["Action", "Isometric", "Fantasy"],
    rating: 77,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 77",
    playersMax: 2,
    playersLabel: "2",
    hours: 13.5,
    hoursLabel: "12-15",
    oneCopy: "remote-play",
    price: 389,
    verdict: "Изометрический экшен про двух персонажей. Ближе к Diablo/Darksiders, чем к Army of Two.",
    storeUrl: "https://store.steampowered.com/app/710920/Darksiders_Genesis/",
    imageUrl: steamImage(710920),
    youtubeUrl: youtube("C7Hxw08wRfs")
  },
  {
    id: "wolfenstein-youngblood",
    title: "Wolfenstein: Youngblood",
    year: 2019,
    genres: ["Shooter", "FPS", "Action", "Sci-fi"],
    rating: 69,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 69",
    playersMax: 2,
    playersLabel: "2",
    hours: 10,
    hoursLabel: "9-12",
    oneCopy: "friend-pass",
    price: 349,
    verdict: "Кооп и кампания есть, но игра спорная. Buddy Pass работает через Deluxe Edition.",
    storeUrl: "https://store.steampowered.com/app/1056960/Wolfenstein_Youngblood/",
    imageUrl: steamImage(1056960),
    youtubeUrl: youtube("lFM7zFCVwgo")
  },
  {
    id: "far-cry-5",
    title: "Far Cry 5",
    year: 2018,
    genres: ["Shooter", "FPS", "Open World", "Action"],
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 22,
    hoursLabel: "18-25",
    oneCopy: "none",
    price: 915,
    verdict: "Открытый мир, не постановочная дуо-игра. Вдвоём весело, но сюжетно рыхло.",
    storeUrl: "https://store.steampowered.com/app/552520/Far_Cry_5/",
    imageUrl: steamImage(552520),
    youtubeUrl: youtube("n-lJd1gueOQ")
  },
  {
    id: "divinity-original-sin-2",
    title: "Divinity: Original Sin II",
    year: 2017,
    genres: ["RPG", "Tactics", "Fantasy"],
    rating: 93,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 93",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 75,
    hoursLabel: "70+",
    oneCopy: "remote-play",
    price: 529,
    verdict: "Если BG3 зайдёт, это почти обязательная следующая остановка. Кампания огромная и законченная.",
    storeUrl: "https://store.steampowered.com/app/435150/Divinity_Original_Sin_2/",
    imageUrl: steamImage(435150),
    youtubeUrl: youtube("unWFWGrMbpc")
  },
  {
    id: "ghost-recon-wildlands",
    title: "Ghost Recon Wildlands",
    year: 2017,
    genres: ["Shooter", "Third-person", "Open World", "Tactics", "Military"],
    rating: 80,
    ratingSource: "Steam",
    ratingLabel: "Steam 80% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 35,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 759,
    verdict: "Военный кооп в открытом мире. Сюжет слабее, зато двое чистят карту работает.",
    storeUrl: "https://store.steampowered.com/app/460930/Tom_Clancys_Ghost_Recon_Wildlands/",
    imageUrl: steamImage(460930),
    youtubeUrl: youtube("7UboU-rioaY")
  },
  {
    id: "portal-2",
    title: "Portal 2",
    year: 2011,
    genres: ["Puzzle", "FPS", "Sci-fi"],
    rating: 95,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic 95",
    playersMax: 2,
    playersLabel: "2, отдельная кампания",
    hours: 5,
    hoursLabel: "4-6",
    oneCopy: "remote-play",
    price: 225,
    verdict: "Если не проходил кооп-кампанию, это must-play. Не просто режим, а отдельная игра на двоих.",
    storeUrl: "https://store.steampowered.com/app/620/Portal_2/",
    imageUrl: steamImage(620),
    youtubeUrl: youtube("aySPmEBzlS4")
  },
  {
    id: "lara-croft-guardian-light",
    title: "Lara Croft and the Guardian of Light",
    year: 2010,
    genres: ["Action", "Puzzle", "Adventure", "Isometric"],
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 2,
    playersLabel: "2",
    hours: 7,
    hoursLabel: "6-8",
    oneCopy: "remote-play",
    price: 180,
    verdict: "Старенькая, но крепкая приключенческая кооп-игра с пазлами и боёвкой.",
    storeUrl: "https://store.steampowered.com/app/35130/Lara_Croft_and_the_Guardian_of_Light/",
    imageUrl: steamImage(35130),
    youtubeUrl: youtube("nER0GNRlK_c")
  },
  {
    id: "borderlands-3",
    title: "Borderlands 3",
    year: 2019,
    genres: ["Shooter", "FPS", "RPG", "Loot", "Open World"],
    rating: 81,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 81",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 23,
    hoursLabel: "22-25",
    oneCopy: "none",
    price: 849,
    verdict: "Крупная кооп-кампания с отличной стрельбой и лутом. Сюжет спорный, но вдвоём темп держит хорошо.",
    storeUrl: "https://store.steampowered.com/app/397540/Borderlands_3/",
    imageUrl: steamImage(397540),
    youtubeUrl: youtube("KojWXk9Vgso")
  },
  {
    id: "tiny-tinas-wonderlands",
    title: "Tiny Tina's Wonderlands",
    year: 2022,
    genres: ["Shooter", "FPS", "RPG", "Loot", "Fantasy"],
    rating: 80,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 80",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 17,
    hoursLabel: "16-20",
    oneCopy: "none",
    price: 1249,
    verdict: "Borderlands в фэнтези-обёртке. Хороший вариант, если хочется стрельбы, классов и более лёгкого тона.",
    storeUrl: "https://store.steampowered.com/app/1286680/Tiny_Tinas_Wonderlands/",
    imageUrl: steamImage(1286680),
    youtubeUrl: youtube("L0wnhP_mQKA")
  },
  {
    id: "dying-light",
    title: "Dying Light",
    year: 2015,
    genres: ["Action", "FPS", "RPG", "Open World", "Horror"],
    rating: 75,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 75",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 18,
    hoursLabel: "17-20",
    oneCopy: "none",
    price: 349,
    verdict: "Паркур, зомби и полный кооп кампании после вступления. Более грязный и живой вариант для двоих.",
    storeUrl: "https://store.steampowered.com/app/239140/Dying_Light/",
    imageUrl: steamImage(239140),
    youtubeUrl: youtube("pL4a6QkzkLs")
  },
  {
    id: "dying-light-2",
    title: "Dying Light 2 Stay Human",
    year: 2022,
    genres: ["Action", "FPS", "RPG", "Open World", "Horror"],
    rating: 77,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 77",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 24,
    hoursLabel: "22-28",
    oneCopy: "none",
    price: 1599,
    verdict: "Больше открытого мира и паркура, чем в первой части. Кооп есть почти на всю кампанию, прогресс сильнее завязан на хоста.",
    storeUrl: "https://store.steampowered.com/app/534380/Dying_Light_2_Stay_Human_Reloaded_Edition/",
    imageUrl: steamImage(534380),
    youtubeUrl: youtube("inetjGIjKGU")
  },
  {
    id: "shadow-warrior-2",
    title: "Shadow Warrior 2",
    year: 2016,
    genres: ["Shooter", "FPS", "Action", "Loot"],
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 13,
    hoursLabel: "12-15",
    oneCopy: "none",
    price: 600,
    verdict: "Быстрый мясной FPS с оружием, мечами и лутом. Сюжет вторичен, зато экшен в коопе бодрый.",
    storeUrl: "https://store.steampowered.com/app/324800/Shadow_Warrior_2/",
    imageUrl: steamImage(324800),
    youtubeUrl: youtube("ftciCeHHn5c")
  },
  {
    id: "strange-brigade",
    title: "Strange Brigade",
    year: 2018,
    genres: ["Shooter", "Third-person", "Action", "Adventure"],
    rating: 74,
    ratingSource: "OpenCritic",
    ratingLabel: "OpenCritic 74",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 8,
    hoursLabel: "7-9",
    oneCopy: "none",
    price: 579,
    verdict: "Пульповый кооп-шутер про экспедиции, ловушки и толпы врагов. Больше аркада, чем сюжетный дуо-боевик.",
    storeUrl: "https://store.steampowered.com/app/312670/Strange_Brigade/",
    imageUrl: steamImage(312670),
    youtubeUrl: youtube("PpAHlg2oIDQ")
  },
  {
    id: "aliens-fireteam-elite",
    title: "Aliens: Fireteam Elite",
    year: 2021,
    genres: ["Shooter", "Third-person", "Action", "Horror", "Sci-fi"],
    rating: 67,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 67",
    playersMax: 3,
    playersLabel: "до 3, миссии",
    hours: 8,
    hoursLabel: "7-10",
    oneCopy: "none",
    price: 599,
    verdict: "Трёхместный кооп по Aliens: коридоры, классы, ксеноморфы. Хорошо как вечерний шутер, слабее как история.",
    storeUrl: "https://store.steampowered.com/app/1549970/Aliens_Fireteam_Elite/",
    imageUrl: steamImage(1549970),
    youtubeUrl: youtube("6c8TrceZWS4")
  },
  {
    id: "back-4-blood",
    title: "Back 4 Blood",
    year: 2021,
    genres: ["Shooter", "FPS", "Action", "Horror"],
    rating: 77,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 77",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 749,
    verdict: "Наследник Left 4 Dead с карточной системой и кооп-кампанией. Хорошо для стрельбы, но не для плотного сюжета.",
    storeUrl: "https://store.steampowered.com/app/924970/Back_4_Blood/",
    imageUrl: steamImage(924970),
    youtubeUrl: youtube("mnjwzd0WsEQ")
  },
  {
    id: "grounded",
    title: "Grounded",
    year: 2022,
    genres: ["Survival", "Adventure", "Open World"],
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 35,
    hoursLabel: "30-45",
    oneCopy: "none",
    price: 479,
    verdict: "Выживание с историей и хорошим коопом. Не боевик, зато сильная совместная песочница с понятной целью.",
    storeUrl: "https://store.steampowered.com/app/962130/Grounded/",
    imageUrl: steamImage(962130),
    youtubeUrl: youtube("ebITJ7jQIf4")
  },
  {
    id: "nobody-saves-the-world",
    title: "Nobody Saves the World",
    year: 2022,
    genres: ["Action", "RPG", "Isometric"],
    rating: 79,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 79",
    playersMax: 2,
    playersLabel: "2",
    hours: 16,
    hoursLabel: "15-18",
    oneCopy: "none",
    price: 530,
    verdict: "Изометрический action RPG с онлайн-коопом на двоих. Не AAA, но аккуратная законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/1432050/Nobody_Saves_the_World/",
    imageUrl: steamImage(1432050),
    youtubeUrl: youtube("OZQPvKMUlkc")
  },
  {
    id: "styx-shards-of-darkness",
    title: "Styx: Shards of Darkness",
    year: 2017,
    genres: ["Stealth", "Action", "Fantasy"],
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 74",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 14,
    hoursLabel: "12-16",
    oneCopy: "none",
    price: 249,
    verdict: "Редкий полноценный кооп-стелс. Хороший кандидат, если хочется не стрелять, а синхронно прокрадываться.",
    storeUrl: "https://store.steampowered.com/app/355790/Styx_Shards_of_Darkness/",
    imageUrl: steamImage(355790),
    youtubeUrl: youtube("apwc3_A9WL8")
  },
  {
    id: "saints-row-4",
    title: "Saints Row IV: Re-Elected",
    year: 2013,
    genres: ["Shooter", "Third-person", "Action", "Open World", "Sci-fi"],
    rating: 86,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 86",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 16,
    hoursLabel: "15-18",
    oneCopy: "none",
    price: 533,
    verdict: "Безумный открытый мир с кооп-кампанией. Стоит держать в списке, но PC-кооп у серии иногда капризный.",
    storeUrl: "https://store.steampowered.com/app/206420/Saints_Row_IV_ReElected/",
    imageUrl: steamImage(206420),
    youtubeUrl: youtube("kzDK1IYo9nw")
  },
  {
    id: "borderlands-2",
    title: "Borderlands 2",
    year: 2012,
    genres: ["Shooter", "FPS", "RPG", "Loot", "Open World"],
    rating: 91,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 91",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 30,
    hoursLabel: "28-35",
    oneCopy: "none",
    price: 389,
    verdict: "Классика 4-местного лутер-шутера. Огромная кампания, тонны оружия, кооп с самого старта.",
    storeUrl: "https://store.steampowered.com/app/49520/Borderlands_2/",
    imageUrl: steamImage(49520),
    youtubeUrl: youtube("KsNZ6eOJl0c")
  },
  {
    id: "diablo-4",
    title: "Diablo IV",
    year: 2023,
    genres: ["Action", "RPG", "Loot", "Fantasy", "Isometric"],
    rating: 86,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 86",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 30,
    hoursLabel: "28-35",
    oneCopy: "none",
    price: 1696,
    verdict: "Большая кампания с актами и нормальной концовкой. Онлайн-кооп на двоих работает без сюрпризов.",
    storeUrl: "https://store.steampowered.com/app/2344520/Diablo_IV/",
    imageUrl: steamImage(2344520),
    youtubeUrl: youtube("wH72EpRepWM")
  },
  {
    id: "vermintide-2",
    title: "Warhammer: Vermintide 2",
    year: 2018,
    genres: ["Action", "FPS", "Fantasy", "Horror"],
    rating: 82,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 82",
    playersMax: 4,
    playersLabel: "до 4, миссии",
    hours: 22,
    hoursLabel: "20-25",
    oneCopy: "none",
    price: 18,
    verdict: "Кооп-резня в фэнтези. Миссии короткие, кампания развёртывается по актам и доходит до финала.",
    storeUrl: "https://store.steampowered.com/app/552500/Warhammer_Vermintide_2/",
    imageUrl: steamImage(552500),
    youtubeUrl: youtube("4VadHTHJ-K8")
  },
  {
    id: "left-4-dead-2",
    title: "Left 4 Dead 2",
    year: 2009,
    genres: ["Shooter", "FPS", "Action", "Horror"],
    rating: 89,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 89",
    playersMax: 4,
    playersLabel: "до 4, кампании",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "none",
    price: 225,
    verdict: "Эталон коопа от Valve. Пять отдельных кампаний, каждая со своим финалом.",
    storeUrl: "https://store.steampowered.com/app/550/Left_4_Dead_2/",
    imageUrl: steamImage(550),
    youtubeUrl: youtube("RvMFOsm4WmU")
  },
  {
    id: "the-forest",
    title: "The Forest",
    year: 2018,
    genres: ["Survival", "Horror", "Adventure", "Open World"],
    rating: 96,
    ratingSource: "Steam",
    ratingLabel: "Steam 96% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 15,
    hoursLabel: "12-18",
    oneCopy: "none",
    price: 279,
    verdict: "Выживание-хоррор с настоящим сюжетом и концовкой. Строй базу, исследуй пещеры.",
    storeUrl: "https://store.steampowered.com/app/242760/The_Forest/",
    imageUrl: steamImage(242760),
    youtubeUrl: youtube("62imEBDF2rE")
  },
  {
    id: "sons-of-the-forest",
    title: "Sons of the Forest",
    year: 2024,
    genres: ["Survival", "Horror", "Adventure", "Open World"],
    rating: 86,
    ratingSource: "Steam",
    ratingLabel: "Steam 86% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 25,
    hoursLabel: "22-30",
    oneCopy: "none",
    price: 600,
    verdict: "Продолжение The Forest: карта больше, монстры жёстче. Концовка есть, кооп онлайн.",
    storeUrl: "https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/",
    imageUrl: steamImage(1326470),
    youtubeUrl: youtube("lSJSVtkhRck")
  },
  {
    id: "man-of-medan",
    title: "The Dark Pictures: Man of Medan",
    year: 2019,
    genres: ["Adventure", "Horror"],
    rating: 71,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 71",
    playersMax: 5,
    playersLabel: "2-5, кампания",
    hours: 6,
    hoursLabel: "5-7",
    oneCopy: "friend-pass",
    price: 545,
    verdict: "Кинематографичный хоррор. Один владеет, второй заходит бесплатно через Friend's Pass.",
    storeUrl: "https://store.steampowered.com/app/1024480/The_Dark_Pictures_Anthology_Man_of_Medan/",
    imageUrl: steamImage(1024480),
    youtubeUrl: youtube("UyBYdhfAxvY")
  },
  {
    id: "magicka-2",
    title: "Magicka 2",
    year: 2015,
    genres: ["Action", "Adventure", "Fantasy", "Isometric"],
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 74",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 369,
    verdict: "Хаотичный кооп с комбинированием элементов. Короткая, но смешная законченная кампания.",
    storeUrl: "https://store.steampowered.com/app/238370/Magicka_2/",
    imageUrl: steamImage(238370),
    youtubeUrl: youtube("o3NQb5zvBKY")
  },
  {
    id: "peak",
    title: "PEAK",
    year: 2025,
    genres: ["Adventure", "Action"],
    rating: 94,
    ratingSource: "Steam",
    ratingLabel: "Steam 94% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 5,
    hoursLabel: "3-8",
    oneCopy: "none",
    price: 98,
    verdict: "Кооп-челлендж: добраться до вершины. Не сюжет, но финал есть — каждый забег как короткая история.",
    storeUrl: "https://store.steampowered.com/app/3527290/PEAK/",
    imageUrl: steamImage(3527290),
    youtubeUrl: youtube("u_vlCvsf8dg")
  },
  {
    id: "raft",
    title: "Raft",
    year: 2022,
    genres: ["Survival", "Adventure", "Open World"],
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam 92% positive",
    playersMax: 8,
    playersLabel: "до 8",
    hours: 30,
    hoursLabel: "25-40",
    oneCopy: "none",
    price: 430,
    verdict: "Survival на плоту с финальной сюжетной аркой. Кооп до 8 человек онлайн.",
    storeUrl: "https://store.steampowered.com/app/648800/Raft/",
    imageUrl: steamImage(648800),
    youtubeUrl: youtube("iyU4_RR0l0o")
  },
  {
    id: "broforce",
    title: "Broforce",
    year: 2015,
    genres: ["Action", "Platformer", "Shooter"],
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam 95% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 325,
    verdict: "Короткий мясной кооп-боевик. Кампания заканчивается, заходит на пару вечеров.",
    storeUrl: "https://store.steampowered.com/app/274190/Broforce/",
    imageUrl: steamImage(274190),
    youtubeUrl: youtube("DHmKxqMId_w")
  },
  {
    id: "castle-crashers",
    title: "Castle Crashers",
    year: 2012,
    genres: ["Action", "RPG", "Fantasy"],
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam 95% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 229,
    verdict: "Классический beat'em up на четверых. Старый, но один из лучших коопов — прошёл и закрыл.",
    storeUrl: "https://store.steampowered.com/app/204360/Castle_Crashers/",
    imageUrl: steamImage(204360),
    youtubeUrl: youtube("Ek2Eoivlwhs")
  },
  {
    id: "cuphead",
    title: "Cuphead",
    year: 2017,
    genres: ["Action", "Platformer", "Shooter"],
    rating: 93,
    ratingSource: "Steam",
    ratingLabel: "Steam 93% positive",
    playersMax: 2,
    playersLabel: "2, локально",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Боссы и платформинг в стиле 30-х. Кооп локальный — удалённо через Remote Play.",
    storeUrl: "https://store.steampowered.com/app/268910/Cuphead/",
    imageUrl: steamImage(268910),
    youtubeUrl: youtube("Ygdm1ltqC6c")
  },
  {
    id: "tmnt-shredders-revenge",
    title: "TMNT: Shredder's Revenge",
    year: 2022,
    genres: ["Action", "Adventure"],
    rating: 94,
    ratingSource: "Steam",
    ratingLabel: "Steam 94% positive",
    playersMax: 6,
    playersLabel: "до 6, кампания",
    hours: 6,
    hoursLabel: "5-7",
    oneCopy: "none",
    price: 515,
    verdict: "Бодрый beat'em up по черепашкам. Короткий, проходится за вечер-два.",
    storeUrl: "https://store.steampowered.com/app/1361510/Teenage_Mutant_Ninja_Turtles_Shredders_Revenge/",
    imageUrl: steamImage(1361510),
    youtubeUrl: youtube("RlviJbgWEEE")
  },
  {
    id: "cat-quest-2",
    title: "Cat Quest II",
    year: 2019,
    genres: ["Action", "RPG", "Adventure", "Fantasy"],
    rating: 92,
    ratingSource: "Steam",
    ratingLabel: "Steam 92% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Простая action-RPG про двух котов. Приятная, заканчивается, идеально без напряга.",
    storeUrl: "https://store.steampowered.com/app/914710/Cat_Quest_II/",
    imageUrl: steamImage(914710),
    youtubeUrl: youtube("RPfKh3FMk5s")
  },
  {
    id: "lovers-spacetime",
    title: "Lovers in a Dangerous Spacetime",
    year: 2015,
    genres: ["Action", "Adventure", "Sci-fi"],
    rating: 90,
    ratingSource: "Steam",
    ratingLabel: "Steam 90% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 5,
    hoursLabel: "4-6",
    oneCopy: "remote-play",
    price: 229,
    verdict: "Один космический корабль на двоих. Чистый кооп ради коопа — всё на коммуникацию.",
    storeUrl: "https://store.steampowered.com/app/252110/Lovers_in_a_Dangerous_Spacetime/",
    imageUrl: steamImage(252110),
    youtubeUrl: youtube("r9JButWd1zI")
  },
  {
    id: "children-of-morta",
    title: "Children of Morta",
    year: 2019,
    genres: ["Action", "RPG", "Fantasy"],
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam 87% positive",
    playersMax: 2,
    playersLabel: "2",
    hours: 15,
    hoursLabel: "12-18",
    oneCopy: "none",
    price: 329,
    verdict: "Story-driven roguelite про семью защитников. В коопе работает приятно.",
    storeUrl: "https://store.steampowered.com/app/330020/Children_of_Morta/",
    imageUrl: steamImage(330020),
    youtubeUrl: youtube("Xs8wgjSBVI4")
  },
  {
    id: "full-metal-furies",
    title: "Full Metal Furies",
    year: 2018,
    genres: ["Action", "RPG", "Adventure"],
    rating: 87,
    ratingSource: "Steam",
    ratingLabel: "Steam 87% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "none",
    price: 415,
    verdict: "Недооценённый кооп-экшен от создателей Rogue Legacy. Заточен под командную игру.",
    storeUrl: "https://store.steampowered.com/app/416600/Full_Metal_Furies/",
    imageUrl: steamImage(416600),
    youtubeUrl: youtube("KjUrQmHv_w0")
  },
  {
    id: "escape-academy",
    title: "Escape Academy",
    year: 2022,
    genres: ["Puzzle", "Adventure"],
    rating: 83,
    ratingSource: "Steam",
    ratingLabel: "Steam 83% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 6,
    hoursLabel: "5-8",
    oneCopy: "none",
    price: 279,
    verdict: "Эскейп-румы в виде игры. Хороший вариант, если хочется думать, а не стрелять.",
    storeUrl: "https://store.steampowered.com/app/1812090/Escape_Academy/",
    imageUrl: steamImage(1812090),
    youtubeUrl: youtube("Gowvcv6c_Bs")
  },
  {
    id: "journey-savage-planet",
    title: "Journey to the Savage Planet",
    year: 2021,
    genres: ["Adventure", "Action", "Sci-fi"],
    rating: 84,
    ratingSource: "Steam",
    ratingLabel: "Steam 84% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "none",
    price: 635,
    verdict: "Кооп-экспедиция на странной планете. Прохождение до финала, без гриндфеста.",
    storeUrl: "https://store.steampowered.com/app/973810/Journey_To_The_Savage_Planet/",
    imageUrl: steamImage(973810),
    youtubeUrl: youtube("G6hMPSNVcJU")
  },
  {
    id: "revenge-savage-planet",
    title: "Revenge of the Savage Planet",
    year: 2025,
    genres: ["Adventure", "Action", "Sci-fi"],
    rating: 83,
    ratingSource: "Steam",
    ratingLabel: "Steam 83% positive",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "10-15",
    oneCopy: "none",
    price: 555,
    verdict: "Прямое продолжение Journey. Кооп онлайн и split-screen — прямо в тему расширенного списка.",
    storeUrl: "https://store.steampowered.com/app/2787320/Revenge_of_the_Savage_Planet/",
    imageUrl: steamImage(2787320),
    youtubeUrl: youtube("0O-T24Mq77A")
  },
  {
    id: "trine-2",
    title: "Trine 2: Complete Story",
    year: 2013,
    genres: ["Puzzle", "Platformer", "Fantasy"],
    rating: 95,
    ratingSource: "Steam",
    ratingLabel: "Steam 95% positive",
    playersMax: 3,
    playersLabel: "до 3, кампания",
    hours: 9,
    hoursLabel: "8-12",
    oneCopy: "remote-play",
    price: 279,
    verdict: "Раз есть Trine 5, логично взять и Trine 2 — самую любимую часть серии.",
    storeUrl: "https://store.steampowered.com/app/35720/Trine_2_Complete_Story/",
    imageUrl: steamImage(35720),
    youtubeUrl: youtube("yxIaDq9aKPY")
  },
  {
    id: "guacamelee-2",
    title: "Guacamelee! 2",
    year: 2018,
    genres: ["Action", "Platformer", "Adventure"],
    rating: 88,
    ratingSource: "Steam",
    ratingLabel: "Steam 88% positive",
    playersMax: 4,
    playersLabel: "до 4, локально",
    hours: 10,
    hoursLabel: "8-12",
    oneCopy: "remote-play",
    price: 430,
    verdict: "Метроидвания с боями и платформингом. Локальный кооп до 4 человек.",
    storeUrl: "https://store.steampowered.com/app/534550/Guacamelee_2/",
    imageUrl: steamImage(534550),
    youtubeUrl: youtube("f-b9PJKunww")
  },
  {
    id: "risk-of-rain-2",
    title: "Risk of Rain 2",
    year: 2020,
    genres: ["Action", "Shooter", "Sci-fi"],
    rating: 93,
    ratingSource: "Steam",
    ratingLabel: "Steam 93% positive",
    playersMax: 4,
    playersLabel: "до 4",
    hours: 25,
    hoursLabel: "20+, реплеи",
    oneCopy: "none",
    price: 108,
    verdict: "Рогалик-шутер: забег заканчивается финальным боссом, но это не сюжетная кампания.",
    storeUrl: "https://store.steampowered.com/app/632360/Risk_of_Rain_2/",
    imageUrl: steamImage(632360),
    youtubeUrl: youtube("qBRe2NDdN1E")
  },
  {
    id: "overcooked-all-you-can-eat",
    title: "Overcooked! All You Can Eat",
    year: 2021,
    genres: ["Puzzle", "Action"],
    rating: 85,
    ratingSource: "Steam",
    ratingLabel: "Steam 85% positive",
    playersMax: 4,
    playersLabel: "до 4, кампания",
    hours: 20,
    hoursLabel: "15-25",
    oneCopy: "remote-play",
    price: 800,
    verdict: "Party-кооп про кухню. Кампании заканчиваются, но это не приключение, а тест нервов.",
    storeUrl: "https://store.steampowered.com/app/1243830/Overcooked_All_You_Can_Eat/",
    imageUrl: steamImage(1243830),
    youtubeUrl: youtube("GS81-vvSo2U")
  },
  {
    id: "a-way-out",
    title: "A Way Out",
    year: 2018,
    genres: ["Action", "Adventure", "Third-person"],
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 6,
    hoursLabel: "6",
    oneCopy: "friend-pass",
    price: 799,
    verdict: "Спрятано: уже пройдено. Полностью построено вокруг дуо.",
    storeUrl: "https://store.steampowered.com/app/1222700/A_Way_Out/",
    imageUrl: steamImage(1222700),
    youtubeUrl: youtube("87HIFtmB948"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "it-takes-two",
    title: "It Takes Two",
    year: 2021,
    genres: ["Action", "Adventure", "Puzzle", "Platformer"],
    rating: 89,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 89",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 12,
    hoursLabel: "11-14",
    oneCopy: "friend-pass",
    price: 999,
    verdict: "Спрятано: уже пройдено. Friend's Pass закрывает покупку второй копии.",
    storeUrl: "https://store.steampowered.com/app/1426210/It_Takes_Two/",
    imageUrl: steamImage(1426210),
    youtubeUrl: youtube("SPa5JXzPaAk"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "split-fiction",
    title: "Split Fiction",
    year: 2025,
    genres: ["Action", "Adventure", "Platformer", "Sci-fi", "Fantasy"],
    rating: 91,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 91",
    playersMax: 2,
    playersLabel: "строго 2",
    hours: 15,
    hoursLabel: "14-16",
    oneCopy: "friend-pass",
    price: 1299,
    verdict: "Спрятано: уже пройдено. Эталонная проверка поля Friend Pass.",
    storeUrl: "https://store.steampowered.com/app/2001120/Split_Fiction/",
    imageUrl: steamImage(2001120),
    youtubeUrl: youtube("fcwngWPXQtg"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "resident-evil-5",
    title: "Resident Evil 5",
    year: 2009,
    genres: ["Shooter", "Third-person", "Action", "Horror"],
    rating: 86,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 86",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "10-14",
    oneCopy: "none",
    price: 649,
    verdict: "Спрятано: уже пройдено. Классический кооп-боевик Capcom.",
    storeUrl: "https://store.steampowered.com/app/21690/Resident_Evil_5/",
    imageUrl: steamImage(21690),
    youtubeUrl: youtube("qUsTgI0cs4c"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "resident-evil-6",
    title: "Resident Evil 6",
    year: 2013,
    genres: ["Shooter", "Third-person", "Action", "Horror"],
    rating: 69,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 69",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 21,
    hoursLabel: "20-22",
    oneCopy: "none",
    price: 649,
    verdict: "Спрятано: уже пройдено. Много кампаний, много хаоса, спорная репутация.",
    storeUrl: "https://store.steampowered.com/app/221040/Resident_Evil_6/",
    imageUrl: steamImage(221040),
    youtubeUrl: youtube("mI6TntXFfZY"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "dead-space-3",
    title: "Dead Space 3",
    year: 2013,
    genres: ["Shooter", "Third-person", "Action", "Horror", "Sci-fi"],
    rating: 78,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic PC 78",
    playersMax: 2,
    playersLabel: "2, кампания",
    hours: 12,
    hoursLabel: "11-13",
    oneCopy: "none",
    price: 699,
    verdict: "Спрятано: уже пройдено. Кооп сильнее меняет тон игры, чем в первых двух частях.",
    storeUrl: "https://store.steampowered.com/app/1238060/Dead_Space_3/",
    imageUrl: steamImage(1238060),
    youtubeUrl: youtube("cZ3mad7SOBg"),
    hidden: true,
    hiddenReason: "Уже играли"
  },
  {
    id: "army-of-two",
    title: "Army of Two",
    year: 2008,
    genres: ["Shooter", "Third-person", "Action", "Military"],
    rating: 74,
    ratingSource: "Metacritic",
    ratingLabel: "Metacritic console 74",
    playersMax: 2,
    playersLabel: "2",
    hours: 7,
    hoursLabel: "6-8",
    oneCopy: "none",
    price: 0,
    verdict: "Спрятано: уже пройдено и оставлено как референс. Не является активным PC-кандидатом.",
    storeUrl: "https://en.wikipedia.org/wiki/Army_of_Two_(video_game)",
    imageUrl: "https://i.ytimg.com/vi/WbggbjbHphA/hqdefault.jpg",
    youtubeUrl: youtube("WbggbjbHphA"),
    hidden: true,
    hiddenReason: "Уже играли / референс"
  }
];
